### ISSUE TITLE
Backgrounds

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#104]
This is simply a stub indicating that Backgrounds need to be created. Ideas for backgrounds should open new issues and reference this issue.

**Comment by queryluke** [comment]
See also #223

**Comment by bpmcpherson** [comment]
An idea occurred to me this morning for what could be some backgrounds. They may be specific to race, but they are backgrounds which have come up in the series:

Salarians - Current/Former STG Agent
Asari - Current/Former Justicar

Then a few general (which could probably be more general for the sake of a game)

C-Sec Officer (Or Law Enforcement)
Current/Former Spectre

**Comment by Duneday** [comment]
With backgrounds it may be best to avoid specifics, like going for law enforcement over C-Sec is a great example you suggested. STG could just be Spy and lose the race specific as well as maintaining the level of generality that backgrounds need. I'll definitely give it some thought and throw out some ideas myself.
