### ISSUE TITLE
Omni-gel

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#117]
Rule addition that would allow breaking weapons and armor into omni-gel.

Need cost of each charge of omni-gel plus additional uses for it:
http://masseffect.wikia.com/wiki/Omni-gel

**Comment by bpmcpherson** [comment]
An idea which is worth taking a crack at is the idea of converting the cost in credits of the item to the resulting cost of medi-gel and use that to determine how much medigel it produces. 

Perhaps it can go a step further and, if the value is there, create higher-quality medi-gel if one wishes t emphasize quality over quantity. The breakdown, if it's skill based, could simply be a higher DC for higher quality medigel.

**Comment by queryluke** [comment]
The 2 mechanics we want to introduce with omni-gel are:
1) Crafting
2) Destroying looted weapons that players don't want to use.

In either case, I'd prefer to throw out the "rarity" or damage profile of a weapon. If a weapon does more damage, it shouldn't produce more omni-gel. Rare weapons you should either use or sell (but you could turn them into omni-gel if you so wished). It's common and uncommon weapons that this is intended for.

### How much omni-gel do you get?
I was thinking something along the lines of:
pistols & smgs: 1 omni-gel
ars, shotgus, srs: 2 omni-gel
arms, legs, & head: 1 omni-gel
chest: 2 omni-gel

### How much is omni-gel worth?
I haven't done the math, but my initial idea is that 1 omni-gel = 1,000 credits. (might change when I've got time to finish up #169). The omni-gel is never as much as the weapon costs. 

### So why not sell the weapon? 
I didn't assume a player would be able to sell back a weapon for it's base cost. I was envisioning used weapons being worth much less (up to the GMs discretion, again, something I want to introduce in #169).

### So why break down weapons at all? 
Omni-gel would be required when creating armor, armor mods, weapon mods, and potentially weapons. Each "thing" would have a cost AND an omni-gel amount.  This also opens up the potential for weapon crafting. There are objectively better weapons, so one idea is to let an M-3 predator upgrade to an M-6 carnifex for X omni-gel and X credits.

### What about other materials?
I don't think I want to dive any deeper into a crafting system than what is proposed above. I.e., I don't want to try and replicate the Andromeda crafting system. Or, at least, not in the near future.

**Comment by bpmcpherson** [comment]
Yeah, I think it would be best to avoid getting too deep with components like Andromeda's crafting system.

**Comment by queryluke** [comment]
Another completely different approach which @Swampson brought up would be to incorporate omni-gel into the kits and tools. So, something like the mending power (#265) would require omni-gel, which could be purchased, but could also be attained by breaking down armor/weapons.

**Comment by Duneday** [comment]
My only concern is that the tool/kit usage could overly complicate their use and the use of omnigel overall, as well as rendering the costs of using kits and tools a bit too much.
