### ISSUE TITLE
Starting equipment for classes

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#12]

**Comment by SleightxHope** [comment]
Possible starting equipment:

If a class is proficient in a weapon type, they should receive the basic weapon for that type. I believe that other starting equipment should be racial, as I will explain below.

Choose from the following:
Assault Rifle: M-8 Avenger
Shotgun: M-23 Katana
SMG: M-4 Shuriken
Heavy Pistol: M-3 Predator
Sniper: M-92 Mantis

Each character in my campaign is a trainee Spectre, so they each start with the following:

1x Spectre Custom Modular Hardsuit (Can be Light, Medium, or Heavy Armor depending on racial proficiencies. Unavailable to Geth or other AI platforms, but they should be able to eventually do research and upgrade their chassis with better materials for an AC boost.) 

The armor has 2 upgrade slots for mods, can be improved to a maximum of 4 mod slots. As another note, my players will receive an 18 AC for Heavy Armor, as the disadvantages for using Heavy armor outweigh the benefits without a small boost.

As for racial proficiencies, I say that if a special weapon or tool kit has a race's name in the title, they should have the option to either start with that weapon/kit or its worth in credits. I.e., Krogans start with a Krogan Warhammer, Asari with an Asari sword, Drell with a Kahjean Venom Dagger, etc. 

You could expand this into Human riot shields (like Cerberus' shield troopers carry, +3 AC but +10 weight and user can only use Heavy Pistols or SMGs), Turian targeting optics (+1 to hit w/ ranged weapons), Salarian hacking aid (Omni-tool program that doubles your proficiency bonus on Hacking checks), Quarian repair kit (Omni-tool fabrication algorithm that doubles the HP you can restore to a vehicle when using your Pilot skill to repair a vehicle), Batarian honor badge (Advantage on Diplomacy checks with other Batarians), Vorcha Omni-claws (Vorcha melee attacks made with Omni-tools can be made with reach), Geth enhanced sensor tech (automatic proficiency with Perception), Volus start with 1.5x their starting currency, etc.

I've personally banned my players from playing Yahgs, too easy for them to abuse lol. Again, all just suggestions that might give each race a bit more flavor. I'm working on armor/weapon mods, should have them up by the week's end.

**Comment by SleightxHope** [comment]
An update: The Katana is friggin' stronk in my playtesting.. May wanna start your players with a weaker shotgun, the RoF on the Katana is a lot of firepower.

**Comment by queryluke** [comment]
I added a [pivot table](https://docs.google.com/spreadsheets/d/e/2PACX-1vQqEWxn624K8fJS7V1EQH3RZgRApTepIx91C2BIGEDzQTvwtvdTaHduzujhVEmPknjifAU7FFCcjJcv/pubhtml?gid=1220686586&single=true) to the weapon list. It's a little funky to read, but if you look at the columns (type) you can see each weapons "average damage", i.e. 4d6 (3.5 * 14). But it should help us decide which weapons should be starting weapons, of course I plan on auditing the stats (see below).

I originally used the ME3 weapon info to spec everything, but it looks like I got way off. For example, the lowest shotguns on the table on the Geth Plasma Shotgun and Graal Spike Thrower, which have an 87 and 80 damage output, respectively. Compared to the katana, which should only be 50. So, yeah, I'm going to have to audit all of these numbers.

In general, my rule of thumb for each weapon type was:

Shotguns: High RoF which is really more "bullet count", High Damage, but low heat (more reloading), short range
SMGs: High RoF, Low Damamge, but higher heat, short range
Sniper Rifles: Low RoF, High Damage, , low Heat, long range
Heavy Pistol: RoF based on if the weapon is single-shot, semi-auto, or burst, variable damage, high heat, medium range
Assault Rifle: RoF base on semi-auto or burst, variable damage, variable heat, mid to long range

**Comment by queryluke** [comment]
Making a note that starting equipment should be decided after pre-made armor sets have been created.

Class: Starting weapon & pre-made armor
Race: Unique Item for that race (effectively another racial perk)
Background: Money and random non-combat items
