### ISSUE TITLE
Omni-tool attacks

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#121]
Remove and create specific omni-tools that can be used as melee weapons. Move 'non-omni-tool' attacks like Biotic punch/biotic burst to cantrips.

**Comment by Swampson** [comment]
This is a great idea.

**Comment by queryluke** [comment]
I've received 2 sets of feedback about the removal of these asking to bring them back as they said their players liked having a default melee on hand. My goal is to always bring this system closer in-line with 5e, making as few rule additions as possible. So I don't want to add them back as is. But I think I should have done a better job of removing them, putting in place comparable abilities. Here is my Work-in-Progress remedy:

### Adept
* At level 1, learn the Biotic Push cantrip (cantrip TBD, but will effectively work like the old omni-tool attack).

### Vanguard
* At level 1, Learn Biotic Punch cantrip (cantrip TBD, but will work like old omni-tool attack). 
* Remove the vanguard automatically learning Barrier. There are enough spell options available that having a replenish-able barrier to use as a casting resource isn't required for a vanguard.

### Engineer
* Could piggy back on #175 
* At level 1, engineers get a melee power that they can cast for 2tp without using tp. (tp amount increasing at 5th, 11th, and 17th). Melee options would include:
  * shocking grasp
  * (fire-based melee, tbd)
  * (cold-based melee, tbd)

* At level 5, engineers get a ranged power they can cast for 3 tp without using tp. (tp amount increasing at 11th, and 17th level). Options would include:
  * incinerate
  * cryo blast
  * overload

### Infiltrators
Learn an Omni-tazer combat power (power tbd, but works like old omni-tool attack)

### Soldiers
???

### Sentinels
???

**Comment by queryluke** [comment]
Found this in the ME Wiki:

> More technically adept soldiers frequently modify their omni-tools to maximize stopping power through electrical, kinetic, or thermal energy. Some troops integrate their weapon with their kinetic barriers, transforming the omni-tool into a wrist-mounted bludgeon; others fabricate flammable gases, held in place by a mass effect field and ignited upon impact. All prove deadly surprises for opponents who expect a disarmed Alliance warrior.

So I think it makes sense to have a few other omni-* melee weapons that have the features:
* you can draw the [weapon name] as a free action (instead of a bonus action)
* Does not require a weapon slot to carry, (i.e. weight = 0)

Adepts and Vanguard would still learn their cantrips at level 1.
Engineers would still learn melee tech abilities
Infiltrators, Soldiers, and Sentinels all have the choice of utilizing these weapons but they're not automatic.
