### ISSUE TITLE
Shield Generators

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#126]
Need to figure out how these will work:

Option 1:
- Armor sets, mods, & items can each have individual shield values. Players total SP = sum of all sets/mods/items. In addition, each generator would need it's own regen speed.

Option 2:
- Each player can have a personal shield generator. Armor sets & mods can increase the potency of the shield generator. 

Option 3:
- Remove shields completely from armor sets and mods. Create a whole new item type called Shield Generators that have their own self-contained stats.

My initial thoughts:
Option 1 seems the most realistic, but also the most complicated and difficult to balance.

Option 2 is the simplest and requires the least amount of work.

I'm going to call option 3 the 'Borderlands' option, since that's how shields work in that game. It's probably the furthest removed in terms of game play, but it keeps shields as self-contained items, like magic items. I.e., no everyone would have them.

There could also be a mix of 2 & 3, where each player might start with a shield generator with a base of 5 SP, and regen of 5. But they could also find a +5 shield generator as a loot reward (10sp / 10 regen).

**Comment by Swampson** [comment]
This is what I was thinking as a possibility.

1. Armor sets have a built-in shield generator included with base price.
2. Shield generator is housed in the chest unit of the armor. We notate that all chest armor, in addition to any mod slots it may have, also has a shield "slot". No other piece of armor has a shield slot
3. Every shield generator has a base SP value and Regen speed. A high-end shield generator MAY have additional effects (e.g. resistance to fire damage).
3. We create three new types of amor mods:
  1. Shield Generators (as outlined in 2. above). Can only go into a "shield" slot on a chestpiece
  2. Shield Capacitors: dictates regen speed. Depending on how we handle regen rules, we may need to state something like "Multiple shield capacitors may be equipped, but they do not stack. The highest-rated capacitor is used when determine regen speed."
  3. Shield Augmentation Units: Adds additional effects: adds +5 shields, resistance to fire damage, deals 1d6 damage to enemy when hit with a melee attack, etc. Multiple Augs can be equipped.
4. Shield capacitors and augmentation units can fit into any armor slot.

I think we start by creating a low, medium, and high-end shield generator. Some existing armor mods can simply be re-named. Player base can homebrew or submit ideas for other mods as-needed temporarily as we work on more core updates.

**Comment by Swampson** [comment]
I was also thinking it might be cool to have a new type of consumable for "disposable" shield generators. These would be small units that could be worn on a belt or under a shirt and would be useful during undercover work or something that a VIP might wear. They should be:
-  Expensive
- Of limited capacity
- Disposable
These would be items that _might_ save your life, as opposed to the high-end SGs that are built into armor, which _will_ save your life.

**Comment by queryluke** [comment]
I'm going to create a survey for this and leave it up for a month. Maybe we'll get feedback, maybe not. But it never hurts to try

**Comment by Swampson** [comment]
I'm going to spam your survey with bots so that I get the results I want.

**Comment by queryluke** [comment]
After sleeping on it, I decided against the survey. As the game designers, if we feel the change makes the game better and more reflective of both ME and D&D 5e, we should make the change.

Once we get to version 1.0.0, which is what I would consider a fully-fledged system, we can start garnering feedback.

I like what we've come up with so let's plan to use it in the 050 release. Feel free to stark sketching out any wording updates.
