### ISSUE TITLE
post on various threads

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#145]
Once 1.0 is out need to post on various threads to increase visibility. Should probably have ANAME set up.

**Comment by queryluke** [comment]
e.g. enworld.org

**Comment by bpmcpherson** [comment]
Just to throw a few additional places out there:

Mass Effect Reddit (and the Mass Effect Andromeda Reddit when that content is fleshed out)
Tabletop Reddit
D&D Wiki - You may be able to have an article concerning your 5e homebrew, which would get exposure. 

I would also see if you could look into linking your game with other groups or systems. As a very loose example, see if perhaps the Open5e project would be willing to do a cross-promotion with you. You both benefit from the exposure and it can never hurt to ask.
