### ISSUE TITLE
'Special Thermal Clips' should be weapon mods

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#154]
Initially, I was using the Mass Effect: Andromeda mechanic, in which something like incendiary ammo is added for the duration of the clip. However, I feel this is both confusing (distinction between thermal clips and and special thermal clips) and doesn't really fit into the 'reality' of the ME Universe. Thermal Clips store the excess heat of the weapon, they aren't an 'ammo clip'.

When creating the list of weapon mods (see #36), special thermal clips should be refactored to weapon mods, indicating that the weapon's internal engineering has been modified to create a new ammo type.

Additionally, should consider giving these mods negative side effects (like reducing heat, rate of file, or range), which adds more flavor to the choice

**Comment by Swampson** [comment]
I completely agree with refactoring thermal clips. I’m wondering if the ammo effects should exist as permanent weapon mods or consumable items. The latter is more in line with ME fiction, but the former may be easier for streamlining gameplay. 

If they are permanent mods, can hey be turned off or on, maybe as a bonus action?

**Comment by Swampson** [comment]
How about this: each weapon can have only one upgrade of each type? That allows for something like a “legendary” internal upgrade that can toggle between an array of ammo types but keeps it relatively easy for GM to prevent OP guns sneaking into the game. Maybe at some point we create a customizable weapon card (similar to spell cards) that players can use to keep track of all their weapons’ abilities.
