### ISSUE TITLE
Monsters: Aliens

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#163]
Ideas can be contributed here. Current outline slated to include the following:

Rachni Soldier
Rachni Worker
Rachni Brood Warrior
Varren
Varren Alpha
Klixen
Thresher Maw
Elcor Tank
Yahg
Harvester
Kirik
Nathak
Pyjak

**Comment by BLUEmusta** [comment]
- Thresher Maw
- Kett

**Comment by bpmcpherson** [comment]
**Kett**
- Anointed - Kett shock troopers equipped kinetic barriers that wield plasma mini-guns; exalted from angara.
- Ascendant - Kett commanders who use energy barriers as both defensive and offensive weapons; exalted from a species beyond the Heleus Cluster, but enhanced with the angaran trait of bioelectricity manipulation.
- Behemoth - An experimental kett unit; exalted from krogan. (Other races could have homebrew variants)
- Chosen - Standard kett soldiers who accompany and support more specialized units; exalted from angara.
- Destined - Cloaked kett squad leaders armed with energy based shotguns; "ancestral kett" exalted from a species beyond the Heleus Cluster.
- Fiend - Hulking kett creatures with natural resistances to weapons fire and overwhelming strength; exalted from eirochs.
- Wraith - Hostile dog-like creatures capable of cloaking; exalted from challyrion.

**Remnant**
- Abyssal (Especially not sure how this one would be handled)
- Architect (Not sure how this one would be handled)
- Assembler
- Breacher
- Destroyer
- Nullifier
- Observer

 **Roekaar** - Angaran Xenophobic Extremists

**Helius Cluster Species**
- Challyrion
- Drall
- Eiroch
- Galorn
- Kaerkyn
- Rylkor
- Taurg
- Wild Adhi
