### ISSUE TITLE
Credits overview

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#169]
How much money to give out.

**Comment by BLUEmusta** [comment]
Ultimately this is going to depend on the prices that items, weapons, and armor are set at.

As a starting point, maybe decide on a gp-to-credits exchange rate and convert the rewards from the 5E loot tables into credits. The values will undoubtedly need to be tweaked a bit after some playtesting, but it'll give a baseline to adjust up or down from.

**Comment by queryluke** [comment]
Right, I think the basic outline for now is 1gp = 100 credits. This puts a starting weapon at about 35gp, which seems to track. A really nice mod for 200 gp, that might be a little low, but I think I can sketch out a basic "mission rewards" table as an outline based on level. I'll draft something and post it here.

**Comment by queryluke** [comment]
[This sheet ](https://docs.google.com/spreadsheets/d/1qNLRg1DAiaQJxJZssraUi_3DKpW8wEbPwNZTqzHN4Ew/edit?usp=sharing) is a mess, but it's a first attempt to try and nail down the spread of credits.

Here was my approach:

1. Find a "lifetime total". This factors in lifestyle, medi-gel, grenades, upgrades (and even ships which will likely be introduced later). To be honest the "upgrades" are on the conservative side of the spectrum, but I was thinking you wouldn't need to purchase every upgrade, some can be looted from the battlefield.
2. Using upper and lower bounds for individual and hoard loot totals, multiply those credits by the number of encounters it takes to get from 1-20. I ball-parked each encounter having 2 "individual" rewards and a hoard every 10 encounters.

This should be enough to get us started and with playtesting we can adjust.
