### ISSUE TITLE
Engineers lacking basic tech abilities.

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#175]
This came in from some feedback from Needleman. Which I've pondered over, and the result is this brain dump.

The syllogism follows:
* Adepts and Engineer's are the 2 ranged casting classes
* Adepts have cantrips
* Cantrips are non-resource costing, non-weapon attacks or effects
* Engineers don't have any non-resource costing, non-weapon attacks or effects

Unconsciously, I think started fixing this with the 0.4.2 change to Drones, which now have their abilities increase with level, much like a cantrip would. But drones still cost Tech Points.

On the one hand, drones are designed to exists for more than 1 round of combat. So having a drone is like having multiple available cantrips, and the initial cost in an investment for how long you want the drone to last.

On the other hand, cantrips offer more variety, in that you're not locked in for an extend period (i.e., one drone), and there are more cantrips available to choose from. Drones also don't have an advanced option, unless you're a drone jockey. Also, when running the numbers on sustained combat damage, all Engineers (except Drone Jockeys) do come up a little short.

Finally, I think the discrepancy is based on the Engineer's D&D class modeling. Originally, Tech Points were inspired by Ki points and Sorcery points. But because drones are such an integral part of an Engineer's toolbox, I feel they're more akin to Rangers (specifically Beast Master rangers).

### Possible Solutions:

__Drones cost no tech points__
Drone jockeys would need to be reworked slightly. In this iteration, you _could_ spend additional TP to buff your drones health, but it's base-line would be HP = your level (or some other logic).

__Allow all Engineers to take advanced options of the drones__
I like this, but it doesn't solve the problem for engineers at whatever level would be below where this feature is introduced.

__Reduced or no tp cost on some spells__
I.e., a feature that allows engineers to choose a tech power which would cost 1/2 or no tech points. The adept subclasses have analogous examples.

__Treating drones like ranger companions__
This would probably take the most work but is the most exciting, IMHO. Drones would have their own stat blocks and only cost 1 tp, but would last until dismissed or destroyed.

**Comment by Swampson** [comment]
As having played both an Adept and an Engineer (albeit in two very different iterations of the rules), I do think there's some merit to this. Without taking the time to consider the full implications of class balance (such as survivability and potential damage output), I do recall feeling like my Engineer was not quite as effective as I'd imagined he'd be, especially compared to my earlier Adept player.

I think that of the three options you've presented, the second one strikes the best balance between ease of implementation and overall effect on the class. I think giving an engineer a single "cantrip-like" tech power at first level would help them feel like they always have something they can be doing while they look for the perfect opportunity to use one of the powers with a higher cost.

In the long term, I really do like the idea of having drones work a bit more like ranger companions, but it seems like it could potentially have a serious impact on overall class balance and may need to be scheduled as its own milestone, or as a milestone focused on refining the classes.

**Comment by queryluke** [comment]
Cool, perhaps they can pick between one of the 'traditional' tech powers:
- Incinerate
- Overload
- Cryo Blast

And something like: can cast as a 2TP power without expending any TP. The amount increase by 1 TP at the 5th, 11th, and 17th level.

So it's great early on, but withers out at higher levels when they've got more gear and spells at their disposal.

**Comment by TheMarmotKing** [comment]
Is it cool if I comment here? I just wanted to say that making one of the base tech abilities act like a cantrip as a class feature sounds like a really good idea to me.  Maybe give them one or 2 Omni tool based utility abilities for free as well? Stuff that can be upgraded like small hacking, scanning.  I think Paragon Lost had a drone scouting enemy positions, so maybe give basic drones some utility 
And let me know if I should comment somewhere else. I'm not sure if this is just for developers, but I'll be watching all the cool changes either way!

**Comment by queryluke** [comment]
@TheMarmotKing Yes, you can definitely comment here and on any issue you want! I'm using the issues as both a means to discuss future additions/changes and for site development stuff.

Thanks for the feedback!
