### ISSUE TITLE
Race - Drell Thinktank

### ISSUE THREAD

**Issue by TheMarmotKing** [queryluke/masseffect-5e#185]
Didn't the Drell have perfect recall?  I think photographic memory is a good skill for salarians, but I would have thought Drell would have that skill or some thing like it, if only for utility

**Comment by Swampson** [comment]
This is a good point. From the Mass Effect Wiki:

>The drell possess eidetic memory, an adaptation to a world where they must remember the location of every necessary resource (vegetation, drinkable water and prey migration paths) across vast distances. The memories are so strong that an external stimulus can trigger a powerful memory recall. These recalls are so vivid and detailed that some drell may mistake it for reality. Thane Krios, for example, remembers every assassination he has ever performed and can describe them in flawless detail, and says he prefers to spend a lonely night with the perfect memory of another. This process can be involuntary.

[http://masseffect.wikia.com/wiki/Drell](http://masseffect.wikia.com/wiki/Drell)

I think the fact that it can be involuntary is important to point out for role playing a Drell, but mechanically could work the same as already exists for Salarians (expertise on one Int-based skill).

**Comment by queryluke** [comment]
https://en.wikipedia.org/wiki/Eidetic_memory#Eidetic_or_photographic_memory

So it seems like eidetic is a photographic memory on steroids that includes sensory information and vivid details.

I almost feel like we can do something mechanically with the involuntary aspect of it as well. I'll think on it.

**Comment by Swampson** [comment]
This is just a brainwave, not a fully-fledged plan:
Implementing something like the "mixed success" result other games (notably _Powered By the Apocalypse_) use. If a drell character has a very high roll on an Int check to recall something, they have the necessary memory/info. If they have a mediocre result, the DM determines which senses they remember, either deliberately or randomly). So they would inform the player "you remember hearing this" or "it felt like ..." or "you saw ..." but not necessarily give them all the info.
This is too convoluted of a system to implement just for this one rule, but might be something we can riff on.

**Comment by queryluke** [comment]
Another convoluted idea to riff off of, I was thinking a risk/reward scenario. Something like:

Reward: Expertise in X (or advantage in X). X being a skill that would reasonably translate. I'm pretty open to the reward being powerful.

Risk: Choose 1 trigger for each sensory input. Each memory is associated with one or more powerful memories. When you encounter the trigger, make a DC 15 Wisdom (or perhaps Charisma) saving throw. On a failed save, your are incapacitated for 6 seconds as the memory floods every sense in your body.

Triggers:
- Smell (e.g., a flower, type of perfume, the ocean)
- Taste (e.g., dish you ate as a child, taste of blood)
- Sight (e.g., burning flag, two people kissing, the sunset)
- Sound (e.g., a child crying, a popular musical song, church bells)
- Touch (e.g., silk along your neck, sand in your gills, being burnt),

**Comment by SrShdw** [comment]
Eidetic Memory: Always succeed checks to remember information. 

It's been done in other systems. It doesn't have to be a complex thing, and it's almost always just a ribbon ability given that most players take notes so it seems like most PCs have Eidetic memory anyways.

**Comment by queryluke** [comment]
### Proposal
* Eidetic Memory: You can recall memories in intricate detail from all your senses. Distant or inconsequential memories require a DC 14 Wisdom check. On a failure, you can only recall details from one or two senses.


### Thoughts

I really like the flair of a mixed success. It gives the GM more to play with. But I agree, lets keep it simpler for now.
