### ISSUE TITLE
Drone Jockey comparable to ranger companions

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#188]
In stubbing out the bestiary, many of the units also call forth drones. So it makes sense that a drone would be a unit in the bestiary. Thus, it also makes sense that, once drones are introduced as units (probably with the Geth), Engineers should summon drones in the same way.

Standard Engineers would summon the bestiary version of the drone. It would cost 1tp per minute. Advanced drones and the repair drone for Combat Medics would need to be reworked.

However the Drone Jockey subclass would fall in line with the Beast Conclave of the Ranger class.

### Drone Companion
With 8 hours of work and the expenditure of 5000 credits worth of materials, you create a synthetic body for one of your drones augment it's VI into a rudimentary AI, then transfer the programming into the body. If your drone companion is ever slain, 8 hours of work and the expenditure of 2500 credits worth of materials, can create a new body and replicate the AI from a backup.

You can still summon a temporary drone using your tech points.

### Drone's Bond
Your drone companion gains a variety of benefits while it is linked to you.

* The drone companion loses its Multiattack action, if it has one.
* The drone companion obeys your commands as best it can. It rolls for initiative like any other creature, but you determine its actions, decisions, attitudes, and so on. If you are incapacitated or absent, your companion acts on its own.
* Your drone companion has abilities and game statistics determined in part by your level. Your companion uses your proficiency bonus rather than its own. In addition to the areas where it normally uses its proficiency bonus, a drone companion also adds its proficiency bonus to its AC and to its damage rolls.
* Your drone companion gains proficiency in two skills of your choice. It also becomes proficient with all saving throws.
* For each level you gain after 3rd, your drone companion gains an additional hit die and increases its hit points accordingly
* Whenever you gain the Ability Score Improvement class feature, your companion’s abilities also improve. Your companion can increase one ability score of your choice by 2, or it can increase two ability scores of your choice by 1. As normal, your companion can’t increase an ability score above 20 using this feature unless its description specifies otherwise.
* Your companion shares your alignment, and has a personality trait and a flaw that you can roll for or select from the tables below. Your companion shares your ideal, and its bond is always, “The Engineer who created me is a beloved companion for whom I would gladly give my life.”

__Roll a d6 to determine companion's Trait__
1|Designation: Large. Assessment: Falls hard.
2|Eliminate!
3|Scanning for enemies...Scanning for enemies...Scanning for enemies
4|Analyzing target...Weakness identified
5|Calculating all variables...optimal action determined.
6|Prioritizing...Maker's Life > Maker's friends' lives > Self-preservation

__Roll a d6 to determine companion's Flaw__
1|Probability of survival: 0.00234%
2|Friendly creature in range. Activating CUTE protocol 
3|Electrical current detected. Priority: avoid
4| TBD
5| TBD
6| TBD

**Comment by Swampson** [comment]
Additional companion flaws:
4. Re-organize equipment/work spaces for maximum efficiency
5. Organic life requires constant monitoring and prompting to ensure optimal nutrition and peak health!

**Comment by queryluke** [comment]
I've decided this will happen when the drone's are added to the bestiary. The subclass features will follow 5th editions Beach Conclave and can be discussed after release.
