### ISSUE TITLE
New Character Sheet

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#196]

**Comment by queryluke** [comment]
From feedback form:
> No room for feats, other equipment, and background information on the character sheet.

**Comment by queryluke** [comment]
From Joey C.

1: Skills and saving throws have a distinct lack of space for putting in two things. Firstly, a tracker on which ones a character may add their proficiency modifier to, and secondly the total score number. These two have confused myself when in character creation. I resorted to underlining the skills that I was proficient in and using as small of writing as I could to put the total number in the circle. 

2: The size of the General Information section (Name, race, class...etc.) could be quite a bit smaller to both save room and allow the aforementioned changes to have requisite space. 

3: Section(s) for the Racial abilities and special techniques is missing. There is a small section for Class based abilities but lacking in the Racial section. 

4: (This is an idea) I do appreciate that you have dedicated an entire page to abilities it might be nice (as you mentioned) a possible page or even a half or one for items and their management. With information such as carry capacity, total weight, item weight, etc.

5: The section for weaponry, while I appreciate the size for ease of reading, I could say needs to be changed a bit. Shrink it to maybe 4 lines of weaponry and add smaller trackers for different Thermal clips.

6: The Shield symbol may be better off as a classical kite shield silhouette for ease of use at a glance.

7: The HP/AC section might do with adding the Barrier Ticks into it as Barrier ticks are a defensive property alongside the others.

**Comment by bpmcpherson** [comment]
To add to this, have you considered creating a digital sheet on Google Sheets that can be copied and include things like calculation formulas. I've found that such sheets are great for character generating and online games which won't be played on Roll20.

**Comment by bpmcpherson** [comment]
Here's a Google Docs cheat sheet for the system. It could be made more specific in certain areas once those rules (i.e. Rapid Reload) get sorted out.

[Mass Effect 5e Cheat Sheet](https://docs.google.com/document/d/19MV6hH00fEI-eoxU3zueDa2fKcCvp-g5jzsUwqkNSyU/edit?usp=sharing)

**Comment by queryluke** [comment]
@bpmcpherson The cheat sheet looks fantastic! Thanks!

RE: Google sheet
I was planning on creating an interactive character sheet on the site, similar to what DnD Beyond has. Ideally, there would be a print option which would pre-fill the character sheet. But, while this might be a fun challenge programmatically, the time investment would be better spent figuring out how to make a Roll20 character sheet or Google Sheets one. Alas, maybe one day.

Either way, the current character sheet needs some love, but my print-design skills are pretty lacking. I've been trying to work on one in inDesign, but it's slow going.

I'll open a new issue for a google sheet character sheet.
