### ISSUE TITLE
Forums?

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#197]
There are a lot of free forum services and this would move the discussion away from issues. But this does add the overhead of moderating the forums.

**Comment by Swampson** [comment]
My immediate reaction to this is that we shouldn't add any forums until we hit 1.0. Keeping the number of voices adding input fairly small is beneficial to faster iteration. Once we are satisfied with the 1.0 release, we can add some kind of forum or discussion platform that's a little less developer focused than Github issues. We can then shift our energy from active development to forum moderation until we have enough feedback to begin development on errata and/or a new "edition" ("Mass Effect 5e2e" - that won't confuse anyone).

**Comment by queryluke** [comment]
This can be brought up at a later date.
