### ISSUE TITLE
"Lifted" condition

### ISSUE THREAD

**Issue by Swampson** [queryluke/masseffect-5e#2]
On https://queryluke.github.io/masseffect-5e/rules/#combat, under "Condition Changes"

I don't know if it's worth formalizing this into writing, but in ME an entity that is "lifted" into the air isn't simply magically suspended, it is actually made temporarily mass-less (or near mass-less) via a mass effect field. So this could have a lot of potential complications/side effects depending on the situation and how a player may want to take advantage of it.

**Comment by queryluke** [comment]
I think this is a good idea. In fact, I'm just going to add all the 5e conditions to it's own tab for easy reference

**Comment by queryluke** [comment]
fixed with #8
