### ISSUE TITLE
Charisma void

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#203]
Via feedback, someone pointed out the lack of Charisma usage in combat. I agree there is a void, but:

* CHA can be used heavily outside of combat
* Would need to artificially insert CHA saves into spells, which would be difficult to justify
* Originally had Sentinels use CHA for Tech and Biotics, but this felt odd

I'm not sure if there is a fix, but I'm open to suggestions/discussion.

One idea that came to mind:
Racial trait or Feature that lets a race use CHA instead of WIS for their Biotic powers. Justification being "Race/person sees combat as a performance...", essentially "barding-up" the player or race.

**Comment by TheMarmotKing** [comment]
I think an argument could be made to give adepts or vanguards the option to make their skills charisma based. Adept in particular, I think could be made charisma based entirely.  Vanguard and sentinels mix and match stats, and wisdom is really useful for perception alone. Adepts could follow a more sorcerer like build to fill that void

**Comment by bpmcpherson** [comment]
Just to chime in on this matter, here is how D&D justifies Charisma in the realm of casting:

> Charisma is your spellcasting ability for your sorcerer spells, since the power of your magic relies on your ability to project your will into the world. You use your Charisma whenever a spell refers to your spellcasting ability. In addition, you use your Charisma modifier when setting the saving throw DC for a sorcerer spell you cast and when making an attack roll with one.

For Paladins, rather than Wisdom like Clerics (see below), they also use Charisma

> Charisma is your spellcasting ability for your paladin spells, since their power derives from the strength of your convictions. You use your Charisma whenever a spell refers to your spellcasting ability. In addition, you use your Charisma modifier when setting the saving throw DC for a paladin spell you cast and when making an attack roll with one.

This is contrary to Wisdom, which is often used by Clerics and Druids

> Wisdom is your spellcasting ability for your cleric spells. The power of your spells comes from your devotion to your deity. You use your Wisdom whenever a cleric spell refers to your spellcasting ability. In addition, you use your Wisdom modifier when setting the saving throw DC for a cleric spell you cast and when making an attack roll with one.

> Wisdom is your spellcasting ability for your druid spells, since your magic draws upon your devotion and attunement to nature. You use your Wisdom whenever a spell refers to your spellcasting ability. In addition, you use your Wisdom modifier when setting the saving throw DC for a druid spell you cast and when making an attack roll with one.

Finally, Intelligence is used by Wizards: 

> Intelligence is your spellcasting ability for your wizard spells, since you learn your spells through dedicated study and memorization. You use your Intelligence whenever a spell refers to your spellcasting ability. In addition, you use your Intelligence modifier when setting the saving throw DC for a wizard spell you cast and when making an attack roll with one.

For this system, Tech has become the equivalent to a Wizard's casting ability, as it requires intellect (i.e. knowledge and know-how) and "tools". We currently use Wisdom for Biotics, but we don't do so for the same reason as Clerics or Druids do, which is based on a strong devotion. In fact, Biotics more closely resemble Charisma casting in D&D as you are trying to project your will onto the world. 

Now, there could be ways where the method of biotic use differs. For instance, Asari naturally possess biotics as a species. Perhaps they could use Charisma? Conversely, TheMarmotKing presents the idea of making it class-specific, where Adepts are Charisma-based while Vanguard and Sentinel could be Wisdom.

**Comment by queryluke** [comment]
@bpmcpherson This is a good point.

It almost feels like CHA should be the standard for Biotics except for Asari who would use Wisdom, since it would reflect how attuned they are to their nascent biotic abilities.

The difficulty I'm wrestling with is balancing mechanics with lore. Mechanically, I would prefer to have the following:

Engineers & Infiltrators: Use INT
Sentinels: Use CHA (for both Tech and Biotics, just to simplify playing with them)
Adepts: Use WIS
Vanguards: Use CHA
Asari (despite class): Use WIS

I feel this strikes a balance with 5th Edition for the number of classes that can use WIS, INT, or CHA for casting spells. But I also don't want to force a square peg into a round hole.

**Comment by SrShdw** [comment]
Sentinals aren't that thin. They only need 3 abilities, Dex, Int, and Wis. Str just doesn't work well with their choice of abilities, and they don't need to up Con very high because they have their class ability.

**Comment by queryluke** [comment]
A note on the change I mentioned above, I wasn't trying to outright propose it. It's just something that makes sense in my mind. To be honest, I don't have a strong opinion on CHA or WIS for biotics. I was looking at @bpmcpherson's descriptions of the 5th edition rules and interpreted CHA being performative/external and WIS being intuition/internal. 

Discarding the race argument for a moment, I think there is reason to have Adepts use a different ability than Vanguards and Sentinels. Adepts, being the most powerful biotic, would need something "extra" or some new unique way to tap into their biotic power. This could be argued as Wisdom or Charisma.

__Note in everything below, WIS/CHA are interchangeable based on where we land on the debate__
Currently, the system has 2.5 INT, 2.5 WIS. I don't think Asari gaining CHA is enough to balance it.

So the alternative (splitting Adepts and Vanguards/Sentinels) would set 2.5 INT classes, 1.5 CHA classes, 1 WIS  class. Or if we fit Sentinels with one spellcasting ability: 2 INT, 2 CHA, 1 WIS. With Asari taking up the other WIS, this adds a small, if inferior, balance to the three abilities.

**Comment by SrShdw** [comment]
It has always seemed like Biotics were based on force of will, which is more Charisma. I'd probably say that Biotics should always key off Charisma and Tech should be based on Int, but that is just my opinion. 

Wisdom is an important stat for every character because important skills like Perception, Insight, Medicine, and Survival key off of it, so there is less fear of seeing someone dump if they aren't a Biotics user, if Charisma were made the default Biotics stat. Much unlike Intelligence in 5e, which is easily dumped by anyone not a Wizard. I don't think having an "imbalance" in the stat importance is all that worrying, especially when there are only 6 classes.

**Comment by queryluke** [comment]
Went digging into the wiki a bit. This is all on the [biotics page](http://masseffect.wikia.com/wiki/Biotics)

In background:
>They must then develop conscious control over their nervous system, which is a long, slow, difficult ordeal (except for the asari, who possess a degree of control naturally). Biofeedback therapy is commonly used to aid in this process. ... Biotic abilities are activated using a technique called "physical mnemonics", in which the biotic uses a physical gesture to cause neurons to fire in a certain sequence, sending an electrical charge through their eezo nodules and creating the desired effect. A biotic may enhance certain aspects of his or her biotic abilities by installing implant upgrades called bio-amps.

Again, I'm not sure if this speaks wisdom or charisma. But at least it's something to work on.

Additionally, under the implants section:
>L5x - In 2185, Adepts are outfitted with L5x implants.
L5n - In 2185, Vanguards are outfitted with L5n implants.

One possibility is that we augment the lore slightly and have the implants linked to an ability, something like:

* Adepts use the L5x implant, which takes considerably more conscious control over their nervous system and devotion to learning to control their inner will. You use Wisdom...
* Vanguards use the L5n implant, which hinges on the user's ability to perform physical mnemonics with grace and accuracy. You use Charisma... (I'm thinking like a Bard playing an instrument)
* Sentinels use the L5q implant, which allows them to manipulate their Omni-tool with the same biofeedback that powers their biotic abilities. Though this is what make sentinels unique, it takes intense mental strength to accomplish. (Wisdom?)
* Asari: The asari do not require biotic implants to control their abilities. Instead, their biotics talents rely on their ability to project their will onto the world. Asari Sentinels opt for a unique biofeedback device, which allows them to power thier Omni-tool with the same willpower.

Again, I'm open to any swapping of CHA and WIS for any of these.

**Comment by Duneday** [comment]
I actually like the implant idea, Id say sentinals are much closer to bards than Vanguards are and should use Cha. Other than that its a creative solution that could be melded to the needs of the system in the future as well.

**Comment by queryluke** [comment]
### Proposed change
#### Spellcasting rules section
* Remove the Nomenclature, Biotic Spells, Tech Powers, Combat Powers, and spell save DC sections.
* Replace with:

We stretch the meaning of "Spell" in Mass Effect 5e to include combat abilities that are powered by technological devices (such as an Omni-Tool). In addition, you do not need to prepare spells. Instead, your class _learns or advances_ spells as they level up. Once a spell is learned, it is always at your character's disposal.

We also break spells down into 3 distinct categories:
__Biotic Powers__ - These function exactly like spells in 5th edition. You have spell slots and regain all of your spell slots after a long rest.
__Tech Powers__ - Tech powers are fueled by Tech Points, a resource available to Engineers, Infiltrators, and Sentinels that reflects your Omni-tool's power capacity. When you spend a tech point, it is unavailable until you finish a short rest, at the end of which you recharge 1d4 tech points. Some armor mods and class feature increase this recharge rate. At the end of a long rest, you recharge all your tech points. Tech powers are unique in that most have a variable tech point cost. You can choose to spend a lot or only a few tech points when casting a power, much like you can cast spells using higher level spell slots. However, there is a limit on how many tech points you can spent to fuel a tech power. This limit is indicated in the Max TP column of your class progression table.
__Combat Powers__ - Combat powers have no casting cost, as they are generally instantiated by some sort of gadget or device. Instead of a casting cost, combat powers recharge on a short or long rest. If a combat power calls for a Spell Save, the DC will be indicated in the combat power's description. 

#### Class pages
Each class will have an additional paragraph about their spellcasting ability.

##### Adepts
Adepts have an L5x biotic implant which requires considerably more conscious control over their nervous system. As an Adept, you use your Wisdom whenever a spell refers to your spellcasting ability. In addition, you use your Wisdom modifier when setting the saving throw DC for an biotic spell you cast and when making an attack roll with one.

##### Engineers
Engineers use a highly modified Omni-tool that requires a keen intellect to maintain. As an Engineer, you use your Intelligence whenever a spell refers to your spellcasting ability. In addition, you use your Intelligence modifier when setting the saving throw DC for an tech spell you cast and when making an attack roll with one.

##### Infiltrators
Infiltrators use a highly modified Omni-tool that requires a keen intellect to maintain. As an Infiltrator, you use your Intelligence whenever a spell refers to your spellcasting ability. In addition, you use your Intelligence modifier when setting the saving throw DC for an tech spell you cast and when making an attack roll with one.

##### Sentinels
Sentinels use the L5q biotic implant, though less potent than other implants, it allows them to manipulate their Omni-tool with the same physical mnemonics that conjure their biotic abilities. As a Sentinel, you use your Charisma whenever a spell refers to your spellcasting ability. In addition, you use your Charisma modifier when setting the saving throw DC for an biotic or tech spell you cast and when making an attack roll with one.

##### Vanguards
Vanguards are outfitted with the L5n biotic implant which draws upon their inner strength of will. As a Vanguard, you use your Wisdom whenever a spell refers to your spellcasting ability. In addition, you use your Wisdom modifier when setting the saving throw DC for an biotic spell you cast and when making an attack roll with one.

#### Asari
New Racial Trait

##### Innate Biotics
Asari do not require biotic implants to control their abilities. Instead, their biotic talents rely on their ability to project their will onto the world. As an Asari, you use your Charisma whenever a spell refers to your spellcasting ability. In addition, you use your Charisma modifier when setting the saving throw DC for an biotic spell you cast and when making an attack roll with one.

Todo list:
- [ ] Update spellcasting rules page
- [ ] Update class pages
- [ ] Review spells and change any "techcasting ability" or "biotic ability" to "spellcasting ability"

**Comment by bpmcpherson** [comment]
I like the change in the wording for the powers.

However, I just now noticed that you decided against combining Sentinels casting ability into Charisma. Could you provide some insight as to how you came to that decision (I don't seem to recall any discussion and I am curious).

**Comment by queryluke** [comment]
Yes, sorry about that. I meant to write up a bit about it last night but got distracted.

So we decided to go back to the split stats for a few reasons.

### Overall
Although this still leaves a partial charisma void, people with high charisma excel in social encounters, which is the most common non-combat encounter. I say "most common" because that can vary wildly based on your game setting, but the "average" game would have a social component, combat component, and a smattering of other components (surviving in the wild, investigating a crime scene, chase scene, etc). As it stood in my initial proposal, this meant Sentinels could pump Charisma and they would have the benefit of:
1. Being superior in social situations, 
2. have access to the widest variety of spells than any other class,
3.  have a high secondary stat (STR, DEX, CON), because they only require one spellcasting stat. 

This seemed too powerful. Se we decided Sentinels should keep the stat split and should use Wisdom.

### Keeping the stat split
This is something we feel strongly about. I don't agree that Sentinels are spread too thin, in fact, I feel they're the most versatile. If we assume every class wants a primary and a secondary stat, Sentinels are one of the few that get a choice for their primary AND secondary.
* All caster sentinel: Wis / Int
* Party leader with biotic control: Wis / Cha
* Upfront fighter with high defense: Str, Con
* Tech savy gun nut: Int / Dex

The ability to use Tech AND Biotics is a bonus, it does not mean to need to pump all your points into both Wis and Int. For Min/Max, yeah, sure there is a cost. But if you're trying to Min/Max, I wouldn't suggest playing a sentinel. 

### Making Wisdom the spellcasting ability
This we feel less strongly about. But we do have our reasons. First, it's difficult to justify (even with the implants) why one class uses a certain stat over others. It plays much more nicely with the Asari race. Second, it simplifies the rules slightly. Biotics use wisdom, unless you're an Asari. Tech uses Int. Finally, the reasons provided to Sentinels using Cha instead of Wis aren't extremely strong. However, I'm still open to feedback.

**Comment by bpmcpherson** [comment]
It's understandable to me and I never had an issue with the Sentinel having to use different stats for tech and biotic powers due to their role as being versatile.

**Comment by Duneday** [comment]
I have mixed feelings here. I do see your point on the versatility, and that min/maxing should be avoided here. In my mind Sentinels were the battlefield leaders (mastermind, 5E bard/paladins), as such I look to that inspiration for how the class would be set up on a basic level when in 5E both Bards and Paladins use Cha as spellcasting ability. On the points against the melding I do have more thoughts.

1. An Asari adept will in general be better than a Sentinel in combat and equivalent in social situations, meaning the versatility of the Sentinel is still costing them effectiveness here.
2. While having access to tech and Biotics could be seen as a versatile strength I think it is being overvalued here. Their spell/ability list is already limited meaning that they will never be as effective as a full engineer or Adept caster no matter how they push their stats again a versatility has already cost them effectiveness. 
3. The same argument is presented here. Their versatility is already limiting them I see no reason to further limit them by forcing an additional stat split or sacrificing a class feature.
4. Being able to (or forced to depending on how you see it) pick how you weight the value of a stat is arguably not a strength, and to argue that the ability to use tech and biotics as a "bonus" is a bit of a fallacy to me as they are limited casters already and the casting is a main feature of the class. 

Overall:
Ultimately versatility already costs the Sentinel the ability to be competitive with every other class in the game, Further limiting them by forcing stat splits or hurting an already limited casting seems way too far for something that is already balanced when we look to the base classes (paladin/Bard).

**Comment by queryluke** [comment]
@Duneday Overall, I think we need to agree to disagree. I understand you want to play a Sentinel, and I understand you find fault with the stat split. As such, I would say you can work it out with @bpmcpherson to make a house rule to use one stat and whether the stat is going to be CHA or WIS.

However, there are a couple points you've made that I'd like to address.

### Class inspiration
>In my mind Sentinels were the battlefield leaders (mastermind, 5E bard/paladins), as such I look to that inspiration for how the class would be set up on a basic level when in 5E both Bards and Paladins use Cha as spellcasting ability

These three are the closest to their 5th edition counterparts.
* Infiltrators, obviously draw heavily from Rogues. 
* Adepts, draw heavily from Wizards. But have a few sorcerer features and use WIS instead of INT.
* Soliders, draw heavily from Fighters. But have a few ranger features.
These three start to differ substantially:
* Vanguards, barbarians, but they can cast spells. One subclass has warlock features. One has fighter features.
* Engineers, monks/rangers/sorcerers/clerics/wizards
* Sentinels, paladins with a touch of rogue, fighter, and pretty much anything from an engineer.

All in all, we're not looking for 1to1 conversions. When I first wrote up the first draft, I started with what I found in 5th edition and changed it as per the needs of mass effect. As such, we're not going to have Adepts use INT for biotics use because Wizards use it, and we're not going to have Vanguards use CHA just because warlocks and some barbarian subclasses use it.

### Combat effectiveness
>An Asari adept will in general be better than a Sentinel in combat and equivalent in social situations

>Ultimately versatility already costs the Sentinel the ability to be competitive with every other class in the game


This depends entirely on what you mean by "better..in combat" and "competitive". I assume you mean damage per turn. My counter is that Sentinels are not meant to be equivalent in damage. In my analyses and playtesting they don't do disproportionately less damage. A player who chooses to play a Sentinel is choosing versatility and survivability over damage.

### Stat splits as a limitation
>Further limiting them by forcing stat splits or hurting an already limited casting

We're not limiting them. They can still choose WIS/INT as their primary and secondary stats if they want a full-on caster. Of note, if a player chose to multi-class Adept/Engineer, they would have the stat splits anyway and their max potential on spells would be equivalent with Sentinels (max tp6, 3rd lvl spells).

Additionally, there are multiple instances of this in 5th edition. A max CHA paladin cannot cast spells higher than the 5th level. They're a melee spell caster. So they can't melee as well as a fighter and they can't cast spells as well as a cleric. It doesn't mean they can use CHA as their melee weapon attacks. This also happens with Rangers. Eldritch Knights (Fighters), Arcane Tricksters (Rogues), and I'm sure there are others. The main difference is that in each of those cases you're splitting between a weapon attack and a spell attack. Well, Sentinels certainly offer that choice. Go heavy Dex for ranged weapons and heavy Wis for your biotic spells. In this example, they're just as limited as a Paladin in 5th edition.

### Class stat priorities
>Being able to (or forced to depending on how you see it) pick how you weight the value of a stat is arguably not a strength

Here is how I interpret your statement: "Each class should have a clearly defined primary and secondary stat which complements the class's features and abilities". To this, I whole-heartedly disagree. Stats are a player choice not a requirement. The __Primary Ability__ is a recommendation. On Sentinels, it currently says Wisdom, but it should be Wisdom OR Intelligence, but not Wisdom AND Intelligence.

### Other ways to improve sentinels
All that being said, here are some things I'm still wide open to:
1. Improving the class features on Sentinels. It may help to reconceptualize the problem: since Sentinels have split spellcasting stats, in what _other_ ways can be improve the Sentinel toolbox.
2. Increasing the max TP, TP pool, and Spell slot progression. Essentially, this would make a more viable WIS/INT Sentinel. As it stands now, I would agree that going all WIS/INT would not be your best damage-per-turn choice. So I'm certainly open to bumping those numbers up slightly.

**Comment by queryluke** [comment]
@Duneday I'm sorry you're not feeling well! I also hope our disagreement doesn't dissuade you from contributing more feedback. You've provided a lot of thorough and well-thought-out criticism (here and everywhere else). I hope you continue to challenge and force me to make these tough decisions. With more playtesting and number crunching, I'm sure we'll find a middle-ground (or we may find out that I'm completely wrong!). I don't enjoy being the arbiter in these situations, but, currently, I want to lean on the playtesting and analyses I've done so far.

That said, I do agree a minor boost in spell slots and tech points could go a long way. Without considering class features, it would, at the very least, make a Sentinels better than a multi-classed Adept/Engineer. I've added to my todo list above to incorporate this change.
