### ISSUE TITLE
Race - Angara Concept

### ISSUE THREAD

**Issue by bpmcpherson** [queryluke/masseffect-5e#205]
Below is my take on the Angara. While I understand that your focus is on the Original Trilogy, I figured throwing some ideas around couldn't hurt. 

Possible Race Menu Image: https://vignette.wikia.nocookie.net/masseffect/images/4/44/Angara_trailer_mugs.png/revision/latest?cb=20170127022744

Possible Source for Portrait on Page: http://www.zbrushcentral.com/showthread.php?206097-Mass-Effect-Andromeda-Art-Dump/page2

# Available Classes
Engineer, Infiltrator, Soldier

# **Racial Traits**
**Speed**
10m

**Size**
Medium

**Sexy Level**
4

## **Alignment** 
Angara are emotional creatures and strongly community oriented. Their emotion-driven tendencies makes them often chaotic neutral/good.

## Ability Score Increase
Your Charisma score increases by 2, and your Constitution score increases by 1.

**Survivalists**
You have proficiency in Survival.

**Bio-electric Focus**
You can use Shocking Grasp as a cantrip, without having to spend tech points, and dealing 1d6 points of damage, but otherwise functioning the same. Charisma is your spellcasting ability for this ability. This does not count against your max number of cantrips known.

**Bio-electric Ward**
Increase your AC by 1 and you have a resistance to lightning.

**Solar Dependency**
If you fail to immerse yourself in sunlight for at least 1 hour during a day, you suffer one level of exhaustion at the end of that day. After a second day, you become poisoned in addition to exhaustion. If you spend longer that 72 hours without exposure to sunlight, you die.

## Optional Starting Credits
Instead of your class's starting equipment, you may start with 6d8 x 1000 credits to buy your own equipment.

**Comment by queryluke** [comment]
Honestly, this is great. Not only is the overall idea fantastic, but you even went so far as to include images AND sexy level (which is totally awesome and really put a smile on my face). I understand you're starting up a campaign, so feel free to adjust as you play test, but I'll can slide this in shortly after I get v0.6.0 out.

**Comment by kikibee1991** [comment]
Yay Jaal! This is beyond words,  fits them to a T!

**Comment by bpmcpherson** [comment]
Before this (and the Prothean) are rolled out, it would be in our best interests to go ahead and audit them like we are doing the others.

**Comment by queryluke** [comment]
This is how I would score them:

Survival: 2
Shocking Grasp: 4-5 (like Asari cantrip)
Bio-Electric Ward: 3 (it's almost a feat, but not quite, and I don't think the resistance to lightning would apply to the shields)
Solar Dependency: -1

Total: 10

So they are a little light. I'll change back to discussion open.
