### ISSUE TITLE
Suggestion: Introduce Limit to Turbocharge Duration

### ISSUE THREAD

**Issue by bpmcpherson** [queryluke/masseffect-5e#214]
From looking at Turbocharge, there appears to be a nasty loophole where the power could last near indefinitely given the right kind of circumstances. As the duration is based on shield remaining up, having a high shield threshold and regeneration rate, along with the ability to turn it on and off, using it while at a distance a la sniper (thus shield is not having to be used for defense), or all of the above could mean that the ability lasts an entire encounter or series of encounters as your shields never completely deplete.

The simplest solution would be to at least add a "or until the end of the encounter" limiter to keep it from spanning multi-encounter sessions.

**Comment by queryluke** [comment]
@bpmcpherson I should have pinged you so you'd have seen I commented about this.

**Comment by bpmcpherson** [comment]
I'm partial to the latter of the two options, but I'll make sure that my other players weigh in on the change to see how they feel.

**Comment by bpmcpherson** [comment]
So it basically becomes a power which you can use if you would rather not reload during the turn or to capitalize on an increased number of attacks? That's the key benefit of Turbocharge.

The advanced options seem fine and line up with the kinds you saw on the power advancement (more spamming of bullets or stability).

**Comment by queryluke** [comment]
@bpmcpherson Yeah...it might be a little weak. Perhaps it gives an extra attack as well? You can only use it once per short rest. I don't think it's too OP with an extra attack. Let's see:

Sharpshooter Soldier:
* First round of combat gets Snap Shot (+1 Attack)
* Uses turbo charge as bonus action (+1 Attack, +1dmg / attack)
* They've got 5 attacks, so with triple heat, their best weapon option is anything with at least 2 heat (1 heat would only allow 4 attacks), which would be the M-29 Incisor (3d6)
* Let's say they've got a +3 mod

3d6 + 5 + 3 = 18.5 * 5 = 92 dmg in a round. I'm sure there are other buffs, but having this once per combat is ok with me.

**Comment by queryluke** [comment]
I removed the proposal because I want more time to think about this. I'm starting to wonder if my idea for #215 might be better for Turbocharge.

**Comment by queryluke** [comment]
### Proposal

Assuming we introduce the _burst fire_ mechanic from #282, my proposal for this power would be:

As a bonus action, activate a subroutine that temporarily vents weapon heat through your armor to improve thermal clip efficiency and weapon damage. Until the end of your turn, the weapon your currently holding gains _Burst Fire_, the heat expense from using Burst Fire is 3, and you may use Burst Fire an Attack action.

Advanced options:

+2 bonus to damage rolls
+2 DC to attack rolls
