### ISSUE TITLE
Fighting Style Suggestion: Assault

### ISSUE THREAD

**Issue by bpmcpherson** [queryluke/masseffect-5e#215]
There is a gap in the fighting styles for characters who want to use ARs/two handed SMGs as their primary weapon.  Sniping doesn't allow for them to be close to enemies, so it is of limited use for players hoping to be in the thick of fighting.  Assault fighting style focuses on letting characters be "bullet hoses," keeping sustained fire downrange with minimal downtime.

**Basic Fighting Style:** Increase the Heat of any AR or SMG you have equipped by 2.  This bonus is not conferred to others if they use the weapon.
**Advanced Fighting Style:** Gain a +3 bonus to Rapid Reload checks.  If you roll a 1 on a Rapid Reload, you do not fumble the clip, but you still fail the Rapid Reload and cannot reload your weapon as a bonus action.

**Comment by Nmmoriarty** [comment]
This was originally my idea when I was talking it through with Ben.  However, with weapon mods, I'll have to look over this and see how that changes the balance of this.

**Comment by Nmmoriarty** [comment]
Alright, upon review of the mod system, I still think this is a solid addition.

All "Magazine" mods do one of three things: give a bonus to Rapid Reload, increase the heat capacity, or give a chance to not consume heat.

Taking the Assault fighting style to its fullest extent, you effectively have a permanent Quick Release Mag III with the added bonus of natural 1 not being a fumble.  If you spec'd into Sleight of Hand, then unless you roll a natural 1, you're always reloading as a bonus action.  This effectively negates the need for Quick Release mods on weapons, allowing you to take more interesting mods.  

Speaking of, Magazine Upgrade improves the heat capacity of a weapon -- would we want Assault to stack with this?  Again, this part of the fighting style gives more to low heat weapons than high, and the same applies to Magazine Upgrade (I'm sure I'll bring up my thoughts on how this particular mod works in #238), so stacking Magazine Upgrade V and this would be +12 heat, which significantly decreases downtime.  With +12 attack rolls, you could make it through a decent amount of combats without having to reload at all.

Lastly, the obvious synergy is with Heat Sink, which gets the most bang for buck with high heat weapons.  ARs and SMGs are the only ones that can take this, and everything in Assault would stack with this mechanic, effectively providing 3 extra shots (2 from the Heat Upgrade, 1 from the math coming off of Heat Sink III).

Thoughts?

**Comment by queryluke** [comment]
I definitely agreed with the void on an AR fighting style. But I think I want to figure out what to do with Rapid Reload and the Weapon Mods before nailing anything down. Either way, I like where this stands now.

**Comment by queryluke** [comment]
Here is something I toyed with for Turbocharge that might serve for an AR fighting style

__Name__: Full-Auto
__Basic__: If you are wielding an Assault Rifle, you may use your Action to go Full-Auto: Enter the targeting condition. While targeting, you create a lethal 10m cone of destruction with your weapon. Each creature within the cone must make a Dexterity saving throw (DC = 8 + your DEX modifier). On a failed save, a creature takes damage equal to the base damage of your weapon. A creature must also make the saving throw when it enters the cone for the first time on its turn or if it ends its turn there. Full-Auto lasts until the beginning of your next turn, or until the targeting condition ends. When Full-Auto ends the weapon's heat becomes 0.
__Adv__: Add your DEX modifier to Full-Auto damage rolls.

What I like about this is it elicits the idea of the "bullet-hose". What I'm not sure about is the complicated nature of interacting with the targeting condition and that the weapon profile doesn't have much interplay with the ability.

**Comment by MonocledMutineer** [comment]
Suggestion:

**Assault Trooper**
Any assault riffle, or smg that you are currently wielding increase it's heat by 2. Additionally, you reduce the DC on the rapid reload bonus action by 3.

_Advanced_
You can make a double tap with an assault riffle or smg, even if the weapon doesn't have the double tap tag.

Just an idea :)

**Comment by queryluke** [comment]
Closing this, we can switch discussion to #282
