### ISSUE TITLE
Salarians Possessing Shorting Resting Needs

### ISSUE THREAD

**Issue by bpmcpherson** [queryluke/masseffect-5e#216]
Something brought to my attention by my Salarian-loving friend is that the Salarian race in this system doesn't account for the lack for needing to sleep for 8 hours. I don't think it would be too difficult or overpowered to adapt the Trace Elf ability into a similar ability. 

"**High-Speed Metabolism:** Salarians don’t need to sleep for as long as other races. Instead, their unique biology requires that they only need to sleep for 1 hour a day. Salarians gain the same benefit that a human does from 8 hours of sleep."

"Salarians are noted for their high-speed metabolism, which allows them to function on just one hour of sleep a day. Their minds and bodies work faster than most sapient races, making them seem restless or hyperactive. The drawback of this active metabolism is a short lifespan of around 40 human years."

-http://masseffect.wikia.com/wiki/Salarian

**Comment by queryluke** [comment]
That's an easy add. I've got no problem filling out races with more lore.
