### ISSUE TITLE
Race - Prothean Concept

### ISSUE THREAD

**Issue by bpmcpherson** [queryluke/masseffect-5e#218]
Below is my take on the Protheans.

Possible Race Menu Image: https://vignette.wikia.nocookie.net/masseffect/images/1/1c/Prothean_soldiers.png/revision/latest?cb=20141206062516

Possible Source for Portrait on Page: https://vignette.wikia.nocookie.net/masseffect/images/3/39/Prothean_Profile.png/revision/latest?cb=20130412085831

# Available Classes
Adept, Soldier, Vanguard

# Racial Traits
**Speed**
10m

**Size**
Medium

**Sexy Level**
5

## Alignment
Protheans come from a society that was heavily regulated and favored the strong. They are generally lawful neutral.

## Ability Score Increase
Your Wisdom score increases by 2, and your Dexterity score increases by 1.

**All-seeing Eyes**
You have proficiency in Perception. You have truesight up to 60 ft.

**Quad-Strand DNA**
Your unique quad-strand DNA helps to protect you against radiation and cold. You have radiant and cold damage resistance.

**Psychometry**
While in physical contact with a creature or object, a Prothean can recall its experiences. If you touch an object or creature and concentrate on it for 1 minute, you learn a few basic facts about it. You gain a mental image from the object or creature's point of view, learning of any events that have occurred within 20 feet of the object or creature within the past 24 hours. If in contact with an object, you see the last creature to
hold the object, regardless of how long ago it was last handled. This ability may only be used once per long rest.

## Optional Starting Credits
Instead of your class's starting equipment, you may start with 2d10 x 1000 credits to buy your own equipment.

**Comment by TheMarmotKing** [comment]
Expertise in perception AND 60ft truesight? Combined with the other race traits, this might be a bit OP.  Maybe just proficiency for perception? Otherwise I like the design

**Comment by bpmcpherson** [comment]
The truesight ability is a unique characteristic of the Prothean race, so I wanted to try and incorporate that. Perhaps they simply get truesight at 30ft and don't gain a proficiency in perception?

**Comment by TheMarmotKing** [comment]
Ah sorry I should have clarified, I love the truesight idea, I'd just recommend proficiency instead of expertise!

**Comment by bpmcpherson** [comment]
That was actually a mistake on my part, then, as I didn't mean to make it expertise (late night 'brewing problems.)

**Comment by TheMarmotKing** [comment]
Problem solved!

**Comment by Nmmoriarty** [comment]
Surprisingly enough, Prometheans make a decent candidate for sub-races.  First is the "Ancient" Protheans as presented, though I'm sure this introduces some interesting canon conflicts.  Second is the "Awakened Collector," Collectors who broke free of Indoctrination due to the Leviathan incident.

**Comment by bpmcpherson** [comment]
From what I can gather, the Awakened Collector have the following unique abilities. 

Forewing Leap - Collectors have wings which can help them leap/move
Ascension Mode - A biotic powerup they can perform
Seeker Swarm - Not sure how to make this happen at the moment.

**Comment by bpmcpherson** [comment]
Just some additional thoughts on the matter:

**Remove:** All-seeing Eyes, Quad-Strand DNA, Psychometry

**Add:**
Chitinous Exoskeleton - +1 to Armor Class

Forewing Leap - Collectors have wings which can help them leap/move

Either a dash or bonus to leaping/moving in some way.

Ascension Mode - A biotic powerup they can perform

Think rage, but for biotics.

Seeker Swarm - Not sure how to make this happen at the moment.

Can summon a seeker swarm.

**Comment by queryluke** [comment]
Now that Asari use CHA for their spellcasting ability, would the same apply to Protheans?

In terms of points:
- 4 for all-seeing eyes (2 for perception, 2 for truesight)
- 3 for quad-strand dna
- 4 for psychometry

11 total, which is in the 10-12 range.

**Comment by queryluke** [comment]
From @HadesJester

>Hello, hello fellow ME fan! I was sitting at my desk and contemplating on how there are so many cool races that haven't been added. Now please ignore this if it has already been discussed, but I have a custom template for a Prothean race. I was playing one awhile back on 5e DnD and decided to share!

>* Speed: 10
>* Sexy Level: 5
>* +2 Intellect
>* +1 Wisdom
>* Perfect Sight: Since Protheans have 4 eyes, it would give them advantage on Perception checks.
>* Past Sense: Able to read ones past in the past week (must be a willing creature and alive). Level 6 they are able to go back a month (yes there was a huge gap between this and the actual game, but it kinda needs to be balanced, yeah?).
Feat: Any choice.

>Do know that this is what I used on 5e DnD and I'm very open to discussion. I would love to see the Prothean race on the page as a playable race.

**Comment by bpmcpherson** [comment]
I guess the question to ask are if there are thoughts on this suggested Prothean concept versus the one I submitted. 

As an aside, I based Psychometry on one of the psionic skills for 5e.
