### ISSUE TITLE
Include Timezone on Notices

### ISSUE THREAD

**Issue by bpmcpherson** [queryluke/masseffect-5e#220]
Seeing the notice this morning, I felt it might be useful to include your timezone so that there's an expectation of exactly when this is. That, or if Ruby can convert the time to the local timezone for the viewer, that would be awesome as well.

Edit: Just happened across this library [here](https://github.com/tzinfo/tzinfo) that might offer said functionality.

**Comment by queryluke** [comment]
@bpmcpherson Thanks. I'll be sure to do that in the future. I'm working on things right now (I'm actually in EST, but got a very late start). Hopefully, the downtime won't be 2 hours.

**Comment by bpmcpherson** [comment]
A fellow EST person, I see! It's no worries, I am so used to working on projects at work where timezones are critical that it stood out to me.

**Comment by queryluke** [comment]
@bpmcpherson 

ok, changes are made. If you notice any broken links or bugs, just let me know
