### ISSUE TITLE
Spells & Powers: Attack Type, Save, and Damage Type Data Not Aligned Properly

### ISSUE THREAD

**Issue by bpmcpherson** [queryluke/masseffect-5e#226]
There's a noticeable gap to the left of the data underneath the aforementioned data attributes for Spells & Powers. 
![power alignment issue](https://user-images.githubusercontent.com/1324851/38780835-9f4149f6-40aa-11e8-9938-f41feb49812a.JPG)

**Comment by queryluke** [comment]
@bpmcpherson Like #224, I think this is caused by some cached css. Can you try a [hard refresh](https://www.getfilecloud.com/blog/2015/03/tech-tip-how-to-do-hard-refresh-in-browsers/#.WtOQYojwYuU) and see if that fixes it (it did on my browser)
