### ISSUE TITLE
Suggestion/Inquiry: Sentinels and Barrier

### ISSUE THREAD

**Issue by bpmcpherson** [queryluke/masseffect-5e#227]
I've noticed that Sentinels do not have access to the Barrier ability. I wanted to know if this was an intentional choice? Back in ME1, barrier was a Sentinel power, as that was before the days of Tech Armor. It's still possible in later games to get Barrier through the bonus powers.

In any case, I just wanted to ask/bring this to attention.

**Comment by TheMarmotKing** [comment]
Access to barrier could be an option for one of the subclasses? This could also open up discussion on sentinel subclasses shifting to be more oriented to tech preference or biotic preference.  Just a thought

**Comment by queryluke** [comment]
So breaking down Tech armor. Looks like the highest possible permanent AC is 26 (can be achieved by a soldier or engineer). On top of this Soldiers can use fortification to boost themselves to 31. Sentinels get tech armor to get to 28 (29 @ lvl 20), and could also use defense matrix to get to 31. So the AC seems balanced to me. Tech armor can be used multiple times between long rests. Fortification only once every short rest.

Therefore the 'healing' (shield regen) and damage resistance is what sets Tech Armor apart. Each application of tech armor is a decent heal, pending you have the shields to accept the bonus.

Barrier, defensively, is fairly week. Even with, say, 6 ticks, the maximum amount of damage reduction is 48 and that's with perfect rolls (though Battle Master Vanguards get increased die types). And combining barrier with the damage resistance isn't overpowered either, plus vanguards could do this anyway if they purchase armor that has those resistance.

So, overall, I think adding Barrier as a Sentinel option is fine. However, I don't think I'll allow them to learn Nova. First, nova is classically Vanguard only. And in reference to my concern above, Barrier detonation and Lash don't deal additional damage when using more barrier ticks. Phase Disruptor is limited in damage by level (being a cantrip).

**Comment by bpmcpherson** [comment]
That understandable. I've always seen Nova as more of a Vanguard ability (probably due to multiplayer and spamming it with Charge).

**Comment by queryluke** [comment]
# Final decision
* Sentinels get access to Barrier, Lash, Barrier Detonation, and Phase Disruptor
* Barrier Ticks scale from 1-6 (like vanguards)
