### ISSUE TITLE
Spell - Charge, Advanced option to regen barrier ticks

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#228]
This is inline with ME3 and the iconic Charge/Nova build.

**Comment by Nmmoriarty** [comment]
Would this replace/be an addition to the targeted damage or wider AoE?

**Comment by queryluke** [comment]
### Change:

Remove __Necrotic Strike__
Replace with __Barrier Regen__
After you cast Charge, regain half of your barrier ticks (rounded down).
