### ISSUE TITLE
Race - Elcor Concept

### ISSUE THREAD

**Issue by bpmcpherson** [queryluke/masseffect-5e#229]
Everyone's favorite race, the Elcor, have returned! 

Possible Race Menu Image: 

Possible Source for Portrait on Page: https://orig00.deviantart.net/6edb/f/2011/346/3/8/mass_effect_2__elcor_reference__by_troodon80-d4ix0b1.jpg

# Available Classes
Engineer, Soldier

# Racial Traits
**Speed**
6m

**Size**
Medium

**Sexy Level**
4

## Alignment
Elcor are methodical, deliberate creatures that never act on irrational decisions. The typical Elcor is often neutral or lawful.

## Ability Score Increase
Your Constitution score increases by 2, and your Wisdom score increases by 1.

**Careful**
You take a disadvantage to Initiative rolls. You also have proficiency in Insight and Perception.

**Powerful Build** 
You count as one size larger when determining your carrying capacity and the weight you can push, drag, or lift.

**Stability of Mountains**
An Elcor has an advantage on saving throws against physical effects to push, pull, or knock it prone.

**Thick Hide**
When not wearing armour, your AC is 13 + your Dexterity modifier.

**Unstealthy**
Elcor have a disadvantage on stealth checks. 

**Quadrupedal**
Elcor walk on four legs, making it difficult to utilize normal equipment. 

## Optional Starting Credits
Instead of your class's starting equipment, you may start with 10d6 x 1000 credits to buy your own equipment.

This is still a work-in-progress, as there are a lot of nuances to consider due to their quadrupedal nature and general Elcor-ness.

**Comment by queryluke** [comment]
I agree, I'll need to do some digging into past D&D's and see if they have anything for quadrupeds. Tome of Foes is coming out in May and there may be some ideas in there as well.

**Comment by bpmcpherson** [comment]
That was the hardest part of it all. That, and they cannot use traditional weapons. According to canon, they mount vehicle-equivalent weapons (hence their "Living Tank" nickname). No idea about armor and the like.

**Comment by TheMarmotKing** [comment]
I've seen elcore in a roll20 system before, and essentially they had to pay extra for custom armor. Weapons were pretty much normal but had to be mounted on their backs and use custom vi targeting systems.  Again, extra $$ on non elcore world's.  They would however get some reasonably good buffs for using heavy weapons.

**Comment by SrShdw** [comment]
It's probably not worth adding. Elcor are like Centaurs, they should remain a statblock. The problems are already well presented, but I'd like to echo that it would slow combat and other situations down considerably. They just don't "do" fast, and adding options for them to do so would significantly break canon and probably just add more complications.

**Comment by queryluke** [comment]
Despite me saying I would include pretty much any race so long as it was balanced, I can't find any quadruped playable races in 5e. And I agree with @Nmmoriarty that speed would likely be much lower. I'm not sure if this constitutes "demonstrably unplayable." Thus, I'm still open-minded (if rather hesitant).

**Comment by bpmcpherson** [comment]
It can be left for a rainy day (or next year's April Fool's joke). It' wasn't the most important of the races (those were covered beforehand).

**Comment by queryluke** [comment]
this is in the Found Codices section of #382
