### ISSUE TITLE
Change Invasion to AI Hacking; Make Invasion have Andromeda Functionality

### ISSUE THREAD

**Issue by bpmcpherson** [queryluke/masseffect-5e#230]
Invasion as it functions now is more like the Sabotage skill present in ME3.

http://masseffect.wikia.com/wiki/AI_Hacking
http://masseffect.wikia.com/wiki/Sabotage

Invasion, as is it in Andromeda, functions very differently. There, it serves as a debuff to defense and weapon damage which can spread to nearby enemies. It can also cause a minor explosion on one upgrade path.

http://masseffect.wikia.com/wiki/Invasion_(skill)

**Comment by queryluke** [comment]
Yes, for this issue, I'm simply going to change the name of the spell, and leave the creation of Invasion open for later.
