### ISSUE TITLE
Ardat-Yakshi subrace

### ISSUE THREAD

**Issue by TheMarmotKing** [queryluke/masseffect-5e#231]
Ardat-Yakshi would be an interesting subrace for Asari.  Increase Charisma bonus to +3, remove wisdom bonus. Make biotic abilities use the Charisma modifier. (There was discussion of a charisma void earlier).  Replace mind meld (maybe call that 'embrace eternity's or something) with a more hostile Wis save ability.  And maybe impose some sort of penalty to balance out the Chance buff.

**Comment by bpmcpherson** [comment]
I'm on-board with having the Ardat-Yakshi sub-race. Here's my take on it.

**Alignment**
Ardat-Yakshi can be like any other Asari. However, should they choose to embrace their condition, their alignment shifts to Chaotic Evil as they become addicted to their lethal mind meld.

**Addicted to Power**
An Ardat-Yakshi which has used their Mind Meld ability gains a compulsion to keep using it. Each day, an Ardat-Yakshi must make a Wisdom saving throw, with a DC of 12 + your Charisma modifier . On a failed save, the Ardat-Yakshi will actively seek out a victim to perform a mind meld with. 

**Dominating Mind**
Starting at 10th level, you can use the Dominate biotic spell once per long rest. Charisma becomes your Biotic Modifier for all biotic spells.

**Embrace Eternity**
After performing a mind meld with another creature, the creature must succeed on a Constitution save throw with a DC of 10 + your Charisma modifier. Success means the creature suffers 4d6 psychic damage and is incapacitated. Failure results in fatal brain hemorrhaging. This ability may only be used once per long rest.

**Pariah**
Ardat-Yakshi are a disgrace to the Asari culture and as such, other Asari will treat you with disdain once your condition is known. All interactive abilities made towards another Asari are done at a disadvantage.

**Comment by TheMarmotKing** [comment]
I like the compulsion roll.  Adds a risk to the ability.  The disadvantage is a good one too.  Now would you use Charisma as the modifier since lvl 1 or starting at level 10?

**Comment by bpmcpherson** [comment]
In general, I suppose. I do want to make there be a general risk to using the subrace so that it's not a straight improvement.

**Comment by queryluke** [comment]
I like this idea as well. I may have to table adding it until I figure out how to handle subraces on the backend. But this is definitely a great start.

**Comment by bpmcpherson** [comment]
The one thing I couldn't think of how to handle is the fact that Ardat-Yakshi are supposed to grow in strength with each mind meld. To quote the wikia:

> While it is not known how much the Ardat-Yakshi's strength increases after each mating, or whether the victim makes any difference, Morinth's continuous use of her condition over centuries allowed her to match Samara's power and experience, despite the 500 year difference between them.

**Comment by TheMarmotKing** [comment]
Maybe add some sort of exp. Value to melding/killing victims as a varient DM option.  Causes them to level faster, rather than scale better

**Comment by bpmcpherson** [comment]
Additional XP routes are generally something I would try to avoid as to keep player levels balanced. In this case, simply an increase in power in some capacity (i.e. more spell slots, higher DC, bonus to attack, etc) would probably reflect better the difference in power vs experience.

**Comment by SrShdw** [comment]
Typically when you defeat something you get XP. If you kill a commoner, they may be worth 0 XP. It should be left up to the GM.

**Comment by SVNaas** [comment]
One problem with this, per canon most Ardat Yakshi aren’t fatal, those who are are outliers so there would need to be a lesser version for non-lethals.

**Comment by queryluke** [comment]
I've included the ardat-yakshi in v0.9.2
