### ISSUE TITLE
Rename Counterspell to Biotic Countermeasure (Or Something Similar)

### ISSUE THREAD

**Issue by bpmcpherson** [queryluke/masseffect-5e#233]
While counterspell is the literal use and inspiration, it isn't very "Mass Effect". So a simple name adjustment could go a long way to maintaining that feel.

**Comment by Nmmoriarty** [comment]
I think just "Countermeasure" would work.

**Comment by bpmcpherson** [comment]
I specify Biotic if only because it's a specific counter to Biotics and no other power type.

**Comment by BLUEmusta** [comment]
What about "Disrupt Biotics"? "Countermeasure" is a bit of a mouthful.

**Comment by queryluke** [comment]
Out of the options listed, I'm going to call it on "Disrupt Biotics". Name elicits what it does and it's not as much of a mouthful.
