### ISSUE TITLE
Race - Vocha Additions Thinktank

### ISSUE THREAD

**Issue by bpmcpherson** [queryluke/masseffect-5e#235]
Here are a few additions to the Vorcha which coincide with their lore. I'm trying to balance them along with their existing abilities.

**Non-Differentiated Cells**
You are immune to disease and the poisoned condition. 

**Limited Regeneration**
You regain 1d6 hit points every 10 minutes, provided that you have at least 1 hit point. If you lose a body part, the missing part will regrow and return to full functionality after X months.

[Source](http://masseffect.wikia.com/wiki/Vorcha)

**Comment by TheMarmotKing** [comment]
Vorcha are a bit unique, and I think they present a good opportunity to mess around.  Just a suggestion, but maybe be liberal with abilities and buffs, but give them a -1 int penalty.  It would certainly coincide with lore, and make room for some neat Regen/adaptation ability

**Comment by queryluke** [comment]
I did a quick race audit (#236). Adding these in, I'd say 1-2 points for ND Cells and Regen each, putting them at 11-13 points. A -1 Int is worth -3 in by rubric.

With that -3 penalty (dropping them down to 10), we could also add in proficiency in Survival, bringing them up to 12.

Instead of a negative Int penalty. perhaps there is a cap to vorcha intelligence: "18  is your maximum possible Int score". There can be highly intelligent Vorcha, but their ceiling is lower than other races, and 18 would still be a respectable score for a Vorcha Engineer.

**Comment by bpmcpherson** [comment]
Poor guys. Limited intelligence and an average lifespan of 20 years. Plus, they're just ugly.

**Comment by queryluke** [comment]
Pulling from #236 

Via Nmmoriarty
>The 1d6 per 10 minutes Vorcha's healing element is very strong. Effectively the Vorcha gets an average 21 hit points every hour, which is a lot of healing. Effectively, until level 11+ play, the Vorcha will never need to spend hit dice -- but the rest of the party will. The party will have to stop despite the Vorcha being able to carry on, unless the Vorcha is face taking all the damage somehow. It also is a bit out of line with the way that that 5th ed does healing

>While I do think the Vorcha should get a healing element, I think it should come from a flat bonus equal to their CON modifier per hit dice spent. This way, instead of just making impossible to seriously damage a Vorcha unless they go from full to dead in one encounter, the Vorcha gets a good healing element that allows the party to save resources -- they spend less medi-gel and other resources to get the party back in fighting condition -- but the Vorcha still take substantive damage and aren't effectively unkillable.

Via Duneday:
>While given the chance the Vorcha healing could be quite useful, in the midst of combat its likely to be of no real use. In fact, Unshackled AI's Repair Matrix is far more powerful and, in my opinion, useful. I would feel safe removing the healing factor from a mechanics standpoint as it takes a longer period of time for it to be useful usually taking a week to heal major wounds. Instead we could focus on the other adaptive elements of their biology maybe keeping a limb regeneration in order to maintain some semblance of the healing. The Vorcha are rapidly adaptive and with their cellular regeneration they also have an immunity to disease which is noticeably absent. Their adaptations to environment and damage could be a substantial replacement to the healing, maybe either giving an immunity or resistance to environment based hazards, or a resistance to the first type of damage they take in combat.

Via Damuttley:
>Vorcha regeneration takes time, and as such wouldn't be hugely viable for a campaign. Its not Piccolo regenerating his arm, but more like a starfish. Environmental resistance bonuses seems the most likely area to improve them. They are practically vermin that live in squalor where no other sentient being would live. Depending on their home environment, you could generate a table or talk with the DM and create bonuses for them. Like Vorscha living in a toxic area becoming immune to poison fumes or Vorscha living in other types or extremes gaining bonuses to reflect their adaptability. You can even change these, IF you spend enough time in an area (have to be fairly significant to override what they already have).

Via Nmmoriatry:
>While I do think Vocha should get a regenerate lost limbs mechanic, some mechanic benefit of healing (and don't forget that a long rest restores all your HP and half your HD). Hell, maybe even they restore all of their HD on a long rest so they are more inclined to take damage, since they've got more resources to restore it. All options worth considering.

Via Duneday:
>Vorcha Healing is a longer term thing taking like a week which is why id be fine seeing it reduced to a limb regeneration although I do like your idea of the full HD refund during a long rest, maybe even losing all exhaustion levels after a long rest, it gets a bit unnecessary at that point though.

**Comment by queryluke** [comment]
## Proposal

__Non-Differentiated Cells__
You are immune to disease, you and have advantage on saving throws against poison, and you have resistance against poison damage.

__Limited Regeneration__
You regain all your your Hit Dice on a long rest. Additionally, if you lose a body part, the missing part will regrow and return to full functionality after a passing of time based on the body part: 

Part | Time
----- | -----
Fingers & toes | 1 week
Eye | 6 weeks
Hands & Feet | 2 weeks
Arm (to elbow) & Leg (to knee) | 4 weeks
Arm (to shoulder) & Leg (to hip) | 8 weeks

### Thoughts
Everyone has submitted some great ideas. I've tried to meld them all together in the proposal above. I adjusted ND-Cells slightly. Straight immunity to the condition seemed a bit powerful, so I used Dwarven Resistance in 5th edition (with disease immunity added)

### Score
* __Hungry Jaws, Bite, Bloodlust__: 7 points. Overall, I'm calling this a feat + 1 (this is lower than my original score in #235, Bite and Bloodlust stand on their own as 2-3, Hungry Jaws is a long rest ability 4, so 6-7
* __ND-Cells__: 2-3 (i'm leaning towards 3)
* __Limited regen__: 2

My score is 12, but could be argued they're at 10

**Comment by bpmcpherson** [comment]
I think it's a good compromise of abilities. There are short term and long term regeneration benefits, but it will still not prevent the need for healing items, which was the concern with my proposal. 

The wording on Non-Differentiated Cells needs to be cleaned up, but the idea is solid.

**Comment by bpmcpherson** [comment]
Another thought on the limited regeneration. It has been stated that fire inhibits the regeneration effect in the series. If, and this is a big if, we wanted to incorporate that, I could see it be worded like so:

However, if you take damage from fire, all benefits of limited healing are disabled until you take a long rest.

Furthermore, another angle to the hit dice regeneration is to make their use stronger: When you roll a Hit Die to regain hit points, instead of rolling you take the highest number you could have rolled. 

That might be a bit strong, but the fact that they still have limits to hit die and, if combined with the fire weakness could curb that.

**Comment by queryluke** [comment]
I think the "fire preventing regeneration" mechanic was more for the game's combat system and not race specific. (Blood Pack [Trooper](http://masseffect.wikia.com/wiki/Blood_Pack_Trooper) & [Warrior](http://masseffect.wikia.com/wiki/Blood_Pack_Warrior))

Going to close this for now, but I think, you're right, we can re-audit the races a bit later and we can rehash this discussion about their regeneration.
