### ISSUE TITLE
Salvo and The Free Hand Advanced Perk Interaction

### ISSUE THREAD

**Issue by bpmcpherson** [queryluke/masseffect-5e#237]
I was having a discussion about this last night and just wanted to clarify how this would work:

Salvo works as follows:
> You spend tech points to create glowing darts of plasma equal to the number of tech points spent. Each dart hits a creature of your choice that you can see within range. A dart deals 1d4+1 fire damage to its target. The darts all strike simultaneously and you can direct them to hit one creature or several.

With this in mind, here is "The Free Hand" Advanced Perk:
> When wielding a pistol, you add your proficiency bonus as damage to all damaging biotic spells and tech.

So we can assume Intelligence would be added. The question then becomes, does each dart receive this damage bonus?

**Comment by Duneday** [comment]
Actually, Id have to disagree. This ahs already been explored in 5e thanks to the Hexblade curse which does the same thing adding prof to dmg of spells and MM. It was clarified that it would apply to each bolt. https://www.dndbeyond.com/forums/class-forums/warlock/8397-hexblade-and-magic-missile

**Comment by Duneday** [comment]
If you are worried about balance I would have to say an infiltrator would potentially out damage a salvo specialist by a long shot. By increasing crit range and using (really the only decent sniper which is also admittedly godlike, another issue that needs to be addressed btw) a lvl 13 infiltrator could out damage a salvo specialist (which would come online at 13 with the fighter style) without any limitations on how many shots simply needing to roll a 16 or higher on an optimized weapon.

**Comment by SrShdw** [comment]
The most elegant solution would be to only apply it to one target for techs that hit more than one.

**Comment by Duneday** [comment]
Maybe, i think if you wanted to limit it make it function exactly like the hexblade at that point and just apply the prof bonus in general to one enemy at a time.

**Comment by queryluke** [comment]
Good to know about Hexblade. I tend to lean on "If it can be done in 5th, it can be done here". It's 57 dmg per turn (maybe ~70 with a ranged weapon). But that's well within 5th edition dmg rangesfor a 17th level character.
