### ISSUE TITLE
Drell Sentinels

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#240]
Idea brought up by Duneday in #236 

>Also despite demonstrably being able to use both biotics and tech they are not able to be sentinals, which is weird and I believe an oversight.

**Comment by TheMarmotKing** [comment]
Personally when I get a chance to playtest this I'm going to be pretty liberal with class race combos.

**Comment by bpmcpherson** [comment]
I understand why they didn't have the class (there wasn't a Drell Sentinel in ME3, which featured the other classes). That being said, I feel this then opens the door for examining other instances where races have the primary classes, but not the combinations and vice versa (ex. Volus have Vanguard, but not Soldier; Turian not having Adept, but having Sentinel and Vanguard.).

Should there be limitations to who can do what based off of the games, the lore, or what? The biggest blockade has typically been biotics classes, which are limited to the races which have shown their use (with others, like Quarian and Salarian, being said that they are either extremely rare or they don't bother with it).

**Comment by queryluke** [comment]
Yeah, the wiki page for biotics explains that every alien race has some biotics. Some are rarer than others. So it could be argued that all races can play anything. Any player could come up with a backstory for a Quarian Adept. Even the non-organic races, like Geth, could be argued to have biotic abilities. Maybe the Geth created a new model that houses eezo-enhanced biotic tissue. It's a huge stretch and I wouldn't allow it as a GM, but I don't want to be the arbiter of other peoples games.

Right now, I'm thinking this might warrant a simple note in the rules section about race/class restrictions. It would first explain that the restrictions are based on the available race/class combinations in ME3 and MEA multiplayer. I would go on to say that, arguably, any race could play as any class, given the player provides justification and the GM approves.

**Comment by bpmcpherson** [comment]
That sounds like the best approach. There can be guidelines, but a GM can do whatever they want.

**Comment by Nmmoriarty** [comment]
Basically, it seems to me either a race can us biotics or it can't.  That seems to be the only logical limiter.

**Comment by bpmcpherson** [comment]
The only exception seem to be the Andromeda species.

> Biotic ability is either exceedingly rare or nonexistent in the Andromeda galaxy, even in the Heleus Cluster where eezo exists in abundance. Neither the angara nor the kett, the two living intelligent species encountered so far in Andromeda, possessed any biotics or knowledge of it prior to the arrival of the Andromeda Initiative. After discovering that asari prisoners could naturally manipulate gravity, the kett occupying the Heleus Cluster made adding biotics into their genome a priority. No kett currently exhibit biotic abilities, but their research notes show they are making progress.

**Comment by queryluke** [comment]
Thanks for that example. I think I'll include the Andromeda note and the list of "alien biotics" from the wiki page on the Race/Class Restrictions rule card I'm going to make.
