### ISSUE TITLE
Race - Asari Thinktank

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#241]
Pulling from #236 

Via Nmmoriarty:
>As for Asari, I think treating them like they have a built in Magic Initiate feat instead of just a bonus cantrip bonus would fit the flavor, and put the Asari around 11 or 12 points, rounding them out. I'm okay with them being at 11, because Asari are already an attractive choice because Asari. Or, perhaps, depending on how we want to go about this, we can give them a bonus/advantage to Persuasion checks to seduce the target -- although I do feel a little weird about it, since I'm kinda wary to build in things that players could... take too far.

Via Duneday:
>Asari could get a Racial to make their Biotic spell modifier Cha instead of Wis. This would make sense because the power to use biotics is an innate ability for Asari while other races tend to need to develop the ability. This could also be a step towards sealing the Cha void in the game, although ultimately it would pigeonhole anyone wanting to be Cha caster into being an Asari, but its a step.

Via damuttley:
>Asari could become the sorcerors of the ME5e and use CHA, since there is a gap in classes/abilities that utilize that stat. Might be worthwhile to examining giving them additional potency in biotics with either increased save DCs for them or giving them bonus spell slots (wrong terminology the first time).

Via Nmmoriarty:
>On the concept of Asari, making them switch their biotic casting stat to CHA regardless is less... useful, in my opinion that just giving them a +2 CHA and +2 WIS or something else. The only class this has any effect on is Adept, so it really doesn't help that much, since if you're going to max your casting stat anyway, why bother?

**Comment by Duneday** [comment]
On the note of the usefulness of the Cha change, it wasn't necessarily about the making the Asari better so much as the system. It lacks a Cha based PC option. There are talks going on about Sentinal and Vanguard potentially becoming Cha which would address this, but until a solution is implemented the possible solutions should be explored across the board.

**Comment by BLUEmusta** [comment]
Asari are the longest-lived species in the ME setting, and many seem to pick up a wealth of knowledge in one field or another by virtue of either formal education or accumulated life experience.

What about letting them choose an additional skill proficiency at creation, but with the caveat that it must be a Social Skill (Deception, Insight, Intimidation, Performance, Persuasion) or a Knowledge Skill (Electronics, Engineering, History, Medicine, Science)?

That'd be worth 2 points, maybe more, bringing the Asari in-line with the 11-12 mark.

**Comment by queryluke** [comment]
I do like @Nmmoriarty's suggestion of giving them Biotic Initiate (Magic Initiate).

The discussions about using a different spellcasting mod can be moved to #203.

Also, not sure if this would get overpowered, but in reference to @BLUEmusta's idea, we could say: "Gain 1 skill proficiency for each stage of Asari character: Maiden 1, Matron 2, Matriarch 3" I know the min/maxers out there would only make Matriarchs, but I think it adds nice flavor.

**Comment by bpmcpherson** [comment]
The flavor is nice, but I cannot think of how anyone would want to choose less skill proficiency.

**Comment by Swampson** [comment]
Seems like the way to handle @queryluke's idea would be to link the various life stages to character level. I know that strays from how 5e handles character progression (no racial traits unlock at level-ups) but I can't imagine a Matriarch being a Level 1 character.

**Comment by Nmmoriarty** [comment]
I agree.  Hell, I think they'd be almost locked into being Maidens.

**Comment by bpmcpherson** [comment]
Maybe as a level 1 character, but for higher levels, they could be at different stages (i.e. Samara).

**Comment by Swampson** [comment]
Yeah, I think the question would be to determine which levels "unlock" matron and matriarch. I almost wonder if there's a way to make it a trade: Matriach's get more skill proficiencies but have to give up something in return. Other systems, such as Savage Worlds, do this by having an "old" PC gain skills but take a penalty to a physical stat like Dex or Con. However, I don't know if that makes sense in the case of Asari, who seem to be just as physically potent (if not moreso) as they age.

**Comment by Duneday** [comment]
Im personally not a fan, This would mean your equating levels to age which is odd in itself. Additionally, the different stages correlate to different character traits (with outliers of course) meaning more often than not you would be RPing a different character throughout the campaign as you "aged." Finally the age differences between stages would be incongruent with simple time flow of a campaign unless your whole team is Asari a human could be born and die in the time it takes an Asari to transition once.

**Comment by Swampson** [comment]
@duneday, that’s a really good point. It wasn’t thinking about how this progression would work relative to PCs of other species.

**Comment by bpmcpherson** [comment]
The stages thing is best left as a character detail, although I do think @BLUEmusta 's original suggestion would be simple enough to include (assuming Innate Biotics wouldn't tip the scales).

**Comment by queryluke** [comment]
### Proposed Change:

Remove __Cantrip__ replace with __Biotic Initiate__
"Choose a class: Adept or Vanguard. You learn two cantrips of your choice from that class’s spell list.
In addition, choose one 1st-level spell from that same list. You learn that spell and can cast it at its lowest level. Once you cast it, you must finish a long rest before you can cast it again."

Add __Innate Biotics__ (see #203)

By the rubric, this should be enough to bring them inline with other races:
Biotic Initiate: 6 (as a feat)
Skill Versatility: 4 (it's 2 for a skill proficiency, and this is 2 of your choice)
Mind meld: 1
Innate Biotics: 1?

**Comment by queryluke** [comment]
I could go either way on Biotic Initiate being an available feat for everyone. My gut tells me to leave it out because there are only a few cantrips and this would effectively every class the ability to take one, which severely limits the draw of playing a Sentinel.

Sentinel was left out because there are no Sentinel-only biotic spells. And I didn't want someone to be confused when looking at the Sentinel spell list and think they could take a Tech power.

**Comment by bpmcpherson** [comment]
Ah, gotcha. Just wanted to be sure I understood everything. I could see it just remaining a racial ability for Asari and it can always be tweaked later.

**Comment by Nmmoriarty** [comment]
I agree that Biotic Initiate shouldn't be a feat available for others to take.  I think that Innate Biotics deserves to be 2 instead of 1 (since it aligns very strongly with their racial attributes), ultimately I don't think it matters enough to make a fluster over it.  Asari are now a very tempting choice.
