### ISSUE TITLE
Race - Krogan Thinktank

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#242]
Pulling from #236 

Via Nmmoriarty:
>Speaking of healing elements, we could add an ability to the Krogan that gives them the ability to negate a critical hit once per long rest due to their redundant systems. This helps bolster a Krogan's ability to tank hits by reducing the damage taken, rather than the Vorcha's ability to recover damage, making their flavor different.

Via bpmcpherson:
>Regarding Krogan, maybe their melee attack can be like their charge from the multiplayer, where it knocks enemies around easily?

Via Nmmoriarty:
>As far as the knockdown on Krogans, it is a good idea, but I'm not sure I am sold on it. It could get complicated, and knocking targets prone isn't necessarily the best tactical option. I still think the ability to negate a critical hit fits more in line with the Krogan's ability to soak a ton of punishment (on top of the AC bonus and Deathless ability).

Via bpmcpherson:
>But I was thinking having that along with the critical hit negate, since both are Krogan-like effects. Or at the very least, a bonus to the Shove Action
>>Shoving a Creature
Using the Attack action, you can make a special melee attack to shove a creature, either to knock it Prone or push it away from you. If you’re able to make multiple attacks with the Attack action, this attack replaces one of them.
>>The target must be no more than one size larger than you and must be within your reach. Instead of making an attack roll, you make a Strength (Athletics) check contested by the target’s Strength (Athletics) or Dexterity (Acrobatics) check (the target chooses the ability to use). If you win the contest, you either knock the target Prone or push it 5 feet away from you.

Via Duneday:
>Krogan are good, and I agree with Nmmoriarty on the ignore a single critical, probably once per long rest, to mirror their redundant physiology and give them that extra little bit of tankiness. To better mirror their biology I would argue dropping their proficiency in intimidation in favor of a proficiency in perception due to their 240 degree vision. Also even though it is not likely I believe that Krogan do possess the ability to become infiltrators it is simply not something their culture would value highly as a skillset favoring more direct confrontation.

Via damuttley:
>Krogans ignoring a crit per long rest sounds good. As does the proficiency in perception. Hard to sneak up on those jumpy toads and their huge field of view. Though they should lose this bonus when battleraging (too much focus on kersplatting to notice things).

**Comment by SrShdw** [comment]
I think Krogans should instead be given the Half-Orc ability from 5e to remain at 1 HP if they would otherwise be knocked unconscious one/long rest. It's already represented in 5e and has a "value" already assigned to it in race balance. 

If you're looking for something extra for Krogans, I suggest the minotaur ability to shove as a bonus action after a melee hit from the UA Waterborne article.

**Comment by Nmmoriarty** [comment]
@SrShdw, they already have that.  [http://n7.world/phb/races/krogan/](url)

**Comment by bpmcpherson** [comment]
Granted, Krogan are supposed to be a pain in the butt to deal with in combat. Plus, so long as the critical hit ignoring (which, to me, means it simply turns it to a normal hit) is once per long rest, it cannot be spammed.

**Comment by SrShdw** [comment]
That's why the get a bonus to constitution. And the "difficult to kill" is perfectly represented in the half-orc ability, especially since shields are in the game.

**Comment by queryluke** [comment]
Based on the rubric, they're only shy a single point. When making a decision, I think we can assume that Krogan can have subrace at some point. So we're picking for the "Standard" krogan, which I see as hearty, hard to kill, and stronger than other races. A subrace could be more "in-your-face" and get option 3 and the aggressive trait. That said, here are some additional options:

### Option 1: Shove as bonus
I'm fine with shove as a bonus action after melee hit. My only concern is that they can already shove a creature as an attack, so making it a bonus action _after_ a successful attack isn't very attractive. Personally, if I've got Extra Attack, I'd prefer to reserve my bonus actions for my class abilities and use an attack to shove.

### Option 2: Other 5th edition abilities
I looked through the 5th edition races and found these two on the Orc. This is a pick 1 scenario, I'm not recommending both be added (unless something else were removed).

>Powerful Build. You count as one size larger when determining your carrying capacity and the weight you can push, drag, or lift.

Powerful build is technically a buff to the shove action, because they're considered to be a Large creature (so they can show Huge creatures).

>Aggressive. As a bonus action, you can move up to your movement speed toward a hostile creature you can see or hear. You must end this move closer to the enemy than you started.

Not the same as their charge ability, but has some semblance.

### Option 3
Remove Rage & Natural Armor. Replace with the Charger feat. Charger is basically Dash to gain a +5 bonus to melee damage or shove the target 10 ft.

**Comment by bpmcpherson** [comment]
I'm personally a fan of Powerful Build.

**Comment by queryluke** [comment]
### Proposal
* __Powerful Build__: You count as one size larger when determining your carrying capacity and the weight you can push, drag, or lift.

### Thoughts
When I wrote up the options, I also was thinking that powerful build was the best option. I like a lot of the other options that have been mentioned, but I think we can fold those in with subraces.

**Comment by bpmcpherson** [comment]
Sounds good to me.
