### ISSUE TITLE
Race - Batarians Thinktank

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#243]
Pulling from #236 

Via Nmmoriarty:
>Batarians, on the other hand, I think could get a bonus/advantage to insight checks, given their culture's focus on caste and etiquette. They are very aware of body language, and this can translate into a bonus, picking up subtle hints to a target's intentions that others might miss.

Via Duneday:
>Batarians, I agree, could use a proficiency in Insight, but I believe intimidation could also be a viable option because, and Im quoting here, "they often gain the upper hand in interspecies arguments because other races find it difficult to know which eyes to focus on when speaking to them." They may also get an option to get starting credits equivalent to Volus as money is a major factor in their culture.

**Comment by queryluke** [comment]
### Proposed Change
Shrewd negotiator: Gain proficiency in either Insight or Intimidation.

Note: Though persuasion and deception would often be used for negotiations, from @Duneday and @Nmmoriarty's points above, I see Insight "I know what you need, I can tell when you're lying" and Intimidation "give me this or else" as what Batarians would use for their negotiation tactics.

**Comment by bpmcpherson** [comment]
Seems pretty reasonable to me. Of course, it's certainly worth consulting our local Batarian expert, @Nmmoriarty.

**Comment by Duneday** [comment]
This seems in line with what he and I both put forward. Seems solid.

**Comment by bpmcpherson** [comment]
As a footnote, I think it would be a good idea to re-audit the races following these changes. It would be worth keeping the information for future use and balancing.

**Comment by Nmmoriarty** [comment]
I think the choice of an extra proficiency would be good.  Plus, IIRC, renegade can apply to intimidates, and Batarian culture seems pretty renegade.
