### ISSUE TITLE
Race - Quarian Thinktank

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#245]
Pulling from #236

Via Duneday:
>Quarians are pretty solid, I would argue that maybe their Attribute bonuses could be tweaked. Charisma and Wisdom don't seem particularly "Quarian." In fact their major enemy (Geth) were born from a lack of both. That said Intelligence and dexterity are both good options as they are obviously intelligent and dexterity is a necessity to practiced engineers.

Via Duneday via damuttley:
>After posting a friend brought up a good point about Quarians and im going to quote him here, "they are highly isolationist when not on their pilgrimage Very few outsiders are allowed access into the fleet ships you only see the young ones out to prove themselves and bring something back to benefit their ppl so I think a similar stat curve to salarians fits them better +2 int, +1 dex or flip those"

**Comment by queryluke** [comment]
One change I'd like to make is clarifying the Hermetic Suit breach with exhaustion: "For each hour in which you have a breach in your suit, suffer one level of exhaustion. For each hour you spend outside of your suit if not in a compatible environment, suffer 3 levels of exhaustion."

**Comment by queryluke** [comment]
Also I think cybernetic enhancement should allow a 4m speed boost, instead of 2m. I'm not sure 2m is attractive enough to take over something like keen senses.

**Comment by Duneday** [comment]
Im not sure if speed is attractive at all really. Quarians will tend towards ranged combat or tech powers with the only real viable alternative being a melee operative.

**Comment by queryluke** [comment]
RE the ability boosts:

+CON seems out because of their fragile immune systems.
+CHA has been stated should be out. (note on this below) 
+WIS has been state should be out, which I tend to agree. As a race are they more attuned to the world or have more intuition?

This leaves only int, dex, and str. Of which, I'd agree, dex and int fit best.

Though if we switch to +2 int, +1 dex, I'd prefer to rework the Salarian scores. +2 int, +1 wis, maybe? Or possibly give Salarians three +1's: wis, int, dex.

Another option could be +2 int, +1 cha. I would argue that just because a culture is isolationist, doesn't me they can't have charisma. I originally gave them the +1 CHA based on Tali's quest is ME2 when Shepard visits the migrant fleet. There were quite a few commanding and charming personalities on board. In Tali's trial, the public outcry had an effect on the verdict. I didn't read this as a fluke, and it made me think that the race valued rhetoric, which takes a certain amount of charisma. But would this charisma transfer to other races? Perhaps this was the argument against charisma.

**Comment by bpmcpherson** [comment]
I do have to say that Wisdom can play a part in how the Quarians have an uncanny knack of survival. Likewise, Charisma is more for their community-minded civilization. While it may be as @queryluke stated in that it is limited to their own species and the Flotilla, they generally think as a whole rather as an individual. 

Finally, another surprising fact to bring up is that, despite their immune system issues, they're stated to be surprisingly hardy a species. Granted, the reason why is unknown, but it's another consideration to keep in mind.

> According to Grunt, quarians are physically tougher than humans, asari and salarians, but not as tough as turians. This could be due to their environmental suits, or due to strictly biological factors, or in reference to their cybernetic augmentations.

**Comment by TheMarmotKing** [comment]
I'm thinking salarians undoubtedly deserve the dex bonus.  And while Wis might not be the perfect choice (and breaks with the E5 tradition of one physical and one mental state bonus) it's the best option unless we get real creative.

**Comment by Nmmoriarty** [comment]
I think a minor +1 CON bonus might be viable, given what @bpmcpherson said about Quarians possibly being tough.

**Comment by Nmmoriarty** [comment]
I like it.

Though this seems like a good place to bring this up: what constitutes an unprotected critical hit?  The language isn't clear.

**Comment by bpmcpherson** [comment]
I, too, like the changes.

**Comment by queryluke** [comment]
@Nmmoriarty, right now I have "Unprotected" as a special condition meaning "no shields or barrier ticks"
