### ISSUE TITLE
Race - Turian Thinktank

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#246]
Pulling from #236 

Via Duneday:
>Turians are pretty much fine. Maybe add a perception proficiency for their eyesight to offset the lack of choice that human provides.

**Comment by bpmcpherson** [comment]
Maybe they could have a resistance to Radiant damage, as the thulium in their skin gives them protection against solar radiation? 

The perception proficiency is certainly a useful benefit.

**Comment by Duneday** [comment]
Both good options, they don't need too much, just a little something to bring them in line with the versatility of humans.

**Comment by TheMarmotKing** [comment]
Maybe a extra weapon proficiency? They are known for pretty universal military training and service.

**Comment by Nmmoriarty** [comment]
...Does anything actually do radiant damage in this system?

**Comment by Nmmoriarty** [comment]
Yeah, getting resistance to damage from literally just one weapon seems a little paltry.

**Comment by queryluke** [comment]
All the plasma guns should do radiant. Or at least that's something that I added a while back.

**Comment by bpmcpherson** [comment]
So, given that there are more instances of radiant damage in the system (environmental, a heavy weapon, energy weapons), has the consensus that Turians gain a resistance to radiant damage improved or should we look to other avenues?

**Comment by Duneday** [comment]
Well my original proposition was perception proficiency based off this quote "Their forward-facing alert eyes give the impression that they possess outstanding eyesight," but I also followed up that either that or the Radiant resistance were good options. So there are at least two avenues we could consider.

**Comment by bpmcpherson** [comment]
Either is fine. I just didn't know if a favored trait would be preferred over another.

**Comment by queryluke** [comment]
### Proposal

* __Thulium Skin__: Resistance to radiant damage and any diseases that would be caused by radiation. 

#### Thoughts
There are a few other races that already offer the perception proficiency, and not many races that offer damage resistances. Radiant damage is playing a larger roll in the bestiary. Any "pulse" weapons deal radiant damage, and pretty much every Geth uses a pulse weapon, but other forces do as well. So it's not a terrible choice.
