### ISSUE TITLE
Suggestion: Vanguard Weapon Proficiencies

### ISSUE THREAD

**Issue by BLUEmusta** [queryluke/masseffect-5e#248]
Currently, Vanguards get proficiency with Heavy Pistols, Shotguns, and a choice between Melee and SMGs.

Although Vanguards have three class features that revolve around melee attacks (Brutal Critical, Retaliation, Zero-Sum), they have to choose Melee as one of their starting weapon proficiencies at creation. This has the effect of providing only an illusion of choice rather than any actual choice -- if you don't choose Melee over SMGs, a significant portion of the class's unique flair suddenly becomes suboptimal.

The issue gets compounded when considering that the subclass features of the Battle Master and Shock Trooper revolve almost entirely around boosting melee attacks in one way or another.

To remedy this issue, I propose that Vanguards instead be given proficiency in Heavy Pistols, Melee, and a choice between Shotguns and SMGs.

**Comment by queryluke** [comment]
My only counter would be that shotguns (most of which have hip-fire) are basically melee weapons. I know this doesn't benefit the class features (Brutal Critical, Retaliation, Zero-Sum), but melee attacks don't require proficiency to make the attack. So, for Zero-Sum, the proficiency bonus to hit is inconsequential. I was thinking Shotgun Vanguards would rush into combat, fire a few shots, and be able to use melee attacks as reactionary and/or when they need to reload. I think this was also spurned by the close association Vanguards have always had with shotguns

All that being said, you've still got a good point. I'm somewhat leaning towards giving them 3 weapon proficiencies (HP, Melee, Shotgun), but no choice. With SMGs being of shorter range, I don't think this hurts Nemesis vanguards terribly, but it may.

I'm interested to hear what others think.

**Comment by queryluke** [comment]
Yeah, I don't think there needs to be too much discussion over this. As @BLUEmusta says the rules favor Melee for Vanguards. I feel in instances where a Vanguard would want to push for Melee, Shotguns, and SMGs, they can work that out with their GM.
