### ISSUE TITLE
Weapon Nerf?

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#249]
This comes from the theoretical output that @Nmmoriarty put together in #238 but to be honest, it's been a hidden problem since the onset. FYI - I'm also only speaking of ranged, non-heavy weapons.

The rest of the game attempts to match 5th edition totals: Monsters, HP, Biotic/Tech power damage. The clear outlier are weapons. Highest dmg weapon I can find in my books is in the DMG, Antimatter Rifle at 6d8 (27), but I would consider this an outlier. Here are the numbers I've run with all ME5e weapons vs All D&D 5e weapons:

#### 5th edition
_EXCLUDING the Antimatter rifle with 6d8, and blowgun with 1 damage, but INCLUDING all the +1, +2, +3 weapons_
Average Damage: ~6.1
Median: ~6.5
Spread: 11 (Low 2.5, High 13.5)

#### ME5e
_excluding ANY mods_
Average Damage: ~9
Median: ~7.5
Spread: 23.5 (low 2.5, high 26)

I even took this out to 5 round/10 round analysis, assuming Rapid Reload didn't exist and when heat ran out the player would be forced to spend a round reloading.

##### 5 round
Avg: 8
Median: 7.5
Spread: 13

##### 10 round
Avg: 7.5
Median: 7
Spread 11

So, at best, we're looking at a ~15-20% increase in average damage output from weapons. And that's not including any of the weapon mods OR armor mods.

Shields, given a max level shield mod of 30 and a full regen at least twice in combat,  would give an additional 90 hp on hp levels that range from 150 to 220. That's a 40% - 60% increase. But this is a best case scenario. It also suggests that survival at higher levels requires 1) max level shield mods and 2) taking the action to allow shields to regen in combat. This also doesn't factor in the lack of healing spells.

Additionally, I've been scaling the monsters based on the PHB and factoring in shields into recommended HP, which means they're at least 15-20% under powered in HP and 40-60% under powered in attack damage.

I'm not sure this is a sustainable discrepancy. So...

#### Remove weapon and armor mods & rapid reload
I don't like this. They add flavor and customization. In this change, we'd be relying on weapons to be the primary source of +X 'magical items'. Maybe shields can be dropped? But this is only 1/2 the problem and doesn't factor in the lack of healing spells (which is mainly why shields are there).

#### Buff everything
All damaging attacks by 15-20% (biotics, tech, melee, grenades, monsters). This also seems like a nightmare. I could achieve it easily programmatically, but it makes it very difficult for others to contribute stat blocks, spells, and pretty much anything that might fall back on the DMG's workshop section.

#### Reduce OP power synergy
This feels like a Sisyphean task. As powers are added and features adjusted, it's going to take a ton of time and effort to figure out if things might be broken. Maybe that's just how TRPGs roll...

#### Nerf weapons
This potentially solve the other problem of melee being slightly under powered.

##### Option 1
Get rid of RoF and scale weapons between 1d4 and 3d8. Effectively will keep everything bound to 5th edition totals. This has the advantage of not having to justify RoF for weapons. The Black Widow is really a 1 RoF, but I had to scale it up to 4 because damage is linked to RoF. Overall, it simplifies the system, and I think the only power that does anything to increase RoF is Turbocharge (which needs a nerf anyway).

##### Option 2
Keep RoF but keep weapons bound to 1d4 - 4d6. 4d6 has a barely higher avg damage than 3d8. So this would allow some weapons to reach that 4RoF pinnacle. But would require much more care and balance when implementing the refactor. And it still make RoF confusing for something like an SMG with a three-round burst, but should only be doing 2d4 damage. This might require dipping into 1 damage weapons (like the blowgun), and I'm not a big fan of that.

I'm open to any and all feedback on this one. It's going to require a major change no matter what.

**Comment by Nmmoriarty** [comment]
Another thing to consider is the presence of damage mitigation that is built into the system.  Shields, Barrier, Tech armor all add a level of damage mitigation that simply isn't present in DnD, and healing items and "magic" are more plentiful here.  While normal DR is essentially only available with the Heavy Armor Mastery feat, it is still present.

As for damage dice, it is important to remember that damage values are abstractions of damage.  Even in DnD, while it expresses combat with a single mechanical action that results in a single mechanical value, in the fiction of the game you are often making more than one swing, even if your total number of "attacks" that can find purchase is one.  I wouldn't worry about matching three round burst weapons with three damage dice -- just go for what fits the damage profile of the weapon you're making.

Also, I didn't mean to scare you with making the Blackest Widower!  It is just a thought experiment to review and see the most overpowered thing I could possibly build to test a system.

**Comment by SrShdw** [comment]
The "Damage Mitigation" you're talking about is like 1d8 generally. Nothing meaningful. 

The reason "future weapons" in the DMG do more damage is because they are being compared to a simple bronze-age sword that does 1d6. When the antimatter rifle becomes the standard of your campaign, it's assumed the armor is also scaled up meaning that antimatter rifle is now your greatsword at best, doing 2d6 damage. 

Combat in 5e is already "Fast and Brutal" most combat scenarios (aside from very large ones) only last 3-4 rounds. I think weapon damage in this conversion should be based off the base weapons in 5e.

**Comment by Duneday** [comment]
I tend to lean towards getting rid of RoF and going more for weapon profiles as well. I will say to Shadow's point that Crits should probably be kept as they are. Crits are supposed to be satisfying and potentially do a significant amount of damage beyond what a normal hit would. That said I do not like how easy it is to crit and I believe it is also the root problem discussed in #238. I believe a crit range shouldn't exceed 19-20. It creates situations like that ridiculous soldier and cheapens class features like the dropshot on Infiltrator.

**Comment by SrShdw** [comment]
Certain weapons could maybe give a bonus to hit or to damage. It might interfere with some mods, but that could perhaps allow you to use different mods on different weapons, and static bonuses to damage wouldn't be an increase to critical hits damage like additional dice would be.

**Comment by TheMarmotKing** [comment]
That leads to another interesting question, will certain guns be like magic items with +1, +2, +3, ect and other abilities, or will that roll fall entirely to gun and armor mods?

**Comment by bpmcpherson** [comment]
@SrShdw Just to clarify, what did you mean by this:

> The "Damage Mitigation" you're talking about is like 1d8 generally. Nothing meaningful.

Just wanted to know where the 1d8 came from.

**Comment by bpmcpherson** [comment]
@SrShdw While the 1d8 is simply the basic barrier, shields, resistances, and other abilities also have to be considered. 

After all, biotics have access to powerful defensive options with Biotic Sphere and Biotic Wall. Tech has Defense Matrix, Combat with Hex Shield that all become accessible as the weapon damage begins to climb. Not to mention the number of powers that can incapacitate enemies. 

To me, this is a problem which has to be considered within the full scope of the system since all of the different combat options need to be taken into account.

**Comment by SrShdw** [comment]
Base 5e has MANY powerful defensive options as well, and martial classes are still the highest-damaging ones in that too. Just because these defensive options exist does not mean that they should be able to be torn through like tissue paper, especially because they are limited resources for casters whereas martial-focused people can basically shoot or swing all day.

**Comment by queryluke** [comment]
I've put together a spreadsheet with the proposed weapon damages. 

https://docs.google.com/spreadsheets/d/1ZSLqul5LmJVMB0y-S6zqQNpbLx2VJIggpO1RTeMVj2Y/edit?usp=sharing

It doesn't have the full stats. Just Rarity, Name, Type, Damage, Average (damage), Tags (properties), Special Abilities, and notes which indicate why a weapon is different. Keep in mind that any weapon with double-tap has the potential to do twice the amount of damage.

You should be able to sort and filter as needed.

**Comment by queryluke** [comment]
I haven't received any feedback on why this would completely ruin everything, so I'm going to go ahead an close this discussion and move forward with the change, as it will entail quite a bit of work on the back end.

**Comment by queryluke** [comment]
If anyone cares to look, [here is an analysis of the new system](https://docs.google.com/spreadsheets/d/e/2PACX-1vSq70x_GZuDKcELgX8k_7Hd6nLGu3DoIEdDwP-YEGjUU-ghGc7ot_Q7140FZwGbEalHgzPwVm4BN8y_/pubhtml?gid=332103674&single=true)

Overall I'm very pleased with the spread.

* Assault rifles vary wildly, but are generally average in all stats.
* Shotguns and Sniper Rifles have high burst damage but drop off significantly due to reloading. But they always have a slightly higher damage than other weapons.
* SMGs have lower drop off over combat rounds, and deal above-average damage, but are limited by their range.
* Heavy Pistols seem weak, but note the "w/ Double Tap" chart brings them much more in-line with other weapons. Plus, they're one-handed so there is potential to dual-wield
* Melee also _seem_ weak, but the charts don't factor in additional damage (from bonuses) and they can be dual-wielded as well.

**Comment by TheMarmotKing** [comment]
Love the visual representation, I think this really does a good job of balancing out weapons and making them deal appropriate amounts of damage
