### ISSUE TITLE
Include Cheat Sheet on website

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#254]
[Link](https://docs.google.com/document/d/19MV6hH00fEI-eoxU3zueDa2fKcCvp-g5jzsUwqkNSyU/edit?usp=sharing)

- In the phb intro
- In the printables

**Comment by bpmcpherson** [comment]
Just a reminder of things to include once they are hammered out:

- Rapid Reload (and how)
- Mods
- Shields and Recharge
- Tech Powers
- Combat Powers
- Heavy Weapons
- Other miscellaneous rules I cannot recall of the top of my head.
