### ISSUE TITLE
Google Sheets Character Sheet

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#255]
If anyone wants to try and tackle this, you can assign yourself to the issue.

It may be possible to convert an existing D&D sheet. Here is one I've used in the past

https://docs.google.com/spreadsheets/d/1qw3DMBK4OgF0jai8GDRtKKXZ8oZmzwwO8phXRD5nC1k/edit#gid=0

**Comment by bpmcpherson** [comment]
Already on it.

**Comment by bpmcpherson** [comment]
Still a work-in-progress, but it's taking shape. 

https://docs.google.com/spreadsheets/d/1P3JC8d_v5xQPcBI1A8s8XyjNRgORZ5YY3YrVCvY_GZI/edit?usp=sharing

**Comment by queryluke** [comment]
It's looking amazing! Great work! We might even be able to hack that spell list to pull from the me data files. I'll make a note about looking into that.

**Comment by bpmcpherson** [comment]
Aside from making room for the new elements of the game (the combat area is going to be a bit of a pain to edit), one thing I'm really looking to trying to do is automatically include data based on selected race/class. 

I have a small example of it working when you select race, as it will automatically set the size of the character (you only notice it on the Volus, as they are small). Those tables of your might be handy in this regard and, if aligned properly, could make maintenance a breeze.

**Comment by Swampson** [comment]
Just want to chime in quickly to second what @queryluke said - it looks amazing! I want all my RPG character sheets to look like this now.

**Comment by bpmcpherson** [comment]
Thank you, both! As I'm developing this, please let me know if there are things missing or could be added. I will also profess that I'm not a designer, so I am trying to prioritize function over form.

**Comment by queryluke** [comment]
I will always support function over form!

**Comment by bpmcpherson** [comment]
I can't guarantee a figure, but I do want to have a section to easily handle armor and weapons, along with mods.

**Comment by bpmcpherson** [comment]
Before I go too much further into development, I wanted to go page-by-page and get feedback on what could be added or changed. The pages which are basically done are the Biotics, Tech, and Combat Powers pages and the Front page. 

With regards to the Front Page, I wanted to include a more thorough armor section, but as with any excel sheet, the more sections I add, the more it messes with the entire row and causes issues. 

So on that, I would love to get what criticisms anyone may have so I can address them now before moving on. Thanks!

**Comment by queryluke** [comment]
@bpmcpherson I started playing around with it. All in all, I think this is still freaking fantastic.

I think the tech/biotic/combat pages are perfect the way they are.

For the front page, I took a stab an a more thorough armor section. I think the main point is to break out the armor body slots and add a place to notate benefits. Here is the list of changes I made:
* Notating AC isn't required, because that's based on what you're wearing (I wrote a rather long formula to do this).
* + Shields only happens on the chest piece (or will in the next release)
* Added place for + regen
* Any other benefits can be listed in the benefits section
* Any +AC from mods can be put under the final AC total in the Mods cell

I don't think it's necessary to have a specific place for regen (i.e., next to the current/max shields), cause the total is right there on the armor.

Mine doesn't track disadvantage, but we could add it back if it's necessary and squish the additional benefits.

The only minor addition to the front page I could think of would be a place for weapon weight. But this is more for the variant rule, and could be handled on the back where all the other weights are.

https://docs.google.com/spreadsheets/d/1dG1xmJTn346f0J0pVaP09LsWUbct9QYdW4qTV_7wR3g/edit?usp=sharing

**Comment by bpmcpherson** [comment]
I like how you handled the armor. Could not have done it better, myself. 

I don't know what other combat statistic I could add aside from Tech Points (but that can be on the tech power page). The weapons section is another thing to tackle, as I didn't know if/how the heat system was going to evolve over the course of the various changes.

**Comment by bpmcpherson** [comment]
I've made some more adjustments to the sheet, so let me know your thoughts.

Additionally, a goal of mine is to automate much of the sheet. For instance, race selection will refer to a table on a hidden sheet which will set the base attribute values, set the base speed, etc. The problem I'm having is that Humans and Unshackled AI, which have the variable attribute. I don't know how to handle those (or any future) instances of that.

**Comment by Swampson** [comment]
Hey, I was just creating a character with the sheet and noticed a bug with the ability scores. The formula for the ability score modifier is "=ROUNDDOWN((Str+StrScore)/2)-5"

However, adding "StrScore" is already added to "Str" so this formula makes the ability modifier higher than it should be. The formula should be: "=ROUNDDOWN((Str)/2)-5"

**Comment by bpmcpherson** [comment]
That's a remnant of updating the ability scores section. I will fix it when I have a moment.

**Comment by Swampson** [comment]
One other thing I found: the "Hit Points" formula should be "=SUM(AS14:AW14)"

**Comment by bpmcpherson** [comment]
Made the corrections you pointed out @Swampson .

**Comment by Swampson** [comment]
Thanks, @bpmcpherson!

**Comment by tioeduardo27** [comment]
Hi @bpmcpherson! I was pre-making some characters for a One-shot campaign I might have soon and found some suggestions and corrections to the sheet available at https://docs.google.com/spreadsheets/d/1P3JC8d_v5xQPcBI1A8s8XyjNRgORZ5YY3YrVCvY_GZI/edit#gid=0

If it's an outdated one, I'm sorry!

- Add a MOD for Initiative so we can assign +5 if we have the Alert feat;
- The formula for Intimidation is counting row 28 and not 27 for the Roll calculation;
- The formula for Passive Perception is counting row 32 (Performance) and not 31 (Perception);
- Change background or font color for Paragon and Renegade skills (maybe light blue and light red);
- Name column in Armor has White font color and can't be seem (change to black);
- Total armor weight is counting column BP instead of BO;

**Comment by bpmcpherson** [comment]
I definitely need to get back to working on this. It's been too long. 

@tioeduardo27 , those are some good ideas that I will look to incorporate.

**Comment by queryluke** [comment]
@bpmcpherson 

here is a newer formula for the AC calc
```
=10+(IF(COUNTIF(AM21:AO23,"=H")>0,0,IF(COUNTIF(AM21:AO23,"=M")>0,IF(J10>2,2,J10),J10)))+IF(AM21 = "H",3,IF(AM21 = "M", 2, IF(AM21 = "L",1,0)))+IF(AM22 = "H",2,IF(AM22 = "M", 1,0))+IF(AM23 = "H",2,IF(AM23 = "M", 1,0))
```

**Comment by bpmcpherson** [comment]
Cool. Sorry that I haven't been able to work on it like I had planned. Something I wanted to ask was how much automation do you want incorporated? For instance, I had planned on selections such a race or class to be able to make assumptions (see HP for the class example). However, if we want to keep the automation down to a minimum to keep it easier to maintain (and since the game is still being developed, everything is up in the air), I would understand that. 

Beyond that concern and what changes are being discussed with regards to spells, I think the Front and Back are generally "done". Again, the concern is first the topic of automation.

**Comment by GameMasterPo** [comment]
A a friend made a character sheet on Google spreadsheets here it is https://docs.google.com/spreadsheets/d/1r-JCa_rqmKSp7-UKf1EP67w6Dl_Pm_JEdaZJMS-R22Y/edit?usp=drivesdk

**Comment by queryluke** [comment]
Thanks @GameMasterPo !!! I've added your link to the site update in #382 

Any new additions/wants/needs to either spreadsheet can have new issues opened.
