### ISSUE TITLE
Armor vs Weapon Mods: consider dropping one

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#256]
With the addition of weapon mods, players have the potential to have +6 to attack and damage rolls. 5th edition seems to be bound to a +4 for legendary level items. So I feel we either need to limit the power of both, or drop 1.

While I enjoy a good crafting system, I wouldn't call the armor mod rules "crafting" since we're really just exchanging money and not collecting materials.

So my first question is: Is the armor modding system worth it? Is anyone planning to use it?

The alternative I'm envisioning would keep armor entirely "Mix& Match". There would be more armor pieces of each type, as I would bring over most of the armor mods and create pieces from them. Armor pieces could not be upgraded. I feel like the mix & match would provide enough choices and customization options without all the complex armor crafting rules.

The weapon mod system would be kept as it is (there will be changes to the mods themselves, but the rules behind them can remain the same). Basically, for a cost, a weapon can be upgraded with a mod. It's a permanent upgrade.

**Comment by bpmcpherson** [comment]
I like both systems and I was planning on using both systems in my game (whenever that gets running), as they reflect the systems in the Mass Effect games. Limiting the power might work, especially if you let the bonuses stack. Perhaps something to look at is limiting armor mods in their use to a particular placement. 

For instance, Microservos in the arms could grant a bonus to melee attack and damage, while the Microservos in the Legs could do something else entirely (improvements to running/jumping, etc). It would help to prevent an easy stacking of attack power.

Another idea is to make the bonuses in armor not stack for multiple instances of an upgrade. Rather, the highest instance is used and everything else ignored (the +2 to attack in my arms armor beats my helmet's +1 to attack: use the +2).

**Comment by queryluke** [comment]
Cool, I wanted to throw it out there just in case there was some reservations about using it. I think, now that weapon mods exist, I just need to audit the current armor mods and make sure there aren't any OP combinations.

**Comment by TheMarmotKing** [comment]
I absolutely think both should be used.  Mods are a great replacement for magic items in this system, and armor mods offer abilities and effects not just weapon based.  They also are one of the best(and only) ways to improve Shields passivly, something I think most characters will want to do. I agree that +6 might be a little overkill.  While it's ultimately up to the DM how much access players have to armor mods, with weapon mods around most will probably prefer to use those slots for shields or fun bonuses

**Comment by Nmmoriarty** [comment]
The simplest solution @bpmcpherson already pointed out: just don't let the bonuses stack.  It limits you in some sense, but it also opens you up to taking more interesting and niche options for mods instead of just getting a +3 Assault Rifle of Much Dakka.

The problem largely, as I see it, is that weapons don't get a +X quality, they get a Bonus to attack or damage, so someone who wanted to rules lawyer it would technically be correct that they stack, so whatever wording you use if you want to go down that path should explicitly forbid it.

**Comment by TheMarmotKing** [comment]
What about stating you can only apply attack bonuses from one mod source at a time? That simplifies the wording

**Comment by queryluke** [comment]
### Armor mods overlapping with weapon mods
I looked over the current armor mods, and they are pretty diverse. I think I can just remove or change any of the armor mods that provided bonuses to ranged weapon attack or damage rolls.
* VI Amiming
* Weapon Stabilizers
* Focus Modulator

I'll put a note in the rules about creating custom armor mods that ranged weapon attack and damage bonuses should remain on weapon mods.

### Armor mods overlapping with other armor mods
First, make a note that a mod cannot be applied twice to a piece of armor. (I.e., can't apply 2 +2 AC mods into a chest piece)
Here are all the places that the current list of armor mods can be stacked

* Weapon slots (no issue)
* Increased HP, I don't like this mod anyway. I think swapping to the "ignore critical" is a better fit. (note to self to change on armor sets)
* +Melee attack and damage rolls. Change the legs to a +1, giving a max +3 when stacked.
* Resistances (could be taken advantage of but they are very expensive, don't think it currently warrants a change)
* grenade capacity (no issue)
* shield points. I want to change +SP to chest only, since this is where the shield generator lives anyway.
* shield regen (no issue, can only stack to 15 currently, but has a ceiling of the character's sp)
* tech regen die type (no issue, max d12 and only happens on a short rest)
* thermal clip capacity (no issue)
* "jump start shield regen", instead of taking hide or dodge action. (no issue. Only 2, even with 4, I'd be ok because they're taking up slots that would increase shields or regen).
* Autogel, I guess this would let you use 2 charges of medigel...but I don't have a problem with that either.

**Comment by TheMarmotKing** [comment]
I think removing attack bonus from armor mods works, but looking around, doesn't the same problem exist for regular armor sets? If you have the kuwashii visor and the mantis armor, you're up to +4.  Throw in a third level barrel, a decent dex mod and even A low level Prof and you're looking at 13 or higher attack modifiers.  Of course that's pretty expensive but still

**Comment by queryluke** [comment]
@TheMarmotKing Right, I'll need to review and remove those bonuses from Armor sets as well. I should also check that no head mods can stack with body armor.

**Comment by TheMarmotKing** [comment]
Maybe replace some of the attack bonuses with damage or crit enhancements

**Comment by Duneday** [comment]
Im very much in favor of reigning in crit. The system expands crit ranges wayyy too far. IMO Crit ranges shouldnt go beyond 19-20. I posted something like this before, but I forget which discussion of the top of my head :S

**Comment by Nmmoriarty** [comment]
I've got to agree on reigning in Crit creep.  Armor mods should improve your defenses, Weapon mods should improve your weapons.

**Comment by TheMarmotKing** [comment]
Defense and utility.  And I think the visor helmets could be made to give attack or at least improve crits

**Comment by Nmmoriarty** [comment]
Well, yes.  I wonder if a resistance to radiant armor mod could be added?

**Comment by queryluke** [comment]
Closing this as it seems we should not drop either mod types. Will open a new issue with armor mod/set review and proposal.
