### ISSUE TITLE
Legendary Actions on Grunt Generator

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#257]
Feedback pointed out an issue that the grunt generator was failing. There were 2 issues.

1. Anytime a heavy weapon was selected, it bugged (fixed this)
2. Some CRs have damage/round totals that are too high to accommodate the current weapons (I patched this for now, but it still errors occasionally). It also causes higher CRs to have a much more limited range of weapon options, usually resulting in their attacks being the same.

If the weapons are scaled back, this will increase the issue in the generator.

Adding legendary actions would allow for at least 1 more attack per round. Should also include reloading as a legendary action and start tracking reloads on the Stat block.

**Comment by Nmmoriarty** [comment]
Not a feedback, but I think a great April fool's joke would be that it just gives you screenshots and fan art of Grunt all day.
