### ISSUE TITLE
Guidance

### ISSUE THREAD

**Issue by TheMarmotKing** [queryluke/masseffect-5e#261]
I think that if we want guidance to be used at all, it needs to have a higher bonus.  E5 guidance is free as a cantrip, but this guidance costs a tech point, and nobody is going to spend an upgrade point to make that a d6.  I propose we change the roll to a d6, or add your tech modifier, or make the spell not cost tech points to use.  Doing one of these makes it a more attractive option that people will choose over damage dealing and healing options, increasing tech classes supporting ability

**Comment by queryluke** [comment]
Agreed. In fact, this should would more like bardic inspiration. Right now it's somewhere in between bardic inspiration and guidance because it allows the check to be made on saving throws. Should probably just go all in and make it work like bardic inspiration:

Changes:
* bonus action
* 1d6 (1d10 on upgrade)
* lasts 10 min
* ability check, saving throw, or attack roll

**Comment by queryluke** [comment]
So I reduced the changes of this, instead, in the next release, guidance will:

* Remain a d4
* Remain an action
* last 10 minutes
* available to use on ability check, saving throw, attack roll

There are a few reasons what I didn't want to go entirely Bardic Inspiration (BI). First, BI is limited to 5 uses per long rest (if you have a 20 CHA) score. Second, 5th Edition's Guidance requires concentration (no more that one target) and a range of touch. It's also not applicable to attack rolls.

So I tooled this somewhere between bardic inspiration and Guidance. You get to use it on attack rolls, you can cast it at range, you can have it active on multiple targets and you can use it much more often than BI. But, it takes an action and it's not as potent (d4).

**Comment by TheMarmotKing** [comment]
I absolutely love this change.  It makes it worthwhile to spend the tech point in both combat and non combat scenarios! Great compromise!
