### ISSUE TITLE
Sentry Turret

### ISSUE THREAD

**Issue by TheMarmotKing** [queryluke/masseffect-5e#262]
The spell doesn't specify how much AC the turret has

**Comment by queryluke** [comment]
Sentry turret will have a stack block in the bestiary. But this is a good reminder for me to change the spell text which will be something like: "Spend 5 TP to summon a sentry turret"

**Comment by bpmcpherson** [comment]
I know it's closed, but this could tie into the changes I suggested in #253 regarding the combat turret (or even including the shielded turret like the Geth units in ME3) where they can be variant stat blocks or something.

**Comment by queryluke** [comment]
@bpmcpherson I'm very open to creating different turret stat blocks and letting this power choose which turret you want to cast or, if that's a bit to over powered, making different tech spells that can summon different turret types.
