### ISSUE TITLE
Sentinel Improvements

### ISSUE THREAD

**Issue by Duneday** [queryluke/masseffect-5e#263]
Via queryluke "@Duneday I'm sorry you're not feeling well! I also hope our disagreement doesn't dissuade you from contributing more feedback. You've provided a lot of thorough and well-thought-out criticism (here and everywhere else). I hope you continue to challenge and force me to make these tough decisions. With more playtesting and number crunching, I'm sure we'll find a middle-ground (or we may find out that I'm completely wrong!). I don't enjoy being the arbiter in these situations, but, currently, I want to lean on the playtesting and analyses I've done so far.

That said, I do agree a minor boost in spell slots and tech points could go a long way. Without considering class features, it would, at the very least, make a Sentinels better than a multi-classed Adept/Engineer. I've added to my todo list above to incorporate this change.

[edit]
FYI - I'm going to close this discussion so I can begin folding the changes into my workflow. But please feel free to open a new discussion about sentinel improvements, and/or, edit you comment above."

A number of my feelings are already posted in #203, but I would like to keep an open thread on how to improve the balance between Sentinels and other classes as per queryluke's suggestion. Particularly gaining community feedback on the stat split issue, but also looking into other possible improvements. For example the current range of buffs for the Sentinel in the guardian tree are about 2-4m as per the Paladin class they are based off. However, Mass effect is a much more ranged based game and players are encouraged to scatter for cover rather than bundle up. I believe this should be reflected as it is with the help action under the Mastermind tree. Perhaps picking an ally or 2 within 10m to grant the bonuses to?
Heres a list of issues I see off the top of my head, but feel free to list your own concerns or solutions.
- Aura Ranges
Stat split for casting modifiers
Unclear wording of "Defensive" under the Guardian tree
Improving Spell selection/TP pool and expenditure
Reworking Tech aura improvement to include all allies (based off the suggested change of selecting allies)

@queryluke I appreciate the concern, on a personal note the pain is more localized so I can only assume its healing and ill be able to sleep soon x.x. I also lean towards play testing as at the end of the day that is what matters most. I look forward to seeing what you uncover.

**Comment by bpmcpherson** [comment]
Defensive is simply the basic Tech Armor power. It's given the name so that when you turn on the Tech Armor ability want wanted it as its usual power, you can declare "I'm using the Defensive Package".

**Comment by Nmmoriarty** [comment]
Honestly, the Sentinel is already quite strong -- it shouldn't cast as well as a dedicated Biotic nor Engineer, it has some quite good bonuses and can go multiple ways satisfying ways.  

The only thing I can think of that could use a minor buff is Tech Armor.  It doesn't scale well as you hit mid-game.  Sure, you can burn all your TP in keeping it active, but with mid-level damage that extra 4.5 temporary shield points per tech point can be burned through rather quickly.  I think that treating it much like the Wizard (Abjurist)'s Ward subclass ability would be easier to scale and manage on top of being stronger, with the ability to dump Tech Points to boost it (instead of casting abjuration spells) with something that also scales/is more reliable than a d8.  

Does Tech Armor end if the TSPs are lost?  If so, then Tech Armor needs significant improvement.  Can they invest TP to get more TSP if "pool" is empty?

**Comment by bpmcpherson** [comment]
I'm of the opinion that the only buff tech armor needs is in regards to the range of the auras, as was mentioned before. I agree that the range should probably be limited to 10m.

As an aside, can multiple tech armor auras from multiple sources be used at once?

**Comment by bpmcpherson** [comment]
Just a few thoughts I had on the matter that I pondered before bed. I'll just list them as I recall them.

- The tech powers function more like a Monk's Ki abilities, albeit with more spell-like effects. 

- With regards to the casting, something to keep in the back of your mind is that the breadth of effects in all of the powers in mass effect is widely smaller than what you will see in 5e. Mind control is very minimal, for instance. Casting in Mass Effect generally serves more of a controlling role with Biotics (Pull, Push, Singularity, Lift) and even then, if an enemy has shields, 3/4 of those I just listed don't work until the shield has been taken down.

> Casting for Sentinels is a significant part of how they try to be relevant, so it should also be heavily scrutinized to make sure it is a worthy inclusion to the class to help them remain relevant (although not to the point where they step on the toes of engineers or Adepts of course).

Perhaps that's one perspective, but the key in the series has always been that they can simply do everything. Below is how they have been described in the games:

### Mass Effect
> The Sentinel is able to combine tech and biotics to manipulate the environment, disable and track enemies, or defend the party. Gameplay focus is on protecting the party using kinetic barriers and healing it with advanced medical training. Kaidan Alenko is an L2 Sentinel.

>Sentinels are support-focused characters, possessing biotic and tech abilities mostly focused around controlling the battlefield and keeping the squad alive. They receive no specialized weapons or armor training, but are proficient with a pistol. The Sentinel is surprisingly durable, with access to many of the shield-increasing talents, along with the Barrier biotic ability.

### Mass Effect 2/3
>Sentinels are unique, bringing both tech and biotic abilities to the battlefield. While they lack the focus of adepts and engineers, they are versatile and can handle any situation. Sentinels are equipped with the most advanced ablation armor system to keep themselves safe. If overloaded, the system will stun all enemies within a short distance. This advanced shield causes the sentinel to be like a "Juggernaut" so to speak, making it less necessary to take cover, and rushing your enemies much more productive.

If you need some tech, they have it. Biotics? They have that too. They still use guns like every other character and will rely on that for the most part for their damage and use their powers to buff/debuff. The introduction of priming and detonating gave them another means of supporting with powers, but it was still in the same vein of "there's a primed target, I can fill the role of detonator".

> I know Sentinels tankiness is really nice, but the reason i look at things to improve is because tankiness only goes so far in being relevant to the team. Look at barabrian for example while raging they also gain damage resistances but it comes with a slew of other benefits (brutal critical, immunity to mind affecting, and others depending on your totem/path).

Sentinels also get other benefits as well, typically tied to their subclass, and don't have the disadvantages of an ability like Rage. Plus, again, the ability to still cast and use abilities like barrier and serve as the same controller/supporter they always do.

I will post more if I remember anything else, but my point was to just throw out information. Another key point is that a straight-up comparison to 5e will only serve so much for balancing, as this game is also introducing its own systems and takes into account an ultimately more limited subset of powers, weapons, etc.

**Comment by bpmcpherson** [comment]
Noted on the rage changes. When I had read it beforehand, I thought I had seen a disadvantage, but on a second read, it was clear I was mistaken. But to clarify, my post and thoughts were to reign in the 5e comparisons to bring attention to the role the Sentinel class as described in the Mass Effect series. 

I wish I could go more toe-to-toe with you regarding 5e mechanics, but I simply lack that experience. I'd have to defer those discussions to someone more experienced. However, I can say that I don't believe there's a system in place for auditing classes. The race audit came from one of the source books for 5e which introduced that system.

**Comment by Duneday** [comment]
Its all good, I tend to use 5E as a metric for balancing so I do reference it a quite a bit. Im pretty sure i grasp a sentinels role in mass effect although on that note I would defer to you if you saw something wrong with my interpretations. 

The class audit was kind of a whimsical thought. It would be pretty difficult to establish a system as classes involve a lot more interactions between features than a race would, and a scale for strength couldnt really be designed unlike a racial. 

[On the note of the disadvantage, you may have read on to the reckless attack that barbarians gain at level 2, I believe, which is a VERY nice ability in and of itself.]

**Comment by queryluke** [comment]
Wanted to chime in that I did boost the spell casting levels of the sentinel in the next release. Though they have no 4th level spells to learn, they get a few 4th level spell slots. Additionally, their TP/maxTP ranges are the same as Infiltrators. So, basically, they're as potent as Infiltrators (on the tech side) and Vanguards (on the biotic side).
