### ISSUE TITLE
"Mending" Tech Power

### ISSUE THREAD

**Issue by bpmcpherson** [queryluke/masseffect-5e#265]
In looking through some of the 5e spells, I happened across [Mending](https://open5e.com/spellcasting/spells_a-z/m/mending.html). It immediately reminded me of one of the opening scenes where Ryder repairs their cracked helmet faceplate with their omni-tool. The wording of the power is pretty fitting, as it can repair small things, but nothing extreme (ex. the entire face plate being blown out).

The issue, however, is that the power itself is so basic that it would be wasteful to pick as one of the limited choices of the tech powers and there aren't cantrip equivalents with tech powers, so that's not an alternative either. That being said, I wanted to see if anyone had suggestions on how to implement this.

**Comment by queryluke** [comment]
Just off the top of my head, this could be covered by toolkits, which, I hope, will be introduced when backgrounds are added.

**Comment by bpmcpherson** [comment]
That's a good point! I honestly had forgotten about toolkits, but that could be an avenue for a solution.

**Comment by TheMarmotKing** [comment]
What if toolkits were rebranded as a omnitool program or something similar? That could be used for alot of similar, cantrip like spells

**Comment by bpmcpherson** [comment]
It would be fitting. "Omni-tool Kits" has a nice ring to it.

Plus, they serve as all sorts of items in the field (ex. computers, scanners, weapons, fabricators).

**Comment by TheMarmotKing** [comment]
This could also be a good way to impliment tech (or even combat) ability spell scrolls.  The omnitool would be a great way to add interesting consumable options.  Of course there might need to be some limit on space (say you can hold 3 of these programs or kits or a tech spell in a basic omnitool, then upgrade for more space later)

**Comment by bpmcpherson** [comment]
So the Hacking Tools from Modern Magic could be easily applied as an Omni-Tool Kit:

> Hacking Tools. This kit contains the hardware and software necessary to allow access into most computer systems and electronic devices. Proficiency with hacking tools lets you add your proficiency bonus to any Intelligence checks you make to connect to or make use of a computer system or electronic device. The kit fits snugly in a backpack or toolbox.
