### ISSUE TITLE
Sample Characters/Starter Kit

### ISSUE THREAD

**Issue by bpmcpherson** [queryluke/masseffect-5e#270]
Something which I think would be helpful once the mechanics stabilize is the development of sample characters from the different races to help those starting out have a baseline (or a quick-start game for players experimenting with the system).

**Comment by queryluke** [comment]
I very much agree. We can use this issue to generate ideas for the "iconic" starter kits.

**Comment by queryluke** [comment]
Level 1. But with instructions on how to level to ~5. I think Ben's idea was something like the [starter set](https://media.wizards.com/downloads/dnd/StarterSet_Characters.pdf) from 5e.

On whatever page we have the kits, we can also include some sample party make-ups. Good idea!

**Comment by bpmcpherson** [comment]
Precisely. Just something for new players to be able to pick up and play.
