### ISSUE TITLE
Open Discussion on Advancement Options

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#272]
Overload
>You spend tech points to unleash an electrostatic discharge at a creature or object within range. Three bolts then leap from that target to as many as three other targets, each of which must be within 6m of the first target. A target can be a creature or an object and can be targeted by only one of the bolts. A target becomes {primed-lightning} until the end of its next turn and must make a Dexterity saving throw. The target takes Xd4 lightning damage on a failed save, or half as much on a successful one where X is the number of tech points you spent.

Quad leap advancement
>Overload can leap to five additional targets, but deals 1d4 damage.

Current rule would imply that casting for 2 TP would result in only 1d4 damage. I don't think this was my intent. Also, "quad" means 4 not 5, and it's five additional (meaning 6). So, yeah, overall, I think I just need to come up with a better advancement option.

**Comment by TheMarmotKing** [comment]
Maybe it's a good time to start up a thread for ability improvement ideas?  It's difficult to make upgrades that are worth more than a new ability.  But I think the potential is there for some really cool and fun upgrades

**Comment by bpmcpherson** [comment]
That is an angle worth exploring. In the case of tech and biotic powers, the pool of use is limited, so more doesn't always equal more uses. However, Combat Powers have built-in limits, so getting another power presents more power usage overall.

**Comment by Duneday** [comment]
Personally im for an ability improvement thread. In my opinion quite a few could use a boost to make them more attractive than just blasting away with guns. Same with primes/detonated to be honest, the only one i see being useful is force...maybe electric, but its also really weak IMO.

**Comment by bpmcpherson** [comment]
Probably one simple solution to your concerns with the detonator DCs is to have them scale like powers can. That way, the DCs get higher as the campaign goes. 

Back to the issue at hand, it's worth looking at the classes in all scenarios to see their power gain/advancement.

For instance, Soldiers have 5 instances of Combat Power Gain/Advancement. This can translate to 5 overall powers, 2 advanced powers and 1 unadvanced, or 1 advanced and 3 unadvanced. Soldiers going the route of Havoc gain 5 additional instances, doubling the numbers above. 

Infiltrators have 5 instances of Tech/Combat Power Gain (I'm unsure how to interpret the 2 and 1 in parenthesis, does that mean choose two powers from either category or 2 from one category, or what?). 

Sentinels have 5 instances of Tech gains.

Biotics are another thing, but I'd have to spend more time looking at those gains given spell slots and whatnot.

**Comment by queryluke** [comment]
I changed the title since the discussion has shifted. I simply added the option for increased damage

**Comment by queryluke** [comment]
This discussing has stagnated, so I'm going to close it. 

I think what we need is a spell review, which I'm going to get started.
