### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by MonocledMutineer** [queryluke/masseffect-5e#277]
Hello

I found your nifty little conversion about two weeks ago and got so exited that I set up a game as soon as I was able. We played this past Saturday, with fair success. I really like how smooth Mass Effect runs on the 5E engine, especially with the system that you have put together.

So I'd like to contribute, if I may.

First, be warned; I'm not a tech guy, in any form or function, so my presence here will probably be a bit ... awkward, as I have no clue about technicalities such as flairing posts and anything to do with code.

Second: I am not a professional game designer, though I have been playing around with designing RPGs for some five years now and have some 16, more-or-less completed, games under my belt. I'm also a natural power gamer, seeing ideal combinations and figuring out RPG systems easily, making me a pain in the rear with any system that cares about game balance.

I have a metric ton of feedback, based on the latest update; so would you prefer to have it in a single info-dump, or several seperate posts, such as "Classes", "Races" and "Equipment"? Or even more specific posts such as "Asari", "Pistols" and "Biotic Powers"?

Cheers! The MonocledMutineer

**Comment by bpmcpherson** [comment]
The more the merrier, I say. As for feedback, I'd say post each in its own separate issue ticket so that it can be easier to track and will keep any conversation isolated to its particular problem.

**Comment by queryluke** [comment]
Yes, glad to have you and that the github issue got sorted out!
