### ISSUE TITLE
Hip Fire - remove advantage?

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#279]
In a recent playtest, we rolled a Shogun Soldier. At level 12, with tactical reload, carnage, extra attack 2, and melee specialist they were getting ~4 attacks per turn averaging about 30 damage per turn. No weapon mods.

Anyway, because hip fire _grants_ advantage, it reminded me just how important having advantage on a 
roll can be. But because he was making melee attacks on the same turn, it made me realize, why is it easier to hit a target within melee range with a ranged weapon rather than a melee weapon. I.e., Hip Fire adds an entirely new bonus to melee range combat that is not afforded to melee weapons. Since shotguns already deal more damage, this just seems off to me.

My suggestion would be to remove the advantage portion of Hip Fire, and simply let hip fire weapons not have a disadvantage penalty within melee range. This also opens up the opportunity for more weapons to be hip fire, like SMGs.

**Comment by bpmcpherson** [comment]
I think removing the penalty is plenty a benefit already.

**Comment by Swampson** [comment]
I agree with this as well.

**Comment by Duneday** [comment]
I will third this opinion.

**Comment by Nmmoriarty** [comment]
As long as Shotguns don't have a stupidly long range bracket, it see no issue with this.  It is important that both brackets don't go very far -- otherwise with the Sharpshooter feat shotguns would become stupidly good at long ranges.
