### ISSUE TITLE
Fighting Style Audit

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#282]
In #280, we discussed removing advanced options of fighting styles.

### Brawler
__Weapon Specialty__: melee
Keep basic, remove advanced.

### Gunslinger
I'd like to move this to a feat, which would allow it to have 2 levels. Or, remove it all-together. 

### The Free Hand:
__Weapon Specialty__: none, intended for casters
Keep basic (except adjust the wording, see #275), find another place for the advanced option, such as a feat or class trait.

### Carnage:
__Weapon Specialty__: shotguns
Remove basic & advanced (not a fan of either). 
__Replacement__: When you roll a 1 or 2 on a damage die for an attack you make with a shotgun, you can reroll the die and must use the new roll. _This is a pull from Great Weapon Fighting, which I think is applicable_

### Sniper:
__Weapon Specialty__: sniper rifle
Keep basic, remove advanced. _This has a certain echo of the Duelist fighting style in 5th edition_

### Defense:
__Weapon specialty__: none
Keep basic, remove advanced. _Same as 5th_

### Protection:
__Weapon specialty__: none
Keep basic, remove advanced. _Same as 5th except using Barrier ticks, and can target ranged attacks_

### Close-Quarters Shooter (see #276): 
__Weapon specialty__: any
_Combine basic & advanced to get the 5th edition version_: 

When making a ranged attack while you are within 2m of a hostile creature, you do not have disadvantage on the attack roll. Your ranged attacks ignore half cover and three-quarters cover against targets within 10m of you. You have a +1 bonus to attack rolls on ranged attacks.

### Assault:
__Weapon specialty__: assault rifle
Some options from #215 

1. Increase the Heat of any AR or SMG you have equipped by 2. This bonus is not conferred to others if they use the weapon. Gain a +3 bonus to Rapid Reload checks. If you roll a 1 on a Rapid Reload, you do not fumble the clip, but you still fail the Rapid Reload and cannot reload your weapon as a bonus action.
2. You can make a double tap with an assault riffle or smg, even if the weapon doesn't have the double tap tag.

**Comment by queryluke** [comment]
Augmented from the DMG:

>Burst Fire. A weapon that has the burst fire property can make a normal single-target attack, or it can spray a 4m-cube area within normal range with shots. Each creature in the area must succeed on a DC 15 Dexterity saving throw or take the weapon's normal damage. This action uses 5 heat.

I'd need to make sure the weapons this applies too have enough heat to make this viable.

Bur from this, the Assault Rifle fighting style could be:

When you take the Burst First action, the size of the cube increased to 6m and you add your proficiency bonus to the DC of the saving throw.

**Comment by bpmcpherson** [comment]
I'll look over these more closely when I have a chance. I've been swamped with work, so I haven't had as much time to dedicate to this.

**Comment by queryluke** [comment]
No worries. I'm not in a huge rush on this.
