### ISSUE TITLE
Biotic Cantrips Review

### ISSUE THREAD

**Issue by TheMarmotKing** [queryluke/masseffect-5e#284]
This is part 1 of a review I'm doing for the spell list.  It's going to include suggestions for Advancement options (referred to as AOs), comments on balance, and a few other things.  Since it'll be much easier to comment and notes on a google doc instead of a long comment list, here is the link.  Commenting on there would be a good way to keep everything organized and easy to read.

https://docs.google.com/document/d/1-VURfL8lsOlfBgmZwbQ9slbePCCB3TnQ3aIrNRqmN8o/edit?usp=sharing

**Comment by queryluke** [comment]
So, I really like the discussion happening with Submission Net, so I think it might be better to break out the docs sheet into separate tickets. I've made a spell review template for issues and I'll go ahead and move everything over.

I'd eventually like to go through all of the spells using this process.

**Comment by TheMarmotKing** [comment]
Just so we don't get super bogged down in spell reviews, do we we want to try to finish the revisions for the current spells (biotic cantrips) before moving on to the next batch?

**Comment by queryluke** [comment]
@TheMarmotKing agreed.
