### ISSUE TITLE
Paragon and Renegade gives Advantage or Disadvantage for Charisma Skills

### ISSUE THREAD

**Issue by tioeduardo27** [queryluke/masseffect-5e#286]
For the campaign I'm preparing, I decided to add this homebrew rule:

- Paragon points > Renegade points: Advantage on Performance and Persuasion rolls, disadvantage on Deception and Intimidation rolls;
- Renegade points > Paragon points: Advantage on  Deception and Intimidation rolls, disadvantage on Performance and Persuasion rolls;

This would also change the P/R bonus rule a little, since they would be available (on any Skill check) for any action the character takes, based on situations and most importantly - roleplay.

I think this will discourage players to consider the P/R points as a way to Min/Max and encourage them to match their actions to their characters, and also keep the R/P mechanic importance.

Thoughts?

**Comment by queryluke** [comment]
So if I'm reading this correctly, if I have 50 Paragon and 15 Renegade, I would have advantage on performance and persuasion, and disadvantage on deception and intimidation. Is that correct?

I think this is an interesting approach. But I would consider a few things.

1. A player might want to mix and match the skills that lie on either side of the split (e.g., Deception/Persuasion). This would make it somewhat difficult for them.

2. You mention that the P/R bonus would "be available (on any Skill check) for any action the character takes..." This is my intent in the current rules. The bonus can be applied to any skill or even an attack roll. I once added a renegade bonus when letting a player punch someone they were interrogating. I've also added a paragon roll to an athletics check when a player tried to pull an NPC out of harms way. I feel like the current examples on the site might make this unclear, which is my fault. In reality you can use the P/R bonus anywhere. In my playtesting, I simply tell the player they can add their P or R bonus. But players can ask if they think a bonus applies.

3. The GM awards the P/R points which are based on roleplaying choices the player makes. So, in theory, a player who is "Min/Maxing" their P/R is roleplaying their character really well (either always taking paragon or renegade choices). Players who waffle are going to have a mixed bag of points. IMO, by imposing advantage/disadvantage for unequal scores, you're actually encouraging min/maxing. Or, you're at least encouraging players to pick a path P or R and stick with it. I think that's fine as long as that's your intent.

Either way, I think you should try it out. If it works, great! And definitely let us know how it goes.

**Comment by tioeduardo27** [comment]
Thanks for the input and for the game you're developing!
My "counterpoints":
1. This could be "balanced" by having the player choose 2 skills from those 4 if they have equal Renegade and Paragon points.
2. I don't think your wording in the rules are unclear, I just thought writing it down in my original post as to make it explicit your rules are also valid in my suggestions.
3. I hadn't thought of that and you're totally right. Though maybe my first counterpoint here could fix that. What do you think?

**Comment by queryluke** [comment]
1. I think that's a great idea!
2. I see, your rules are in addition to the current ruleset. That makes more sense.
3. As long as there is some roleplaying/personality style that can justify using Paragon or Renegade for each of the Charisma Skills. Just brain-storming:

Skill | Paragon vs. Renegade
--- | ---
Performance | Classical vs. Rock-in-roll
Persuasion | Inspiring vs. Threatening
Intimidation | Threatens with laws vs. Threatens with pain
Deception | Augments the truth vs Outright lies

Anyway, you suggestion is much clearer. I've been so focused on playtesting combat that I haven't had time to run some non-combat scenarios. But when I do, I'll definitely want to revisit the current P/R rules. So please let us know how it goes in your game.

**Comment by queryluke** [comment]
I've added this idea in the new "Found Codices" section of #382
