### ISSUE TITLE
Salarian: Photographic Memory

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#287]
Current:
You can recall with near-perfect clarity anything you ever seen or read. Choose one of the following skills, you have expertise in it (add double your proficiency bonus): Engineering, Electronics, History, Medicine, or Science.

Proposal:
Whenever you make an Intelligence (Engineering, Electronics, History, or Science) check to recall information, you add double your proficiency bonus to the check, even if you're not normally proficient.

Thoughts:
What I don't like about the current one is that we're equating memory with expertise, which isn't necessarily the case. The proposal focuses on memory. Some situations where this would come in handy would be recalling information about a planet, monster, ship schematic, etc. But it wouldn't give you double proficiency when making an Engineering check to fix something. Again, separating tangible skill from memory.

**Comment by Nmmoriarty** [comment]
Sounds like a good rewording to accomplish what you want to get at.
