### ISSUE TITLE
Spell Review: Submission Net

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#289]
This came from a play tester:

### Current
Spend 2 tech points to shoot a swarm of miniature pylons to a target location within 20m. The pylons form a 4m cylinder at the chosen location, created an electrified net. Creatures within the net cannot cast tech.

To escape, a creature must succeed on a Strength (Athletics) check or must remain trapped in the net. If a creature does break free, it takes 1d6 lightning damage.

If you have a submission net deployed, you can spend XTP to send electric currents through it. Each creature within the net makes a Constitution saving throw. On a failed save, a creature takes Xd6 lightning damage, or half as much on a successful one.

Advanced 1 | Advanced 2
--- | ---
You can electrify the net as a bonus action the first time you cast Submission net. | Increase the DC to break free of the net by 3.

### Problems
* A bit overpowered for 2 TP as it automatically hits. 
* The electric currents don't have an action cost.

### Proposal
Spend 2 tech points to shoot a swarm of miniature pylons to a target location within 20m. The pylons form a 4m cylinder at the chosen location, creating an electrified net. Each creature in the area must make a Dexterity saving throw. On a failed save, the creature is trapped in the net. Trapped creatures cannot cast tech and are considered Restrained.

To escape the next, a creature must succeed on a Strength (Athletics) check against your spell save DC. On each attempt, the creature takes 1d6 lighting damage as it struggles against the electrified field.

On each of your next turns, if you have a submission net deployed, you can use your action to spend XTP to send electric currents through it. Each creature within the net takes Xd6 lightning damage.

**Comment by TheMarmotKing** [comment]
Should creatures have to roll a decent save upon starting their turn in the field or ending their turn there? I think that would make it more effective for area denial since this change needs it.

**Comment by Swampson** [comment]
With regards to the suggestion from @TheMarmotKing, I think your intention is to penalize characters moving through the area of the net after it’s in place? If so, maybe we add “The area of the submission net counts as difficult terrain. A creature that starts or ends its turn in this area must succeed a Strength saving throw against your spell save DC or be Restrained by the net.

**Comment by Swampson** [comment]
@queryluke “To escape the net, a creature must succeed on a Strength (Athletics) check” - this should be a saving throw, I think, not a skill check.

**Comment by queryluke** [comment]
I think we need to take a step back and define what this power actually looks like (without mechanics).

I realize now, the person who sent this in (via email) is imagining some sort of a physical net. My interpretation is that the pylons make an electric wall around the 4m area. Anything within it can't cast tech and entering or exiting the wall takes a dice roll (I think @TheMarmotKing is on the same page because he pointed out that there is nothing to prevent entering the area). @Swampson with the difficult terrain mechanic, I feel like you're imagining that the pylons land _throughout_ the 4m area creating a net of electric tethers. (I drew a picture).

![submission_net](https://user-images.githubusercontent.com/12414786/40234857-4d0f3ea0-5a76-11e8-86f6-c3e95cbb2064.jpg)

So let's first pick which mental image we want. If I'm being honest, I didn't even think about option 2, I'm leaning towards that.

**Comment by Swampson** [comment]
So, I was _also_ imagining a more literal "net" when thinking about this spell - sort of like a high-tech version of a [net gun](https://en.wikipedia.org/wiki/Net_gun). The pylons would land in a random pattern, a la Option 2, but would cast a "net" of electrified current over any targets in the zone, causing the restraint. My thinking with difficult terrain and the saving throw for creatures starting/ending their turns is that by moving through the area of the net you'd risk getting entangled in it.

Given your intention perhaps one thing we could consider is a name change, maybe "Submission Field", "Zone of Submission", or "Queryluke's Minor Plane of Greater Pain" (two of these are not real suggestions).

**Comment by TheMarmotKing** [comment]
Making it a, if you enter the net you have to make the saving throw or something and making it difficult terrain makes it so the if every enemy inside passes the saving throw it isn't a complete waste.  I would also recommend that an AO be the ability to electrocute caught enemies as a bonus action.

**Comment by TheMarmotKing** [comment]
And is this concentration? Or a one minute duration?

**Comment by Swampson** [comment]
It's currently a 1 minute duration, no concentration. I think this is probably fine given they caster has to dump additional TP into the spell (and spend some portion of their turn doing so) if they want it to cause substantial damage.

**Comment by queryluke** [comment]
@Swampson RE: check vs saving throw

My mental difference is that saving throws are in reaction to something and checks are done when a creature is actively choosing to do something. So you'd never have "can use their action to make a saving trow".

I went digging in some spells and found some examples like whirlpool & tsumami. Other spells, like Dominate Person, allow the creature to make a new saving throw, but it's in reaction to taking damage. Anyway, I stuck with the skill check for now, but let me know what you think.

---

### Updated Proposal
* Level: Tech
* Casting Time: Action
* Range: 20m
* Duration: 1 min
* Detonates: no
* Primes: lightning (_this is new_)

__Spell Text__
Spend 2 tech points to shoot a swarm of miniature pylons to a target location within 20m, forming an electrified net over any creature or object within a 4m cylinder. Each creature in the area must make a Dexterity saving throw. On a failed save, the creature is trapped in the net. Trapped creatures are restrained and cannot cast and Tech spells.

A creature restrained by submission net may use its action to make a Strength (Athletics) check against your spell save DC to escape the net. On each attempt, the creature takes 1d6 force damage as it struggles against the net. On a success, the creature is no longer restrained.

Until the spell ends, the area is considered difficult terrain. A creature that enters the cylinder for the first time on its turn or end its turn there must also make the saving throw or becomes trapped by the net.

__Advanced Options__
* Electrified Net:  If you have a submission net deployed, you can use your bonus action to spend XTP, sending electric currents through a single net. Each creature within the net takes Xd6 lightning damage.
* Anti-Tech: If a creature you can see begins to cast a Tech spell, you can use your reaction to cast submission net.

### Thoughts

In this instance, the ability to electrocute is only an advanced option, making this power (at base) more about control. But the electrocution is paired with the ability to cast as a reaction (as a counter to a tech power). It think, in this case, both advanced options are well balanced.

**Comment by Swampson** [comment]
@queryluke, re Saving throw vs skill check: you are absolutely right - I misunderstood the cause and effect of the 1d6 damage - it’s only triggered IF the character attempts a STR check to escape.
