### ISSUE TITLE
Spell Review: Barrier

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#293]
from #284 

## Current
* Level: Cantrip
* Casting Time: action
* Range: self
* Duration: instant
* Detonates: no
* Primes: no

__Spell Text__
Surround yourself in a high-gravity mass effect field that strengthens your defense but reduces your movement speed. While you have any barrier ticks, your speed is reduced by 4m. Whenever you take damage, remove 1 barrier tick and reduce that damage by 1d8. When you cast Barrier, refill your barrier ticks to their maximum amount. Your class indicates the maximum number of barrier ticks you can have.

This reduction increases by 1 when you reach 5th level (2d8), 11th level (3d8), and 17th level (4d8).

__Advanced Options__
* Tactical Barrier: When you take damage, you may choose to expend a Barrier Tick instead of being required to use one.
* Quick Barrier: You may cast Barrier as a bonus action.

## Thoughts
* Clarify, does it last forever?
* This is such an essential spell, I can’t see any biotic class not getting it.  But the action to cast costs a lot of time, especially since it needs to be recast a lot.  It might be worth it to put some thought into making this spell a bonus action normally.   

## Proposal
__Advanced Options__
* Heavy Barrier: ability to expend more than one barrier tick in a turn.  2 max considering that this scales.  Maybe make it mandatory to do so if this advancement option is chosen.

**Comment by queryluke** [comment]
As pointed out by @MonocledMutineer, if an Asari Soldier takes Barrier as one of their biotic initiate cantrips, how many barrier ticks do they get?

So, a possible refactor to Barrier would be to have it explicitly provide a number of barrier ticks and remove the class barrier tick max.

**Comment by queryluke** [comment]
RE: as a bonus action
I'm not of the opinion that Barrier is essential for all biotic users, primarily just Vanguards. Additionally, I've tried to add other cantrips and powers that gain barrier ticks, like Biotic Punch and one of the advanced options of Charge.

**Comment by TheMarmotKing** [comment]
I think making barrier detonation as a component works.  And it gives opportunity for an advancement option related to it.  

Just noting that barrier needs a very strong alternative to bonus action barrier. 
Heavy barrier has potential but the current low number of ticks at early levels makes it unattractive against bonus action
AO if barrier detonation is added: barrier detonates at max ticks when a barrier is depleted.

Referencing level based barrier ticks, I think this would clear up some issues but also make it necssary to adjust some class features.  Vanguard in particular would be getting screwed over by that.  Maybe a class feature to give extra barrier ticks at certain levels.

**Comment by bpmcpherson** [comment]
I also agree that barrier detonation should be a component of the barrier power, as that's how it functions in ME:3. Additionally, it could have the following effect:

> _Detonate the field to lift and dangle nearby targets._

Basically, it's a utility detonation that lifts targets (and could prime in this case) and give an incentive to be used by Sentinels and/or Vanguards, who can better tank attacks while not having a barrier active. 

> Clarify, does it last forever?

I think there needs to be a time limit it will stay active. For how long, I'm not sure. It could be two minutes, it could be ten minutes. I'm not sure and I'm trying to find a good point of reference, but I haven't found one I like. 

> This is such an essential spell, I can’t see any biotic class not getting it. But the action to cast costs a lot of time, especially since it needs to be recast a lot. It might be worth it to put some thought into making this spell a bonus action normally.

A bonus action seems fair. It would make it equivalent to tech armor in that regard.

**Comment by queryluke** [comment]
#### Things that seems settled
1. Barrier detonation becomes a component of barrier
2. Cast as a bonus action

#### Wild idea
What if we got rid of barrier ticks completely? Instead, barrier works similarly to Tech Armor, it's either on or off. I know that's a pretty drastic change, but keeping track of barrier ticks can be cumbersome, there are already a number of other counters: tech points, thermal clips, grenades, medi-gel.  

Here is a breakdown of changes this would require:
* barrier would be a concentration spell, lasting 1 minute
  * counters damage reduction, when an attack gets through, you need to make a con save to keep it up.
* any spells that require barrier ticks, would instead require an active barrier
  * Possible problem is that a character's turn becomes: cast barrier (bonus), cast spell (action), repeat. Although, I guess there are d&d similarities, like hunter's mark & hail of thorns
* Battle master vanguards would need to use superiority die (instead of barrier ticks)
* Nemesis vanguard's metabiotics would need to use a different resource for improving spells (this was based on a sorcerers metamagic)
  * To be honest, this probably needed to change anyway because, currently, you could use your metabiotics infinitely by continuing to keep barrier up. Whereas, a sorcerer is limited by their sorcerer points. The same could be said for battle master vanguards.
* Nemesis teleporting dodge would need a rework (could simply be a short/long rest ability)
* Protection fighting style would need to be reworked
* There is a set of armor that allows barrier that would need to be reworked.

**Comment by bpmcpherson** [comment]
To be honest, all of the cast from Barrier (minus phase disruptor, as the source material actually requires barrier IIRC) or Siphoning Strike abilities could instead work with your shield values as they do in the game. It's more universal a stat and more in-line with the games themselves.

**Comment by queryluke** [comment]
This is one of those powers that is difficult to pin down:

* ME1: Active boost in shields points (i.e., an additional layer of shields)
* ME2: Active boost to overall damage reduction
* ME3: IIRC, Vanguards and Adepts had no shields, they had something called a 'biotic barrier' which worked exactly like shields and was used to cast powers like nova and phase disruptor. There was also a power called Barrier that worked like ME2, but had a new detonation component
* MEA: Passive bonuses to shields

The current iteration is trying to squish the 2 different components of ME3 together.

I'd be hesitant to use shield points as a casting resource because I see shields as generated by a device and barrier as generated by biotic powers. But, mechanically, using shield points makes those abilities unavailable if the character isn't wearing armor or doesn't have a personal shield generator.

**Comment by TheMarmotKing** [comment]
I really like the barrier tick system, and would vote to keep it and work around it

**Comment by queryluke** [comment]
Yeah, I'm struggling with this one. The primary problem is that there are 3 classes that have a class resource (barrier ticks) that can only be acquired by spells. Whereas, class resources (spell slots, superiority dice, tech points) are meant to regenerate over time. 

I don't mind the use of barrier ticks as a class resource, but they need to have some regenerative factor beyond spells. Having barrier ticks also should _not_ reduce speed because that just feels like a blanket penalty to the class.

I see a few paths we can travel down:

### Barrier as a class feature
* Biotic classes gain Barrier as a class feature, not a spell.
* Using the feature regens barrier ticks, but you'd be limited in the number of times you could use it per long rest.
* There would be no speed penalty
* Barrier Detonation would be it's own cantrip

### Keep Barrier as a cantrip
* Biotic classes regain their barrier ticks on a short rest. 
* The Barrier cantrip would either be removed or simply regenerate barrier ticks, nothing else. 
* There would be no speed reduction and no advanced options. 
* Barrier Detonation would need to be its own cantrip

### Remove Barrier ticks
* Barrier becomes an on/of concentration cantrip
* Barrier Detonation is absorbed into Barrier
* Anything involving barrier ticks is refactored (either to use shield points or something else)

**Comment by TheMarmotKing** [comment]
Class feature proposal
Barrier: Use an action to create a biotic barrier around you that reduces incoming damage and fuels certain biotic abilities.  Upon activating, you gain barrier ticks equal to the maximum shown on the class progression table.  Upon taking damage while barrier is active you may choose to expend a barrier tick to reduce the damage by 1d8+you spellcasting modifier.  
This reduction increases by 1 when you reach 5th level (2d8), 11th level (3d8), and 17th level (4d8)
When all barrier ticks are expended, or anytime while barrier is active, you may detonate the barrier as a reaction, forcing all hostile creatures in a 2m radius sphere around you to make a dexterity saving throw or become lifted.
Increase the range of the sphere by 2m at 5th level (4m), 11th level (6m), and 17th level (8m)
As an action you may regenerate all of your barrier ticks.  You may only regenerate barrier ticks a number of times equal to your spell casting modifier plus 1 per long rest (This needs balancing)
You may activate barrier once per short rest.  (I'm thinking a pretty long duration, enough to last till the next short rest if they are careful.)

If Barrier is added as a class feature, the non biotic classes need to have a bone thrown their way to balance this out.  This is also a bit of a wordy explanation, and It might be good to just make barrier detonation a "use x number of ticks to lift these dudes" spell.

**Comment by queryluke** [comment]
I asked Needleman if he had any thoughts about Barrier. He's been running a campaign for a few months now, but he's not on GitHub. Anyway, he said he didn't have any problems with it. It did a good job replacing the damage reduction of a Barbarian's Rage for Vanguards. So I definitely don't want to do a major refactor.

So making it a class based ability definitely fixes the "class resource dependent on spell" problem and also creates new opportunities for class features, like activating barrier as a bonus action.

@TheMarmotKing I like what you've got here. A few thoughts:

__Barrier Detonation__
I think this could stay as a separate cantrip. It would be no different than Phase Disruptor in that it requires barrier ticks to use.

__Times per long rest__
I could be "number of times equal to your spellcasting modifier, minimum 1". I think that's perfect. What sort of balancing were you thinking?

__Choice to use barrier tick when damaged__
I like that (at least early on), you cannot choose to use the tick for damage reduction. Perhaps this can be a new class feature that vanguards get.

**Comment by TheMarmotKing** [comment]
So make one one the vanguard subclasses give barrier improvements based around bonus actions and durability.  
I think giving adepts options to make barrier more efficient as spell ammo and a similar bonus action would be fun.
Sentinel is... Wierd here.  I almost think that if they want barrier it should be only available as a biotic focus subclass option.  
These are just thoughts.  

But I hold fast that making in this a class feature warrents treats for engi, soldier and infiltrator.  

Barrier seems to be taking a while to figure out, I think it would be good to wrap up the other biotic cantrips not involved in barrier just to clear the board a little.
