### ISSUE TITLE
Spell Review: Biotic Push

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#296]
from #284 

## Current
* Level: Cantrip
* Casting Time: Action
* Range: Touch
* Duration: Instant
* Detonates: yes
* Primes: no

__Spell Text__
Make a melee spell attack on a Medium or smaller creature or object within range. On a hit, you create a pocket mass effect field that deals 1d4 force damage the target and repels it 6m away from you.

At higher levels: This spell's damage increases by 1d4 when you reach 5th level (2d4), 11th level (3d4), 17th level (4d4)

__Advanced Options__
* Quick Cast: You may cast Biotic Push as a bonus action.
* Flatten: On a hit, the target is knocked prone.

## Thoughts
@TheMarmotKing pointed out that this is pretty much Throw with no range. It's somewhere between Biotic Punch and Throw...but not as good as either. I'd be ok removing this one.

**Comment by bpmcpherson** [comment]
The fact that biotic throw can be used point-blank, this seems redundant as-is. The only way I can see it staying is to make it have a useful niche of some kind.  

An idea which comes to mind is to adopt the Heavy Biotic Blast that the Asari Justicar uses in the ME:3 multiplayer. [It's a local AoE Range burst that damages and knocks back enemies.](https://youtu.be/_4UWEwi6Tt4?t=2m12s), but it's just their heavy melee attack, so it's more akin to what Biotic Punch is.

**Comment by queryluke** [comment]
Another possibility is simply calling this "Push" and make it a non-damaging ability. Here is "Gust" from 5th edition which could serve as a model.

>You seize the air and compel it to create one of the following effects at a point you can see within range:
> * One Medium or smaller creature that you choose must succeed on a Strength saving throw or be pushed up to 5 feet away from you.
> * You create a small blast of air capable of moving one object that is neither held nor carried and that weighs no more than 5 pounds. The object is pushed up to 10 feet away from you. It isn't pushed with enough force to cause damage.
> * You create a harmless sensory effect using air, such as causing leaves to rustle, wind to slam shutters shut, or your clothing to ripple in a breeze.

**Comment by queryluke** [comment]
Going to go with removing this. We can always come up with other niche powers in the future.

**Comment by bpmcpherson** [comment]
Okay, fair enough. I will say that it might be interesting to look at some of the other "Heavy" melee abilities from ME:3. They had some cool abilities which could be adapted to cantrip-like powers to have other options besides Biotic Punch.
