### ISSUE TITLE
Spell Review: Charge

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#297]
from #284 

## Current
* Level: cantrip
* Casting Time: action
* Range: 10m
* Duration: instant
* Detonates: yes
* Primes: no

__Spell Text__
Alter your mass and choose a creature or object you can see within range. Use the target's mass to pull yourself to its location with incredible force. Any creature or object within a 2m sphere must make a Dexterity saving throw. On a failed save, a creature takes 1d6 force damage and becomes prone. On a successful save, a creature takes half as much damage.

The damage increases by 1d6 when you reach the 5th level (2d6), 11th level(3d6) and 17th level(4d6).

__Advanced Options__
* Barrier Regen: After you cast Charge, regain half of your barrier ticks (rounded down).
* Distance: The force ripples outwards from the point of impact, increasing the radius to 4m.

## Thoughts
(The following from @TheMarmotKing)
- Distance is under powered compared to Barrier Regen

Some possible replacements for Distance
* Rapid Charge: Charge can be cast as a bonus action.
* Stunning blow: On a failed save, the target is stunned till the end of your next turn

**Comment by queryluke** [comment]
My only note on Rapid Charge is that Shock Trooper Vanguards gain the ability to charge as a bonus action from their subclass.

**Comment by bpmcpherson** [comment]
Stunning is more in line with how Charge works in the games.

**Comment by queryluke** [comment]
Ok, replacing distance with stunning.
