### ISSUE TITLE
Spell Review: Dark Channel

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#298]
from #284 

## Current
* Level: Cantrip
* Casting Time: action
* Range: 20m
* Duration: Concentration, 1 min
* Detonates: no
* Primes: necrotic

__Spell Text__
Make a ranged spell attack on a creature you can see within range. On a hit, you plague the target with a persistent, damaging biotic field. The creature is primed (necrotic) and takes 1d10 necrotic damage and 1d10 necrotic damage at the start of your turn while you maintain the spell. If the creature dies, Dark Channel transfers to another random, hostile creature within 10m. Only one Dark Channel can may be active at a time.

The damage increases by 1d10 when you reach the 5th level (2d10), 11th level(3d10) and 17th level(4d10).

__Advanced Options__
* Cripple: If the affected creature would make a saving throw or attack roll, as a reaction you may increase the severity of Dark Channel. The affected creature must roll a d4 and subtract the number rolled from the attack roll or saving throw.
* Improved Damage: Increase the damage die type to d12

## Thoughts
As pointed out by @TheMarmotKing, the spell is a bit too powerful as a cantrip. Here are some dmg outputs for a lvl 5 adept:

- Dark Channel: 11 (2d10) damage (fist turn), then subsequent turns are 11 damage and they get an action to cast another spell.
- Lance: as a level 1 spell, 12-17 (3d8 + spellcasting mod)
- Reave: 11 (2d10) (but causes disadvantage)

Other considerations are moving the automatic transfer to an advanced option, but I'm not sure if that would be as attractive as cripple or improved damage. Also, since the creature is primed, the automatic transfer might never even happen because the spell has a chance to be detonated. Anyway, something to think about.

**Comment by TheMarmotKing** [comment]
Reducing the automatic damage to a d6 would make it less powerful without having to rework anything, and keeps the spirit of the spell alive.  

I also would like to recommend changing the "transfers to another random hostile creature in 10m" to "transfers to the nearest hostile creature in 10 m of the target".  It's simpler to have it hop to the targets neighbor and it's more in line with lore

**Comment by bpmcpherson** [comment]
I'm onboard with @TheMarmotKing 's solution.
