### ISSUE TITLE
Spell Review: Pull

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#299]
## Current
* Level: Cantrip
* Casting Time: action
* Range: 20m
* Duration: instant
* Detonates: no
* Primes: no

__Spell Text__
You create a negative mass effect field around a creature or object you can see within range then jerk the field sharply towards you, bringing the target with it. Only Medium and smaller creatures are affected. The distance the target travels is based on its size, starting at 2m for medium-sized objects and adding 4m for each size small than medium. E.g., Medium = 2m, Small = 6m, Tiny = 10m, etc.

If attempting to pull an object from another creature, the creature must pass a Strength saving throw to retain possession of the object. If you pull a creature and it moves more than 2m, it must pass a Dexterity saving throw or be knocked prone.

The number of targets increase by 1 when you reach the 5th level (2), 11th level (3), and 17th level (4).

__Advanced Options__
* Magician: You can shape and guide pull to add different trajectories to the object. The direction of pull cannot change, but you can add arcs, decrease the distance the object moves, and even pull small objects directly into your hand.
* Push: You may choose to move the target towards or away from you.

## Thoughts
It's been discussed in #266 and @TheMarmotKing pointed it out in his google doc. In ME1, there was a power that lifted and suspended targets in the air. In ME 2,3, & A, it was renamed to Pull. 

I thought that lifting a target in the air was too powerful for a cantrip, so I made a level 1 spell named Lift and a cantrip name pull. However, this seems to have caused a lot of confusion. So it might be worth renaming Lift as Pull. And completely rework this power as something new.

@TheMarmotKing has also suggested reworking Telekinesis from 5th edition, here is his proposal:
* Level: Cantrip
* Casting Time: action
* Range: 30m
* Duration: Concentration, 10 min
* Detonates: no
* Primes: no

You create a mass effect field to lift an object no more than (Insert balanced weight here).  You may move the object in any direction in a 30 meter radius at a speed of 2m.

**Comment by bpmcpherson** [comment]
Pull has become a rather complicated power in the later games since it's both a lifting power or, optionally, a force choke-equivalent ability (with multitarget abilities at higher levels).

**Comment by TheMarmotKing** [comment]
So what are the thoughts on making a "biotic lift stuff and move it around" cantrip? It would take some balancing (through level scaling I think) to avoid "LIFT A STARSHIP AND DROP IT ON THEIR HEADS" but I think flavor spells are can be fun

**Comment by queryluke** [comment]
### Proposal
__Rename 'Lift', the 1st level spell will be renamed 'Pull'__

* Level: Cantrip
* Casting Time: action
* Range: 20m
* __Duration: Concentration, 10 minutes__
* Detonates: no
* Primes: no

__Spell Text__
You can manipulate light objects with a series of mass effect fields.  When you cast this cantrip, you can try to move an object that weighs up to 10 kgs (~20 pounds). If the object isn't being worn or carried, you automatically move it up to 10 meters in any direction, but not beyond the range of this spell.

If the object is worn or carried by a creature, you must make an ability check with your spellcasting ability contested by that creature's Strength check. If you succeed, you pull the object away from that creature and can move it up to 10 meters in any direction but not beyond the range of this spell.

__Advanced Options__
* Magician: You can exert fine motor control over the object, such as manipulating a simple tool or removing an object from a container.
* Improved Lift: You can manipulate an object that weighs up to 25 kgs (~55 pounds).

**Comment by TheMarmotKing** [comment]
This feels like a good flavor filled addition.  No further comments from me
