### ISSUE TITLE
Swapping Juggernaut and Battlemaster subclasses

### ISSUE THREAD

**Issue by Swampson** [queryluke/masseffect-5e#3]
Per a conversation with @queryluke, we should consider swapping the Juggernaut subclass to Vanguard and the Battlemaster subclass to Sentinel.

## Suggested changes to Juggernaut subclass:
Replace "Imbue Omni-Tool" and "Tech Armor Overload" with "Improved Barrier Capacity(1)" and "Improved Barrier Capacity(2)", so that the advancement table reads:

2. Improved Melee Damage
6. Improved Barrier Capacity (1)
10. Melee Casting
14. Improved Barrier Capacity (2)
18. Improved Melee Damage (2)

## Suggested changes to Battlemaster subclass:
I am not sure if "Imbue Omni-tool" and "Tech Armor Overload" would work as replacements for "Improved Barrier Capacity" or not in this revised subclass. This may need further discussion.

2. ?
6. Battlemaster (1)
10. Battlemaster (2)
14. ?
18. Battlemaster (3)

**Comment by queryluke** [comment]
checkout my issue 3 branch.

I've split what used to be "Improved Tech Armor" into multiple features and split those between the battlemaster and bastion class. Now the bastion class is more melee tank, with better shields from tech armor, some additional melee features, but the main piece is the protective tech armor. Battlemaster's tech armor gets the "reactive" and "adaptive" pieces, which I feel play into the idea of a "battlemaster", whatever that means.
