### ISSUE TITLE
Spell Review: Slam

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#300]
## Current
* Level: cantrip
* Casting Time: Action
* Range: 20m
* Duration: Instant
* Detonates: no
* Primes: no

__Spell Text__
Target a lifted object and slam it to the ground dealing bludgeoning damage equal to 2d8 + your spellcasting ability modifier. The target is no longer lifted but is prone.

The number of targets increases by 1 when you reach 5th level (2), 11th level (3) and 17th level (4)

__Advanced Options__
* Stun: The creature must pass a Constitution saving throw or stunned for 1 round.
* Improved Damage: Increase the damage die type to d12

## Thoughts
Like Barrier Detonation, this is another spell that has a prerequisite. It's not as bad, but it might be better off being a component of Lift (or Pull, depending on #299)

**Comment by TheMarmotKing** [comment]
I think that in order to make this spell good we should make sure there are ample opportunities and abilities to lift targets.  This is really only an issue at low levels right now as barrier detonation and lift are the only spells at early level that use the effect.  

Alternatively slam can be made into a standalone spell that lifts then slams the target into the ground.  However I think this is a little redundant as a damage dealing cantrip since we already have throw and the like.  

I like the idea of having a spell that can be used against lifted enemies, in combo with other abilities.  

So my proposal is that rather that making serious changes to slam, we add advancement options to other spells that do lift and work out pull vs lift

**Comment by bpmcpherson** [comment]
I think it's fine to have a power which is designed to work with others, so long as the ability to lift is readily available. One could make the case that a target which is airborne could be slammed (i.e. hovering on a jetpack or a high leap), which would extend the utility of the attack.

**Comment by queryluke** [comment]
Hmm, so perhaps the qualifying text is: "target a creature or object that is lifted or at least 4m in the air"

**Comment by TheMarmotKing** [comment]
I think keeping it to lifted targets to keep it simple might be the way to go

**Comment by queryluke** [comment]
### Proposal
* Level: cantrip
* Casting Time: Action
* Range: 20m
* Duration: Instant
* Detonates: no
* Primes: no

__Spell Text__
Target a lifted creature or object and slam it to the ground dealing 2d8 bludgeoning damage and knocking it prone. The target is no longer lifted.

The number of targets increases by 1 when you reach 5th level (2), 11th level (3) and 17th level (4)

__Advanced Options__
* Stun: If the target is a creature, it must pass a Constitution saving throw or becomes stunned until the end of your next turn.
* Reaction: When a creature or object becomes lifted, you may cast Slam as a reaction.

### Thoughts
I like the possibility of this being used on flying creatures but I think the qualifying aspect of the spell is that a target is caught in a negative mass effect field, so it's easy to target them with the positive mass effect field that slams them to the ground. Hence the lack of an attack roll. That said, as a GM, I'd allow players to cast this on flying targets, but I'd make them make a range spell attack roll.

I removed the improved damage because it's scaling damage is limited to the number of lifted targets. Though being able to cast this spell as a reaction seems powerful, I didn't some solor playtesting with 3 lvl 12 adepts: one always using singularity, one always using slam, one always using AoE attacks to take advantage of the prone position. It would certainly be a little frustrating for the GM, having creatures constantly lifted and slammed, but the spell slots dried up pretty quickly, so it wasn't too over powered.

**Comment by bpmcpherson** [comment]
I suppose that's where the GM would need to adapt to the situation. Too many Lift/Slam scenarios? Send in larger targets that will be the focus.
