### ISSUE TITLE
Spell Review: Phase Disruptor

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#301]
## Current
* Level: Cantrip
* Casting Time: Action
* Range: 20m
* Duration: Instant
* Detonates: yes
* Primes: no

__Spell Text__
You focus the energy of your barrier into a high-powered beam at a target creature or object within range. Remove 1 barrier tick and make a ranged spell attack on that target. On a hit, the creature takes 3d4 force damage.

A higher levels, you may use additional barrier ticks to create more than one beam: two beams at 5th level, three beams at 11th level, and four beams at 17th level. You can direct the beams at the same target or at different ones. Make a separate attack roll for each beam.

__Advanced Options__
* Improved Damage: d6
* Cripple: Creature's hit by Phase Disruptor have disadvantage on their next attack roll.

## Thoughts
Included as part of the cantrip review. I currently have no issues with it.

**Comment by TheMarmotKing** [comment]
Considering the current low cap for barrier ticks at lower levels, especially for adapts who are most likely to use this spell as a go-to ranged attack, some ability to regain ticks without having to use biotic punch or pick up biotic punch might be nice. 

An advancement option to regain ticks on a hit? I just don't care for the idea of having to cast barrier, make two attacks(assuming you take no damage) then cast barrier again when you're level 1.

**Comment by bpmcpherson** [comment]
It becomes far more viable at later levels and when used in tandem with recovery options. I don't think it's entirely necessary to have to make cantrips be highly effective for lower levels even if they can take them at that time.
