### ISSUE TITLE
Spell Review: Slow Fall

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#302]
## Current
* Level: cantrip
* Casting Time: reaction
* Range: 10m
* Duration: concentration, 1 minute
* Detonates: no
* Primes: no

__Spell Text__
When you or a creature within 10m of you falls, choose up to five falling creatures within range. Create a negative mass effect field around each creature, slowing the rate of descent to 20m per round. If the creature lands before the spell ends, it takes no Falling damage and can land on its feet, and the spell ends for that creature.

__Advanced Options__
* None
* None

## Thoughts
There aren't any advancement options.

**Comment by TheMarmotKing** [comment]
I honestly think this spell can stay where it is.

**Comment by bpmcpherson** [comment]
One idea for an advanced option, if you're looking to add one, is to allow the user to control the direction of the fall. Beyond that, other options include increasing the slowing effect, number of affected creatures/objects, etc.

**Comment by TheMarmotKing** [comment]
Unless AOs add a completely new aspect of utility to the spell, there's not much way to make it worthwhile to advance it.  It's a really good cantrip for clever plays and I don't think it needs anything

**Comment by queryluke** [comment]
### Proposal
__Advanced Options__
* Increase duration to 5 minutes
* As you fall, you can direct your fall by 2m in any direction except up. You may do this once per round.

### Thoughts
The likelihood of taking either advanced options is small. But I hope to diverge the cantrips acquisition from spell acquisition at some point, which means players will have more cantrips overall. So, in preparation for that, these 2 options seems sufficient.

**Comment by bpmcpherson** [comment]
Seems like decent options.
