### ISSUE TITLE
Spell Review: Throw

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#303]
## Current
* Level: cantrip
* Casting Time: action
* Range: 20m
* Duration: instant
* Detonates: yes
* Primes: no

__Spell Text__
Make a ranged spell attack on a target you can see within range. On a hit, hurl the target backwards 10m and deal force damage equal to 1d6 + your spellcasting ability modifier.

At higher levels: This spell's damage increases by 1d6 when you reach 5th level (2d6), 11th level (3d6), 17th level (4d6)

__Advanced Options__
* Improved Force: Throw is so forceful, it lifts the target off the ground when knocking it back. Targets must pass a Dexterity saving throw or are knocked prone.
* Improved Damage: Increase the damage die type to d8

## Thoughts
* 10m is pretty far with no size restriction.

**Comment by bpmcpherson** [comment]
If we go based on how Throw works in the games, larger enemies are not moved at all by the attack. They simply take the damage. So clearly, there are limits to the ability. However, the common evolution to the ability is to either make the throw do more against single opponents or hit multiple opponents by increasing the radius of the effect (making it more of a target burst) and/or multiple projectiles (which tends to be a class-based ability in this system).

Now, I don't know if this should be mentioned in the skill or not, but when a target is either lifted or in a lower gravity environment, throw has a much more effective knock-back.

**Comment by TheMarmotKing** [comment]
Proposal: retain the damage, making it balanced in the face of other damage cantrips.  Maybe a d8? Gotta come up with a reason for people to use this instead of punch and phase disruptor
When a lifted tarted is hit by this ability, they are hurled back 10 m and take damage upon impact with a surface.
Proposed AO: you may select two targets when casting this spell
And keep increased damage. Maybe even increase against lifted targets.

**Comment by queryluke** [comment]
For me, reasons for using this over the other damaging cantrips:
* Biotic Punch, don't want to be in melee range
* Phase disruptor, don't have barrier or don't want to loose barrier ticks
* Dark Channel, using another concentration spell

Adding AoE would be a pretty good advancement option: On a hit, each creature within a 2m radius of the initial target is also knocked back.

**Comment by queryluke** [comment]
### Proposal
* Level: cantrip
* Casting Time: action
* Range: 20m
* Duration: instant
* Detonates: yes
* Primes: no

__Spell Text__
Make a ranged spell attack on a target you can see within range. On a hit, the target takes force damage equal to 1d8 force damage. If the target is Medium or smaller, it is pushed backwards 10m.

At higher levels: This spell's damage increases by 1d8 when you reach 5th level (2d8), 11th level (3d8), 17th level (4d8)

__Advanced Options__
* Radial Blast: On a hit, the damage is dealt to each creature within 2m.
* Improved Damage: Increase the damage die type to d12.

## Thoughts
Looking at the list of damage dealing cantrips in 5th edition:
* cantrips that hit more than 1 target deals 1d4-1d6 damage. 
* cantrips that hit 1 target and add some sort of debuff is 1d4-1d8 damage (depending on how "good" the debuff is)
* cantrips that hit 1 target without a debuff deal 1d10-1d12 damage

Based on this info, I increased the damage to 1d8, because the knockback isn't a huge benefit. Additionally, I've stuck with the basic improvements: (AoE vs more damage)

**Comment by bpmcpherson** [comment]
I like the proposed changes.

**Comment by TheMarmotKing** [comment]
I'm going to start on the 1st level biotic spells probably today or tomorrow.  Probably do a Google doc then transcribe them to posts.
