### ISSUE TITLE
A huge problem with 0.8.0

### ISSUE THREAD

**Issue by TheMarmotKing** [queryluke/masseffect-5e#309]
I'm kidding hahaha.  Actually I just wanted to say wow, these new backgrounds and the rest of this update are really incredible!  I'm itching to try them out.  The forums had been silent for a while and now I see why, Luke and Hugh you guys are great.  
So yea I just wanted to throw down some appreciation and thank you guys for all the work you put into this thing.  Keep up the amazing work!

**Comment by queryluke** [comment]
@TheMarmotKing Oh man, you got me good! XD

**Comment by Swampson** [comment]
@TheMarmotKing you got me too! As much as I appreciate the praise, the credit really does go to @queryluke - he's done basically all the work you see in the 0.8.0 release.

**Comment by Nmmoriarty** [comment]
It is looking quite good.  What's left to review at this point?

**Comment by queryluke** [comment]
@Nmmoriarty Sometime this week, I'll make new spell review tickets for all the 1st level spells. Then we'll move onto 2nd, 3rd, & 4th. Tech spells, then combat powers. I'd also like to get a class review in before v0.9.0, but I want the spells to be pretty solid before looking at classes.

I figure we'll save background and toolkit reviews for post-v0.9.0

**Comment by TheMarmotKing** [comment]
Class review is going to be a substantial undertaking I think.  I looked over some of the 1st level biotic spells and actually didn't find very much to comment on.  I feel like the higher level spells are going to be easier to review.  I'm looking forward to going over tech skills.
