### ISSUE TITLE
Allow All Classes for All Races in the Grunt Generator

### ISSUE THREAD

**Issue by rexthepig** [queryluke/masseffect-5e#310]
**Is your feature request related to a problem? Please describe.**
In the player's Handbook, it says that the race/class restrictions can be lifted at the GM's discretion, yet the Grunt generator still won't allow you to make combinations that go against said descriptions.

**Describe the solution you'd like**
The ability to select all classes for all races, and vice versa. Maybe put the restricted races/classes in a different colour, such as red, if possible.

**Describe alternatives you've considered**
Another option would be to have a button to toggle on/off the race/class restrictions.

**Comment by queryluke** [comment]
Good point. It's easy enough to remove and will actually take out a somewhat janky piece of code.
