### ISSUE TITLE
Monsters: More Aliens

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#312]
From @rexthepig

-Keepers
-Pod Crabs
-Gass Bags
-Thorian Creepers
-Maybe the Thorian (Although I have no idea how one would do that, so maybe not.)
-Unarmed Elcor
-Hanar (You know, in case a player decides to punch one)

**Comment by rexthepig** [comment]
Rachni Queen would be good to have along with the rest of the rachni forces.

**Comment by queryluke** [comment]
tacking in google sheet

https://docs.google.com/spreadsheets/d/18AJJLaqv3vM-RS4HKF0khirPeXIpls1zrltJx22-6Lw/edit?usp=sharing
