### ISSUE TITLE
Monsters: Archetypes (standard grunts)

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#313]
Idea brought up by @rexthepig. The grunt generator works for now, but it would be nice to expand the bestiary. Some examples off the top of my head are:

- Salarian STG agent
- Human CAT6 agents
- Asari Justicar
- CSEC officers (based on citadel races)

Feel free to drop in other ideas here.

**Comment by rexthepig** [comment]
N7
-Demolisher
-Destroyer
-Fury
-Paladin
-Shadow
-Slayer

**Comment by rexthepig** [comment]
- Turian Cabal Vanguard
- Batarian Troops

**Comment by queryluke** [comment]
tracking these in a new google sheet
https://docs.google.com/spreadsheets/d/18AJJLaqv3vM-RS4HKF0khirPeXIpls1zrltJx22-6Lw/edit?usp=sharing
