### ISSUE TITLE
Prothean Race

### ISSUE THREAD

**Issue by HadesJester** [queryluke/masseffect-5e#315]
Hello, hello fellow ME fan! I was sitting at my desk and contemplating on how there are so many cool races that haven't been added. Now please ignore this if it has already been discussed, but I have a custom template for a Prothean race. I was playing one awhile back on 5e DnD and decided to share!
Speed: 10
Sexy Level: 5
+2 Intellect
+1 Wisdom
Perfect Sight: Since Protheans have 4 eyes, it would give them advantage on Perception checks.
Past Sense: Able to read ones past in the past week (must be a willing creature and alive). Level 6 they are able to go back a month (yes there was a huge gap between this and the actual game, but it kinda needs to be balanced, yeah?).
Feat: Any choice.

Do know that this is what I used on 5e DnD and I'm very open to discussion. I would love to see the Prothean race on the page as a playable race.

**Comment by queryluke** [comment]
@HadesJester thanks for the idea! @bpmcpherson had already come up with a Prothean concept, found in #218. I'm going to move your ideas over there.
