### ISSUE TITLE
Dexterity over-representation

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#316]
In this system, Dexterity is almost invaluable due to the number of spells and abilities that require dex saves. This is certainly true in D&D, but their spell list is so much larger, they have a variety of other saves.

As part of our spell review, something I'd like to start looking at is incorporating alternative saves into the mix.

A quick blanket fix for some are:

- Any displacing powers or holding powers require a Strength save
- Any cold or lightning damaging powers require a Constitution save

### Edit (2018-09-05)
I'm going to keep a running list of spells and their saving throws here as we work through the spell review. When we're done, this should provide a better sense of where the spells stack up.

ST | Count | Spells
--- | --- | ---
STR | 5 | Storm, Stasis, Lash, Cryo Blast**, Cryo Beam**
DEX | 8 | Barrier Detonation*, Charge*, Nova*, Catapult, Shockwave*, Vortex*, Singularity*, Dark Sphere*
CON | 6 | Alter Center Mass, Reave (AO Only), Flare, Annihilation Field, Dark Sphere, Cryo Beam*
WIS | 2 | Dominate, Decoy
INT | |
CHA | |

\* Potential to change to STR or CON save
\*\* On unprotected targets

**Comment by Swampson** [comment]
I think it's also worth considering the impact of Dex as an attack modifier - considering that almost all weapons in the game are ranged. Specifically, I think there's an argument to be made that Shotguns could use STR as the attack mod instead of DEX.

**Comment by Nmmoriarty** [comment]
This is a rough thing to balance.  Instead of making shotguns STR, I think making melee more worth while would be a better alternative.

**Comment by TheMarmotKing** [comment]
I actually think shotguns being STR is a good idea.  I toyed with a similar system while making my own version of this (since scrapped lol).  I would also throw out that come guns could be versatile, kind of like the finesse trait in E5.  Mmortiaru brings up a good point, although Melee weapons do already ignore shields.  I think it would be appropriate to buff the non common Melee weapons.  Like the krogan Warhammer and I dunno, stun battons.  Leave daggers and get based Melee alone.

**Comment by bpmcpherson** [comment]
It's unfortunately what happens when shooting is the baseline combat style in the series. That being said, I think the best approach is to make the alternatives, be they melee or powers, truly worth investing in over having to go ham in investing in your shooting skills.

**Comment by queryluke** [comment]
An idea I had was to replicate 5th's model for this:

>For attacks with melee weapons, use your Strength modifier for attack and damage rolls. A weapon that has the finesse property, such as a rapier, can use your Dexterity modifier instead.
>For attacks with ranged weapons, use your Dexterity modifier for attack and damage rolls. A weapon that has the thrown property, such as a handaxe, can use your Strength modifier instead.
[source](https://www.dndbeyond.com/compendium/rules/basic-rules/step-by-step-characters#5ChooseEquipment)

Now, no one is throwing weapons. But I my idea is to introduce __Recoil__ as weapon property. Any weapon with __Recoil__ can use STR instead of DEX. This represents the ability keep the weapon level and on target using muscle rather than fine-motor skills.

**Comment by bpmcpherson** [comment]
It's worth playing around with and seeing how the existing weapons fit into the mold.

**Comment by SleightxHope** [comment]
Perhaps it would be worth it to use the Weight of a weapon to calculate a separate value for Recoil. The heavier the weapon, the higher the Recoil value from 0-5. If your STR modifier isn't > or = to the Recoil value, the shot is made at disadvantage. This would make sure that people who take larger weapons into battle have the physicality to use them. Plus it doesn't make DEX a god-skill any more.

Weight to Recoil Proposed Chart:
1-3 = 1 : Most light blades and holdout weapons.
4-6 = 2 : Most heavy pistols and SMGs. Some lighter assault rifles, shotguns and sniper rifles.
7-9 = 3 : Most assault rifles, shotguns and sniper rifles.
10-12 = 4 : Most heavy weapons and heavy-grade shotguns/LMGs/anti-material rifles.
13-15 = 5 : Artillery-grade weapons and mounted guns not typically meant to be carried. Only Krogan and Elcor would consider this reasonable.

**Comment by bpmcpherson** [comment]
That is an idea I do like. Could even be worth integrating that with a sort of mod which can make a weapon have light materials in its construction similar to those in ME:A.

**Comment by SleightxHope** [comment]
Good idea, bpmcpherson! Could be worth it to replace Ultralight Materials' current effect (reduce weapon Weight by 1/2) with the following:

Ultralight Materials I: Reduce weapon Weight by 2 and Recoil by 1.

**Comment by queryluke** [comment]
I've added the weight/strength idea proposed by @SleightxHope in the new "Found Codices" section of #382 we can continue to iterate in new issues or later versions.
