### ISSUE TITLE
Blackstar Adept has Tech armor upgrade

### ISSUE THREAD

**Issue by Lodus** [queryluke/masseffect-5e#317]
I don't know if this goes in the " bug " section but.

The adept's level 14 subclass skill for the Blackstar is the level 3 tech armor upgrade.

![biotic](https://user-images.githubusercontent.com/3013279/41638390-1a3c63d4-7427-11e8-868f-bb252515a0eb.PNG)

**Comment by queryluke** [comment]
Yes, very much a bug. Thanks for catching this.
