### ISSUE TITLE
1st Level Biotic Spells Review 

### ISSUE THREAD

**Issue by TheMarmotKing** [queryluke/masseffect-5e#319]
https://docs.google.com/document/d/1BA8VKstW4C6_ce2HgBE-WMNbvDmPjQbNZDadLEMs-LI/edit?usp=sharing

I find it much easier to write these all at once without using the template.  Sorry about that.  Makes it much harder to maintain a stream of thought if I'm filling out a form before looking at each spell.  But Yea Here is 1st level spells!  Lets get started

**Comment by queryluke** [comment]
No worries! Thanks for putting it together. I can break them out into separate tickets. I've really been meaning to get to this, but I've been focusing on the new character sheet, bug fixes, and a some backend changes.
