### ISSUE TITLE
Biotic Spell review lvl 2

### ISSUE THREAD

**Issue by TheMarmotKing** [queryluke/masseffect-5e#320]
https://docs.google.com/document/d/1JGTTRezuXsM2l62z6SXWJNZ1jTRj7NMOVk9OkTGQ92I/edit?usp=sharing

I'm on a roll today. 
Gotta say the level two spells actually sound really fun in general.  Biotic Orbs and Backlash I really loved.

**Comment by queryluke** [comment]
moved these to individual issues, thanks for the initial review!
