### ISSUE TITLE
Spell Review: Nova

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#325]
## Current
* Level: 1st
* Casting Time: Action
* Range: Self, 2m sphere AoE
* Duration: Instant
* Detonates: yes
* Primes: no

__Spell Text__
Transfer the energy of your barrier into a biotic explosion, consuming your remaining barrier ticks. Creatures within a 2m sphere centered on you must make a Dexterity saving throw. On a failed save, a creature is knocked prone and takes force damage equal to Xd10, where X is the number of barrier ticks. On a successful save, a creature takes half as much damage.

When you cast this spell using a spell slot of 2nd level or higher, the radius of the explosion increases by 2m for each level above the 1st.

__Advanced Options__
* Improved damage: Increase the damage die to d12.
* Half blast: You may cast nova twice within a single action. Each cast consumes one half of your barrier ticks. If you have an odd number of barrier ticks, you choose which blast consumes the remaining tick. You can move in between the blasts.

## Thoughts
From @TheMarmotKing

With the way barrier works right now, this spell might not be good.  If a dude charges in and uses Nova, he loses out on some important damage reduction while presumably in the middle of the baddies.  The Prone is a nice touch, but could make it harder for your gun wielding team to back you up (disadvantage against prone enemies on ranged attacks).  
Cantrips using barrier ticks is one thing, especially with the ability to regain with biotic punch, but this spell is a big risk without enough payoff.  

Recommendation:  Increase the damage by a lot.  Make those barrier ticks count.  That or add some kind of shield/barrier regen on successful hits.  

AO: Improved Damage: Already touched on, the damage needs to be improved already.  Personally I’d switch this with the higher spell slot option.  Increase damage per spell slot, Increase range per tick used with this advancement
Half Blast: So… basically either they have disadvantage on a prone save or you get to split your damage between two areas.  Not going to lie this one feels… off.  
I think an advancement option regarding barrier ticks or damage to shields would be more appropriate.  
Nova is part of the Barrier problem, so it’s going to evolve and change with that particular ability.

**Comment by queryluke** [comment]
Initial thing to change is make it a Strength save rather than Dex save (helps with #316 )

As for damage analysis (_when I calculate damage for AoE spells, I base it on 2 creatures taking damage, one succeeding and one failing, but there is obviously more potential_):

#### 1st level vanguard
* Lance = 3d8 + spell mod = 14 - 19 dmg
* Shockwave = 3d6 = 15 dmg
* Nova = 3d10 = 24 dmg

#### 10th level vanguard
* Warp = 3d10 + spell mod = ~21 dmg
* Shockwave (as 2nd level) = 4d6 = 21 dmg
* Nova = 5d10 = 40 dmg

#### 20th level vanguard
* Warp (4th level) = 5d10 + mod = ~32 dmg
* Storm = 8d10 = 66 dmg
* Nova = 10d10 = 82 dmg

But! Nova costs a spell slot and all barrier ticks (and a bonus action if you want to ensure a max level hit). Which is a bit of a resource nightmare.

This is the only non-cantrip that utilizes barrier ticks. So I'm wondering if the simplest change is to make this a cantrip and reduce the damage to d8. The d8 would still be higher than the recommended damage for AoE cantrips (1d6), plus you have a variable amount of damage.

**Comment by TheMarmotKing** [comment]
Cantrips do seem to lack a good around damage option, and this might be a great way to fix that.  It also keeps barrier ticks in the cantrip section, so they don't use other resources.  On top of that, Nova scales kind of automatically with levels, simply due to barrier ticks.

**Comment by queryluke** [comment]
## Current
* _Level: Cantrip_
* Casting Time: Action
* Range: Self, 2m sphere AoE
* Duration: Instant
* Detonates: yes
* Primes: no

__Spell Text__
Transfer the energy of your barrier into a biotic explosion, consuming your remaining barrier ticks. Creatures within a 2m sphere centered on you must make a Dexterity saving throw. On a failed save, a creature is knocked prone and takes force damage equal to Xd8, where X is the number of barrier ticks. On a successful save, a creature takes half as much damage.

At higher levels: This spell's damage increases by 1d8 when you reach 5th level (X + 1d8), 11th level (X + 2d8), 17th level (X + 3d8)

__Advanced Options__
* Improved damage: Increase the damage die to d12.
* Half blast: When you cast nova, it consumes one half of your remaining barrier ticks (rounded up), but deals damage as if you had used all of your remaining barrier ticks.
