### ISSUE TITLE
Spell Review: Reave

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#327]
## Current
* Level: 1st
* Casting Time: Action
* Range: Self, 6m cube AoE
* Duration: Instant
* Detonates: yes
* Primes: necrotic

__Spell Text__
Unleash a wave of dark biotic energy in a 6m cube. Each creature within the blast becomes primed (necrotic) until the end of its next turn and must make a Constitution saving throw. On a failed save, a creature takes 2d10 necrotic damage and has disadvantage on their next attack or saving thrown. A creature takes half as much damage on a successful save.

At Higher Levels: When you cast this spell using a spell slot of 3rd level or higher, increase the damage by 1d10 for each level above the second.

__Advanced Options__
* Distance: Increase the range of Reave to 10m.
* Armor boost: The dark energy heightens your senses momentarily. When you cast Reave, gain +2AC until the start of your next turn.

## Thoughts
From @TheMarmotKing

Looks fine to me.  The logical alternative if you don’t feel like using Nova.  One thing, Is the higher level trait supposed to say “if you cast at a spells lot of 2nd or higher”? Because it says third slot right now and that seems off. 

Although, is reave not traditionally a single target ability that drains health?  I’m fine with diverging from the game version for balance sake but I just want to check.

AO: Distance:  I’m not a fan of distance talents, but that’s just me.  It’s fine how it is
AO: Armor Boots: Could be based on how many enemies hit?  
Suggestion:  Just to stick with the original a bit, maybe a health restoring talent could be added here?

**Comment by queryluke** [comment]
In ME2 reave restored health. In ME3, reave gave damage resistance. I went with the latter because I was trying to avoid biotic spells in regenerated health. This is a loose concept. Many ME fans reeled at the expanded spell list provided by ME3 multiplayer. The general argument was "biotics powers can only increase and lower the mass of objects" I've tried to stretch this as best I could with descriptions. I've also included dark energy as the source of necrotic biotic powers (like reave), my own sci-fi justification being: dark energy can increase/decrease mass at an atomic level, which can create isotopes and irradiate elements.

Anyway, that's all more for flavor than anything.

__Single vs Multi target__
You're right, reave is supposed to be single target. It's multi-target right now simply to add variety to the spell list. But that's not a great reason. I'm already re-imagining Push as a 1st level cone AoE that works similarly to Gust of Wind.

I'll think on this some more and make a proposal to iterate on.

**Comment by TheMarmotKing** [comment]
I think that we have a lot of aoe/multi target spells for biotics as is.

**Comment by queryluke** [comment]
## Proposal
* Level: 1st
* Casting Time: Action
* __Range: 50m__
* Duration: Instant
* Detonates: yes
* Primes: necrotic

__Spell Text__
Hurl an orb of dark energy at one creature within range. Make a range spell attack against the target. On a hit, you deal 2d10 necrotic damage and the target has disadvantage on their next attack, ability check, or saving throw. The disadvantage lasts one minute or until the target becomes incapacitated.

At Higher Levels: When you cast this spell using a spell slot of 2nd level or higher, increase the damage by 2d10 for each level above the first.

__Advanced Options__
* Area Reave: The orb becomes unstable and explodes when it reaches the target. Hit or miss, the target and each creature within 2m or it must succeed on a Constitution saving throw or take 2d6 necrotic damage. When you cast this spell using a spell slot of 2nd level or higher, this damage also increases by 2d6 for each level above the first.
* Immediate Detonation: When you hit a target with reave, it detonates the primed target at the end of your turn.

## Thoughts
This is pretty much an overhaul. To bring it more in line with Mass Effect, Reave is a ranged spell attack with only a single target. Area Reave provides some AoE potential and gives another chance to cause damage even with a miss. Immediate Detonation turns reave into a stunning spell, as necrotic detonation causes a Con save or the target is stunned.
