### ISSUE TITLE
Spell Review: Shockwave

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#328]
## Current
* Level: 1st
* Casting Time: Action
* Range: self, 10m line AoE
* Duration: instant
* Detonates: yes
* Primes: no

__Spell Text__
Create a cascading shockwave in a 10m line originating from you. Each creature must make a Dexterity saving throw. On a failed save, a creature takes 3d6 force damage and is knocked prone. On a successful save, a creature takes half as much damage.

At higher levels: When you cast this spell using a spell slot of level 2 or higher, the damage increases by 1d6 for each slot level above the 1st.

__Advanced Options__
* Improved Distance: The shockwave travels 16m
* Improved Damage: Increase damage die type to d10

## Thoughts
I'm not sure any players would take the improved distance as an advancement. It's not as attractive as the damage. Perhaps improved distance and area, 16m long by 4m wide...that might be too much AoE. Or a 10m cone. Anyway, I'm open to an updated or replacement AO for improved distance.

**Comment by Fakaozada** [comment]
Maybe adding some new mechanics to the improved distance, like changing the direction of the shockwave if it hits a wall or something... The new tragetory could be random or calculated depending on the spell casting line... This could add some new forms to use the spell...

**Comment by queryluke** [comment]
## Proposal
_The only change is to specify the width of the line and the Improved Distance AO gives the user control of the line, which has some interesting capabilities to work around cover, angle off walls, etc._

* Level: 1st
* Casting Time: Action
* Range: self, 10m line AoE
* Duration: instant
* Detonates: yes
* Primes: no

__Spell Text__
Create a cascading shockwave in a 2m wide by 10m long line originating from you. Each creature caught in the line must make a Dexterity saving throw. On a failed save, a creature takes 3d6 force damage and is knocked prone. On a successful save, a creature takes half as much damage.

At higher levels: When you cast this spell using a spell slot of level 2 or higher, the damage increases by 1d6 for each slot level above the 1st.

__Advanced Options__
* Controlled Shockwave: The shockwave travels 16m. You may change the direct of the line every 4m.
* Improved Damage: Increase damage die type to d10
