### ISSUE TITLE
Drones do not scale, underpowered at higher levels

### ISSUE THREAD

**Issue by EvanED** [queryluke/masseffect-5e#329]
**Describe the bug**
Unless I'm missing something, there's no longer description of the drone types (speeds, ACs, starting health, effects).

**To Reproduce**
1. Go to the [engineer class page](https://n7.world/phb/classes/engineer)
2. Click on 'drone' (under level 1)
3. It lists the L1 drone availability, but no descriptions
4. Also check the L2 subclass feature descriptions, and over on the subclass tab, and the spell list

**Expected behavior**
A description of the drone types, like [what used to be there](https://i.imgur.com/Ig0QlhN.png) on [earlier versions](https://evaned.github.io/masseffect-5e/phb/#/classes/engineer)

**Comment by queryluke** [comment]
@EvanED In v0.7.0, we revised drone jockeys and drones. The drones now have their own stat block in the bestiary. So when you summon a drone, you summon the bestiary version. Does that clarify?

**Comment by EvanED** [comment]
I see, thank you very much.

I'm tempted to suggest adding a note in the engineer's level table's drone description that stats are in the bestiary. I'm not convinced that this is totally necessary and not just a crutch for people like me who knew where they used to be, but my argument for why it goes beyond that is that at least from my not-very-fluent-in-D&D stance, the bestiary is something mentally lumped in as a "GM tool," which is at least part of why it didn't occur to me to look there. Looking at the Ranger description in the native PHB to compare, I see that it seems like you need to look at the bestiary for that as well but the description doesn't say that explicitly -- but it _does_ specifically use the term "beast", includes mention of the allowed CR, and gives a couple examples in the PHB.

A couple things lost with this change (don't take that as criticism exactly; I'm not nearly experienced enough to be able to guess how things turn out from a balance perpsective) are:

* You can't vary your TP spend to change the strength of the drone
* The drone's attributes no longer vary with your level

I'm assuming these changes are intentional?

**Comment by queryluke** [comment]
@EvanED 

> You can't vary your TP spend to change the strength of the drone

Yes this was intentional.

> The drone's attributes no longer vary with your level

Yep, this is something that needs to be addressed. Other class powers get improved versions or scale as they level. Engineers falls pretty flat at later levels.

**Comment by bpmcpherson** [comment]
Is it possible to scale them a la animal companions?

**Comment by queryluke** [comment]
@bpmcpherson That would be ideal, it's just figuring out which stats to buff and be sure that the benefits don't outweigh choosing the Drone Jockey subclass
