### ISSUE TITLE
Spell Review: Fly

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#338]
## Current
* Level: 2nd
* Casting Time: Action
* Range: 60m
* Duration: Concentration 10 min
* Detonates: no
* Primes: no

__Spell Text__
Create a negative mass effect field around a willing, Medium sized or smaller creature and lift it 2m into the air. The creature's speed becomes zero, but you can use a bonus action or reaction to move the creature up to 20m through the air. When the spell ends, the target falls if it is still aloft, unless it can stop the fall.

At Higher Levels: When you cast this spell using a spell slot of 4th level or higher, you can target two additional creatures for each slot level above 3rd.

__Advanced Options__
* Improved Lift: You can lift Large sized creatures
* Quick: You can cast Fly as a bonus action

## Thoughts
via @TheMarmotKing
>Fly seems… a little disappointing.  I think it would actually be cool to have a spell that makes your movement speed into a limited flying ability.  Kind of like the e5 fly spell.  SO Here is my suggestion.

## Proposal
via @TheMarmotKing
* Level: 2nd
* Casting Time: Action
* Range: Self
* Duration: Concentration, 10 min
* Detonates: no
* Primes: no

__Spell Text__
Create a negative mass effect field around yourself allowing you to move freely through the air.  During the duration of this spell, you gain a flying speed of 20m.  When the spell ends if you are still aloft, you fall to the ground.  

__Advanced Options__
* Quick Cast: Fly as a bonus action.  Increase the fly speed  to 30m
* Extended Cast: You may extend the duration of this spell to 30 minutes.

**Comment by queryluke** [comment]
So, I'm not sure when this happened, but the current version of Fly is a _very_ old version of Lift. Sometimes this happens with the data files and content gets mismatched. I've been slowly working through all the data and breaking them out into separate files so this won't happen again. In the doc you mentioned adding a new spell Levitate to replace Fly, but I don't think that's necessary. Between Lift, Pull, and Singularity, I think we've got lifting targets covered.

Anyway, my intent was to have this be exactly like 5e's fly spell. 

Do you think this should be limited to the user? Or can this be cast on another wiling creature? This would allow a higher level spell slot option of targeting more creatures.

**Comment by TheMarmotKing** [comment]
I think limiting it to the user is reasonable, and adding multi fly as an AO makes sense.

As for levetate, that wasn't going to be a target enemies spell, but a moving friends spell.  Similar to E5 levetate but not against enemies
