### ISSUE TITLE
Melee Weapon Stats

### ISSUE THREAD

**Issue by SleightxHope** [queryluke/masseffect-5e#34]
Melee weapons would be available for use by any class that has the STR score to use them. Each class' inherent melee attack weighs nothing and requires no STR, so each class keeps that in addition to anything else they want to carry.

Cerberus Operator Blade
Cost: 1000
STR Required: 12
Weight: 6
Damage: 1d8 
Qualities: Slashing, Finesse, Special 
Special: On successful attack, target must make a CON save (DC= 8+Proficiency Bonus+ STR or Dex modifier, whichever is higher). On a failed save, target takes 1d4 bleeding damage for 1 additional round. 

Krogan Warhammer
Cost: 8000
STR Required: 18
Weight: 15
Damage: 1d12
Qualities: Bludgeoning, Special
Special: On successful attack, target must make a CON save (DC= 8+Proficiency Bonus+ STR or Dex modifier, whichever is higher). On a failed save, target is knocked backwards 4 meters.

Asari Huntress Sword
Cost: 2000
STR Required: 12
Weight: 6
Damage: 1d6
Qualities: Slashing, Finesse, Light, Special
Special: When wielding this weapon, you may use a Biotic Spell (if you know any) as a bonus action when you make a successful attack. 

Kahjean Venom Dagger
Cost: 3000
STR Required: 10
Weight: 1
Damage: 1d4
Qualities: Piercing, Finesse, Light, Special
Special: On successful attack, target must make a CON save (DC= 8+Proficiency Bonus+ STR or Dex modifier, whichever is higher). On a failed save, target has the Poisoned status for 1d4 rounds. This special effect can be used once per long rest, as the micro-chem mixer in the handle synthesizes more venom.

Melee Mods for Firearms

Omni-blade Bayonet
Cost: 2000
1 Slot
Doubles weight of weapon
Allows wielder to make a bonus melee attack, using the wielder's standard melee attack to hit. Does 1d4 Slashing damage on a hit.

Stun Attachment
Cost: 3000
1 Slot
No affect on weapon weight
When you make an attack on a target within 2 meters, you may use your bonus action to make a melee attack. On a hit, the target takes no damage, but loses their reaction and bonus action if they have not already taken them that round.

Possibly more to come, but this is what I could think of right now.

**Comment by queryluke** [comment]
Love all of this. Will include it in the next release.
