### ISSUE TITLE
Jetpacks?

### ISSUE THREAD

**Issue by ouellettear5** [queryluke/masseffect-5e#352]
I'm starting to put a campaign together. As I build maps I realise the importance of three dimensional design. Cover is a huge aspect of combat in this universe, so it makes sense that PCs and enemies will be fighting for the higher ground (since elevation negates enemy cover). Jetpacks are part of the universe and could add a fun element to combat. Thoughts? Jetpacks could just be an armor mod

**Comment by queryluke** [comment]
Yeah that's a great idea!

A simple chest armor mod could be:

>As a bonus action, gain flying 6m for 1 minute. The recharges after a short rest.

Better versions could provide more uses per long rest.

**Comment by ouellettear5** [comment]
That would be cool. mod levels can be 1/day > 2/d > etc... There might be some weird  continuity with some spells; Havoc Strike sort of implies that a character has jets in some fashion already.

**Comment by Nmmoriarty** [comment]
I think an alternative would be a "if you dash you gain a fly speed of 60, if you don't end your movement on solid ground you begin to be affected by gravity or lack thereof."  Not sure what limiter should be attached, but you shouldn't be able to fly all day every day.

**Comment by Fakaozada** [comment]
I like it, but I think it should use fuel... maybe a specialized one...

**Comment by ouellettear5** [comment]
I'm hesitant to use a fuel  economy, because it adds more inventory management for PCs and DM (especially if you include NPCs) which a lot of people, myself included, try to avoid. I think limiting it to times per day is easier to manage, and will prevent people from spamming it too much.

**Comment by bpmcpherson** [comment]
I'm not sure if limiting it is necessary, either. I like the approach Andromeda took where they're less "jetpacks" and more "jumppacks". They do a quick jump and have a limited hover ability, but you're using them with the intention of jumping.

Now, if you wanted to have actual "jetpacks", then it can be equipment that can replicate the Fly biotic power X number of times before a short rest or something of that nature.
