### ISSUE TITLE
Some other questions in my campaign

### ISSUE THREAD

**Issue by Fakaozada** [queryluke/masseffect-5e#354]
Hi all,

Coming back with some more issues that happened in my campaign:

Life support built on armors: In the game Shepard don't use any other equipment to enter dangerous atmosferes, he simple put on the helmet, so my players entered a atmosfere without oxygen low gravity and some weak levels of radiation. My question: Is there any life support buit on full set armors? If so what are the stats? like time of oxygen, resistance/time to radiation...

Prices on kits: There are no prices on the tool kits, one of my players wanted to buy one, I said it was 1k...

Images on bestiary: I think we have to have images of the creatures on bestiary, because always search on google about them to show the players are a little annoying... For example, DO NOT seach for Klixen on google images...

**Comment by queryluke** [comment]
@Fakaozada 

__RE: life support__
Full stats for environmental conditions might be something we address in the future. It's a really neat idea, but it is also complex and would take some time to build a world around. If I were GMing, I would say that a full suit of armor provides a few hours of protection and life support. But this is entirely contextual to the scenarios you're running. If you players are space pirates, they might be able to salvage space wrecks for 10 hours at a time. But if they're living on the Citadel, special life support suits that are used for making Citadel repairs might be limited and hard to come by. Honestly, I'd leave this to your judgement call. Make an assertion and stick with it. If your assertion is a few hours and you have scenarios where you need more time, you can improvise upgrades to the armor. Again, not a great solution, but hopefully gets you by for the time being.

__RE: kit prices__
1k is the price I would have given as well. But I've made a note that prices for kits needs to be developed.

__RE: bestiary images__
I completely agree. I'll expedite this need in my next dev cycle. I actually have stock images for everything I've created, so it should be a simple matter of designing it for the site.
