### ISSUE TITLE
Kobold Fight Club

### ISSUE THREAD

**Issue by rexthepig** [queryluke/masseffect-5e#355]
I made this a good while ago, I've converted the Mass Effect 5e bestiary into [Kobold Fight Club](https://kobold.club/fight/#/encounter-builder). I probably should've posted this sooner, but here it is: 
https://docs.google.com/spreadsheets/d/1-5tAUUiXXMp5K1dRDIgxtgNIH16XLDbrRv65D70U2wg/edit?usp=sharing

**Comment by queryluke** [comment]
This is fantastic!!! As I create more monsters I'll be sure to add to this list. 

Also this gives me a leg up on creating my own encounter builder. Thanks!

**Comment by ouellettear5** [comment]
Super useful! I'm actually considering DnD  creatures in my campaign. They will basically by native "aliens" on more remote planets

**Comment by queryluke** [comment]
@ouellettear5 Let me know which creatures you use. I want to eventually include a list of recommended monsters from DnD.

**Comment by queryluke** [comment]
FYI - I'm marking this as complete because I've added instructions and links on the site proper (in the next release)
