### ISSUE TITLE
Weapon Mods

### ISSUE THREAD

**Issue by SleightxHope** [queryluke/masseffect-5e#36]
Weapon Mods are applied to assault rifles, shotguns, sniper rifles, submachine guns, and heavy pistols to augment them. Available mods include high-caliber barrels, scopes, and bayonet attachments, among others. Only two mods can be applied to a weapon at a time, and the same mod cannot be applied twice to a single weapon. Mods in this conversion will have 3 levels for the sake of testing/simplicity, and apply to all ranged weapons. 

Stability Dampener- Distributes recoil with sliding system of counterweights compatible with kinetic coil generators. Reduces weapon kickback, giving weapon a +1, +2, or +3 to hit depending on the level.

Extended Magazine- Increases magazine capacity, allowing more shots before needing to reload the heat sink. Increases ammo by 10%, 25%, and 50% increments per level.

Ballistic Accelerator- Capacitor boosts kinetic coil generators, increasing shot penetration. Trades damage for bullet penetration in the following ratios: -3 damage to ignore 1/2 cover at Level I, -2 to ignore 3/4 cover at Level II, -1 to ignore full cover at Level III.

Extended Barrel- Lengthens barrel, creating greater bullet velocity and impact. Does +1, +2, and +3 damage as mod level increases. 

Precision Scope- An optical lens that enhances the effective range of the weapon. Increases the weapon's Range by 10%, 25%, and 50% per level.

Thermal Scope- Much like the Precision Scope, this increases the effective range of a weapon, but trades encumbrance for the ability to see through most walls and clouds of smoke. Increase weapon's weight by 50%, range increases per level as Precision Scope.

Ultralight Materials- Different metals used in the frame of a weapon can make it easier to wield and maneuver with. Based on level, this mod reduces the weapon's weight by 10%, 25%, and 50% respectively.

Possibly more to come, this is a good start.

**Comment by queryluke** [comment]
Weapon mods are something I hadn't delved into yet, so thanks for getting the ball rolling! My only immediate hesitation is using percentages. 50% is fine, that gets used a lot in 5e: _"half of your charisma mod"_ or _"half of your class level"_. I'll noodle on these.

**Comment by SleightxHope** [comment]
Hmm, perhaps a better adjustment might be to limit mods to an improvement that scales with player level (to reflect their ability to utilize them better), making the emphasis for the player to be focused on obtaining better weapons for immediate results, since there's a large variety. What do you think of these:

Stability Dampener- Distributes recoil with sliding system of counterweights compatible with kinetic coil generators. Reduces weapon kickback, giving +1 to hit at Level 1, +2 at Level 9, and +3 at Level 17. 

Extended Magazine- Increases magazine capacity, allowing more shots before needing to reload the heat sink. Increases Heat of the weapon by 25% at Level 1 (minimum of 1), 50% at Level 9, and 75% at Level 17.

Ballistic Accelerator- Capacitor boosts kinetic coil generators, increasing shot penetration. Trades damage for bullet penetration in the following ratios: -3 damage to ignore 1/2 cover at Level 1, -2 to ignore 3/4 cover at Level 9, -1 to ignore full cover at Level 17.

Extended Barrel- Lengthens barrel, creating greater bullet velocity and impact. Does +1, +2, and +3 damage at Levels 1, 9, and 17 respectively. 

Precision Scope- An optical lens that enhances the effective range of the weapon. Increases the weapon's Range by 1 category (2M-10M-20M-60M-Artillery range) at Level 1. Increase the range a step at Level 9 and Level 17.

Thermal Scope- Much like the Precision Scope, this increases the effective range of a weapon, but trades encumbrance for the ability to see through most walls and clouds of smoke. Increase weapon's weight by 3, 2, or 1 at Levels 1, 9, and 17. 

Ultralight Materials- Different metals used in the frame of a weapon can make it easier to wield and maneuver with. Based on level, this mod reduces the weapon's weight by 1, 2, or 3 at Levels 1, 9, and 17.

**Comment by queryluke** [comment]
From #34 

Omni-blade Bayonet
Cost: 2000
1 Slot
Doubles weight of weapon
Allows wielder to make a bonus melee attack, using the wielder's standard melee attack to hit. Does 1d4 Slashing damage on a hit.

Stun Attachment
Cost: 3000
1 Slot
No affect on weapon weight
When you make an attack on a target within 2 meters, you may use your bonus action to make a melee attack. On a hit, the target takes no damage, but loses their reaction and bonus action if they have not already taken them that round.

**Comment by queryluke** [comment]
Scopes that reveal tac-cloaked enemies
