### ISSUE TITLE
Spell Review: Cryo Beam

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#360]
## Current
* Level: X-type Tech
* Casting Time: action
* Range: self, 6m cube
* Duration: instant
* Detonates: no
* Primes: cold

__Spell Text__
You spend tech points to blast a stream of liquid hydrogen from your omni-tool. Each creature in a 6m cube becomes primed-cold until the end of its next turn and must make a Constitution saving throw. A creature takes Xd8 cold damage on a failed save, or half as much damage on a successful one where X is the number of tech points spent. If the target is unprotected, it must pass a Strength saving throw or becomes frozen until the end of its next turn.

__Advanced Options__
* Brittle Freeze: Creatures that fail the Constitution saving throw suffer a -1 AC penalty
* Frozen Ground: Cryo beam leaves a patch of ice on the ground that lasts for 1 min. Each creature that moves into or out of the patch must pass a Dexterity saving throw. On a failed save, slips and falls prone, ending its movement.

## Thoughts
Initial thoughts:
- It's called cryo _beam_ so it should be a line
- Simplify the saving throws
- could be made a N-type tech spell
- replace brittle freeze completely
- frozen ground should be difficult terrain

**Comment by LyleMcAwesome** [comment]
The change to Brittle - as in full freeze - should be at a failed saving throw, whereas a success would leave him brittle or "chilled" as some games would put it.
When I first looked at the ability I expected a beam as well, and I think a 16m beam would make sense its not too long, that it has a range of a weapon, and not too short so you're not RIGHT up on them. It should be the Cryo Blast that is closer range.

**Comment by queryluke** [comment]
## Proposal
* Load: 3
* Casting Time: action
* Range: self, 8m line
* Duration: instant
* Detonates: no
* Primes: cold

__Spell Text__
Spend 4 tech points to blast a continuous stream of liquid hydrogen from your omni-tool in an 8m long by 2m wide line. Each creature in the beam must make a Strength saving throw. On a failed save, a creature takes 6d8 cold damage and then becomes frozen until the start of your next turn. On a successful save a creature takes half as much damage and isn't frozen by this spell. Creatures with at least 1 shield point have advantage on this saving throw.

A creature must also make the saving throw when it enters the beam's space for the first time on a turn or ends its turn there.

At the start of your turn, you may spend your action and an additional tech point to continue casting the beam. Your movement speed is reduced by half and you may rotate 90 degrees for 2m of movement. The spell ends if you become incapacitated.

__Advanced Options__
* Brittle Freeze: +2 load, creatures have disadvantage on their Strength saving throw. On a successful save, a creature is primed cold until the end of your next turn.
* Frozen Ground: Cryo beam leaves a patch of ice on the ground that lasts for 1 min. The ground is considered difficult terrain.


### Thoughts
I interested to head feedback on the third line of this spell. It lets the player continue to cast and reorient the beam for a greatly reduced cost, which would be great for mobs and sweeping the beam across the battlefield. But it's a bit complex and might have glaring OP holes in it.

Because of the continual cast, I refrained from adding a +tp version of the spell. However, if the continual cast is problematic, I would turn this into a "standard" spell for 3 tech points with a +1tp version of 1d8 per additional tp spent.

**Comment by SleightxHope** [comment]
I kinda like the thought of it behaving a bit like the spell Moonbeam, where you throw it out there and then continue sweeping it across enemies (just directionally instead of from above).

 I'd remove the text about rotating 90 degrees (it introduces a measurement that might complicate hex grid players, etc.) and change the text to:

"At the start of your turn, you may spend your action and an additional tech point to continue casting the beam. Your movement speed is 2m while casting it in this manner. The spell ends if you become incapacitated."

That way, they need to position themselves well before casting it into mobs, or have their allies use spells/features that push/pull enemies into their range. If they need to move, they'll need to sacrifice their continued offensive output. Makes it more strategic in nature, with a bigger payoff for good positioning.
