### ISSUE TITLE
Spell Review: Cryo Blast

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#361]
## Current
* Level: X-type Tech
* Casting Time: Action
* Range: 20m
* Duration: instant
* Detonates: no
* Primes: cold

__Spell Text__
You spend tech points to fire a mass of super cooled, subatomic particles at a creature or object within range. Make a ranged spell attack against the target. On a hit, the target becomes primed-cold until the end of its next turn and takes Xd8 cold damage, where X is the number of tech points spent, and the target's movement is reduced by half. If the target is unprotected, it must pass a Strength saving throw or becomes frozen until the end of its next turn.

__Advanced Options__
* Ice Lance: Transform the attack into a deadly lance. The attack can no longer freeze or slow the target, but you add 1d6 piercing damage for each tech point spent.
* Frigid Air: The blast snap freezes the air around the target in a 2m radius. Each creature that enters the frozen space for the first time on a turn or ends its turn there must pass a Constitution saving throw or take 2d4 cold damage.

### Thoughts
Overall, I think its fine. Bread and butter cold spell. Range needs to be increased to 30-50m.

**Comment by queryluke** [comment]
## Proposal (draft)
* Load: 1
* Casting Time: Action
* Range: 50m
* Duration: Instant
* Detonates: no
* Primes: cold

__Spell Text__
Spend 1 tech point to fire a mass of super cooled, subatomic particles. The particles explode in a 2m-radius sphere centered on a point within range. Each creature within the sphere has its movement reduced by 4m until the start of your next turn and must make a Strength saving throw. On a failed saved, a creature becomes frozen until the start of your next turn. Shielded targets have advantage on this saving throw.

You may spend additional tech points, up to your proficiency modifier, to increase the potency of this spell. For each additional tech point you spend, increase the radius of the blast by 2m.

__Advanced Options__
* Ice Lance: +2 load, When you cast cryo blast, you may transform the attack into a deadly lance instead. Make a ranged spell attack on a target within range. On a hit, the target takes 1d8 cold and 2d4 piercing damage for each tech point spent.
* Frigid Air: +1 load, The blast creates a pocket of frigid air that lasts until the end of your next turn.  Each creature that enters the frozen space for the first time on a turn or ends its turn there becomes primed cold until the end of its next turn and must pass a Constitution saving throw or take 2d6 cold damage.

### Thoughts
Though I said I thought this was fine, I realized the current version differs from the game quite a bit. Specifically, "Cryo Blast does no damage to enemies. Cryo Blast either freezes enemies solid or slows them down." ([source](http://masseffect.wikia.com/wiki/Cryo_Blast#Player_Notes_2)).

These changes transform Cryo Blast into a control spell, which is nice for Engineer's Efficiency, as it allows an Engineer to take a control spell as a "cantrip."

Priming isn't automatic. Frozen targets will be considered primed-cold (a change I have slated for the next release), so casting this spell gives the opportunity of freezing targets, thereby priming them as well.

Ice lance is a load 2 because it adds a ton of versatility, transforming this spell into either an AoE control or single target attack. Frigid Air adds back the automatic priming of any creature in the area and a little bit of damage. I'm not 100% sold on frigid air, this was a first pass.

**Comment by bpmcpherson** [comment]
I dig it.

**Comment by TheMarmotKing** [comment]
Does ice Lance also freeze the target?

**Comment by queryluke** [comment]
No, The intent is that the player chooses, when they attack, to use the damaging version or regular version.
