### ISSUE TITLE
Spell Review: Energy Drain

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#365]
## Current
* Level: X-type tech
* Casting Time: Actopm
* Range: 20m
* Duration: Instant
* Detonates: yes
* Primes: no

__Spell Text__
You spend tech points to cycle your Omni-tool, sapping electromagnetic energy from a creature you can see within range. Make a ranged spell attack against the target. On a hit, the target takes Xd4 lightning damage, where X is the amount of tech points you spent. Additionally, if you are wearing armor, gain shield points equal to half of the damage done.

__Advanced Options__
* Improved Damage: Increase the damage die type to d6.
* Improved regen: If you are wearing armor, gain shield points equal to your damage roll.

## Thoughts
- Increase the range to 50m
- Change "If you are wearing armor" to "...up to your maximum possible shields"

**Comment by LyleMcAwesome** [comment]
In my opinion, the changes make sense, both to range and the other one.
Though I think the extra damage would need a bit more spice, maybe allowing it to prime as well.

**Comment by queryluke** [comment]
## Current
* Load: 2
* Casting Time: Action
* Range: 50m
* Duration: Instant
* Detonates: yes
* Primes: no

__Spell Text__
You spend 2 tech points to cycle your Omni-tool, sapping electromagnetic energy from a creature you can see within range. Make a ranged spell attack against the target. On a hit, the target takes 3d6 lightning damage,and you regain shield points equal to half the amount of lightning damage dealt.


__Advanced Options__
* Improved Damage: Increase the damage die type to d6.
* Improved regen: If you are wearing armor, gain shield points equal to your damage roll.

## Thoughts
- Increase the range to 50m
- Change "If you are wearing armor" to "...up to your maximum possible shields"

**Comment by TheMarmotKing** [comment]
Doesnt the spell already deal lightning damage?  Also I'm interested in the idea of a -1 load, but maybe as an add on itself or an item.  I don't think it's a great idea to weaken a spell especially when you spend precious advancement points on it

**Comment by SleightxHope** [comment]
I'm inclined to agree with MarmotKing,  not really diggin' anti-shield. Maybe change that advancement option from Anti shield to something like: 

Linked Current- +2 Load. On a successful hit, you can designate yourself or an ally within range of the ability to direct a positive current to. This current doubles a creature's waking speed for 1d4 rounds. Using this advanced tech skill more than once does not stack the speed boost.

This might make the choice in advancement between a defensive boost vs. an offensive/mobility boost. Thoughts?
