### ISSUE TITLE
Spell Review: Incinerate

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#368]
## Current
* Level: X-type tech
* Casting Time: action
* Range: 20m
* Duration: instant
* Detonates: yes
* Primes: fire

__Spell Text__
You spend tech points to hurl a high-explosive, plasma round at a creature or object within range. Make a ranged spell attack against the target. On a hit, the target is primed fire and takes Xd10 fire damage, where X is the number of tech points you spent. A flammable object hit by this spell ignites if it isn't being worn or carried.

__Advanced Options__
* Frozen Combo: Deal double damage to frozen targets
* Radial Blast: On a miss, the target creature takes half damage.

## Thoughts
- Increase range to 40m
- Clarify that the detonate happens before resolving the spell effect
- Frozen combo is too limited, consider changing to any primed cold creature. Should also say the hit is considered to be a critical hit, rather than "double damage"
- Is radial blast too powerful? Perhaps reduce to a flat damage like 2d6?

**Comment by TheMarmotKing** [comment]
I think radial blast basically makes it a single target fireball with a high cost.  Tech classes need options like that to ensure they don't waste a ton of T points in one go with no reward

**Comment by queryluke** [comment]
## Proposal
* Load: 1
* Casting Time: action
* Range: 40m
* Duration: instant
* Detonates: yes
* Primes: fire

__Spell Text__
Spend 1 tech point to hurl a high-explosive, plasma round at a creature or object within range. Make a ranged spell attack against the target. On a hit, the target is primed fire and takes 2d10 fire damage. A flammable object hit by this spell ignites if it isn't being worn or carried.

__Advanced Options__
* Frozen Combo: When you hit a creature or object with Incinerate, if the target is primed cold, you deal a critical hit.
* Radial Blast: On a miss, the target takes half damage.

**Comment by TheMarmotKing** [comment]
This sounds like a perfect combo of tier based spells and the flexibility tech is supposed to bring.  Not sure what other aoe spells tech has, but maybe make radial a +2 load? If there is a 3 load spell that is aoe, incinerate becomes redundant and more costly.
