### ISSUE TITLE
Spell Review: Neural Shock

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#369]
## Current
* Level: X-type tech
* Casting Time: action
* Range: 20m
* Duration: instant
* Detonates: no
* Primes: no

__Spell Text__
You spend tech points to flash an ion laser at an organic creature within range. The creature makes a Constitution saving throw. The DC of this throw is increased by 1 for each tech point spent. On a failed save, the creature has disadvantage on the next melee or ranged attack it makes and can't take reactions until the start of its next turn.

__Advanced Options__
* Damage: A creature takes Xd6 psychic damage on a failed save or half as much damage on a successful one where X is the number of tech points spent.
* Paralyze: If a creature fails the saving throw, it is paralyzed for 1 turn.

## Thoughts
- increase range to 50m
- could be an N-type spell for 1-2 tech point(s)
- Paralyze text should be "until the end of its next turn"
- Damage seems a litter under powered compared to paralyze. Could use a buff or complete replacement.

**Comment by TheMarmotKing** [comment]
Should be "disadvantage on all attacks it makes it's next turn.". Disadvantage on one attack isn't really worth taking.  Advanced option might make it lingering for a few turns, force a repeat save.

**Comment by queryluke** [comment]
## Proposal
* Load: 1
* Casting Time: __bonus action or one reaction, which you take when you see a creature making a ranged or melee attack roll__
* Range: __50m__
* Duration: instant
* Detonates: no
* Primes: no

__Spell Text__
Spend 1 tech point to flash an ion laser at an organic creature within range. The creature makes a Charisma saving throw. On a failed save, the creature has disadvantage on melee and ranged attack attack rolls and can't take reactions until the start end of its next turn.

__Advanced Options__
* Mental Strain: +1 load, the creature takes 2d6 psychic damage when hit by the ion laser.
* Paralyze: +2 load, If a creature fails the saving throw, it is paralyzed until the end of its next turn.

## Thoughts
- Simple but effective control spell that has the benefit of being a reaction or bonus action.
- range increased
- __Charisma save__? Yep, the first charisma save on a spell. My mental justification is that the laser is sends a shock through the creature's nervous system. Instead of brute force to avoid the effects (Constitution), it takes sheer _will_ to avoid the effects, will being some mix of mental stability, personality, gusto, etc.
- disadvantage on __all__ melee and ranged until the end of the creatures turn
- __Mental strain__. Add 2d6 to the effects. Not a _ton_ of damage, but gives the player 2d6 extra per turn (if used as a bonus action). Not this damage is automatic and does not allow a saving throw.
- Paralyze: +2 load as causing paralysis is a powerful effect.
