### ISSUE TITLE
Armor Customization

### ISSUE THREAD

**Issue by SleightxHope** [queryluke/masseffect-5e#37]
For the purposes of my playtesting, all of my players are starting with a standard generic Light, Medium, or Heavy armor called Spectre Modular Hardsuits that have no special qualities besides shield generators and the typical AC as lined out in the Rules. Below are some ideas lifted from the games and converted to 5e.

HEAD

Spectre Initiate Helmet- Starting helmet for a Spectre trainee. Dual layer of fabric armor and kinetic padding within a lightweight ablative ceramic shell. Comes standard with a suite of communication, navigation, and battlefield awareness software. Can be hardsealed with an environmental mask to protect wearer from hazardous environmental conditions. 

Death Mask- Developed by Tyriel Advanced Communications Corporation (TACC), the latest version of the Death Mask offers exceptional protection and real-time data feedback that helps coordinate the wearer's melee attacks. When rolling damage dice for melee attacks, re-roll all 1's. 

Kuwashii Visor- Developed by Ariake Technologies, the wearer exchanges full protective coverage for visibility, unencumbered mobility, and increased accuracy. -1 to AC, +2 to attack rolls.

Sentry Interface- This visor works with the Sentry system, a software application that optimizes an armor suit's microframe computer. When the Sentry system is running, more power can be devoted to shield management. Add 10% of your total SP (minimum of 1) to your total while this helmet is equipped.

Kestrel Helmet- The Kestrel armor system's helmet forgoes traditional transparent visors in favor of a reinforced faceplate with an internal heads-up display. The display connects to redundant micro cameras to allow naturalistic vision inside the well-padded interior. +2 AC while wearing this helmet, as the faceplate's armor protects more vital areas.

Capacitor Helmet-  A recent design, this Alliance-made helmet stores microcapacitors in its structure to replenish spent kinetic barriers. The transpari-plast armor panel on its top can be removed to access capacitors for field maintenance. When rolling to restore depleted shields in combat, double your proficiency bonus when calculating how many SP are restored.

Archon Visor- The Archon visor uses an efficiency algorithm to balance processing power for omni-tools. A heads-up display and voice command software allows users to micromanage the systems, reducing the cool-down period between energy expenditures. Add 10% of your total TP (minimum of 1) to your total while this helmet is equipped.

Umbra Visor- A next-generation vision device that assists targeting. By detecting the focal point of the wearer's eyes and enhancing the image at that location, the visor helps direct a biotic power or tech attack exactly where the wearer is looking for maximum damage. When inflicting damage with a spell or tech power, re-roll all 1's on damage dice. 

Recon Hood- A hood issued to covert action teams, this model's optic display interfaces with most small arm's auto-targeting software, linking hand and eye for improved accuracy and increased weapon damage. Ballistic-mesh fabric and composite ceramic plating provide necessary armor, and the integral air filter helps in hostile environments. When you land a critical hit, roll an additional damage die when calculating damage.

Mneumonic Visor- Relatively new to the market, the Mnemonic Visor is difficult to find outside Alliance space. Intended for biotic specialists, this headpiece plugs into the rest of the user's suit, gathering data so it can adapt to the wearer's tactics. It boosts biotic performance at critical moments to allow a soldier to perform with greater power than normally possible. While wearing this helmet, you may choose 1 cantrip you know. This cantrip is always cast at an Advanced level, and you may choose which Advancement to use each time you cast it while this helmet is equipped.

Securitel Helmet- The Securitel Helmet was originally designed as riot-gear. It is covered in ablative plating, well-padded to lessen damage from slashes and bashing attacks. The helmet's emitters boost kinetic feedback stabilizers in the rest of the armor, while its onboard computers monitor the wearer's heart-rate and central nervous system. The wearer gains resistance to Slashing and Bludgeoning damage. 

Delumcore Overlay- Developed by Delumcore Systems, a VI inside this headgear enhances aim when targeting an enemy's vulnerable points. It also maximizes armor-cell efficiency, feeding excess power to weapon systems. While wearing this helmet, all ranged weapons roll critical hits on 19-20. This does not stack with any other feature that reduces critical hit threshold. 

CHEST

Spectre Initiate Chestplate- Starting armor for a Spectre Trainee. Interlocking plates of thick, ablative ceramic. Designed to be light, effective, and easily repaired. 

Kassa Impact Armor- Chestplate with micro-capacitors that release energy to dampen the kinetic shock of receiving a blow. As a reaction once per short rest, you may use your reaction to halve the attack's damage against you. 

Serrice Rimebane Armor- Chest plating with auxiliary power cells that defrost spots of crystalline ice caused by cryo rounds on impact. While wearing this armor, you are immune to the Frozen condition. 

Rosenkrov Reflex Armor- Sturdy armor that gathers real-time battle telemetry, and whose on-board combat computer can help a combatant move faster than they can think. Once per short rest, the wearer may use 2 Reactions on their turn instead of 1.

Armax Parade Armor- Glossy armor that shines in the light, designed to look good as its first function. While wearing this armor, you have advantage on Persuasion and Performance checks. 

Ariake Charger Armor- Armor with a biofeedback system regulating wearer's adrenaline surges. While wearing this armor, the wearer has advantage on attempts to physically push or pull a hostile creature. 

Hahne-Kedar Tactical Armor- A chestplate that disperses weight in a way that makes carrying more equipment bearable. When wearing this armor, treat your STR score as if it were 19 for the purposes of carrying equipment (unless your score is higher, then no effect occurs).

ARMS

Spectre Initiate Gauntlets- Starting gear for Spectre trainees. A combination of fabric armor and kinetic padding and plates of ablative ceramic for protection. 

Kassa Fury Gauntlets- Gauntlets that stimulate the wearer's nervous system and the muscles, making them temporarily faster and more brutal when striking. When making a melee attack while wearing these gauntlets, you may make a second attack with your Omni-tool weapon as a bonus action if you still have one. 

Serrice Adaptor Gauntlets- A pair of gauntlets that have microfabricators in their frames. These can spread omnigel through the rest of the hardsuit, inuring the combatant to a type of damage. Every long rest, you can designate a type of damage (fire, necrotic, poison, etc.) and gain resistance to it until you take another long rest.

Rosenkrov Snaring Gauntlets- Arm pieces that were designed with trench warfare in mind, they have strong electromagnets that prove especially useful when regulated by combat computers. You are immune to dropping your weapon if hit by any effect that would otherwise disarm you. Additionally, if a grenade lands within 4m of you, you may use your reaction to guide it to your hand, then throw it back. If you do so, flip a coin. On heads, the grenade affects any space you target. On tails, you receive damage as if the grenade had exploded in your space.

Armax Talon Gauntlets- A set of spiked, clawed gauntlets that give the appearance of their wearer possessing demonic hands. All melee attacks made while wearing these add 1 point of Slashing damage, and the wearer has advantage on all Intimidate checks made while wearing them.

Ariake Goliath Gauntlets- Arm plating with micro servos that coordinate muscle movements when resistance is encountered. While equipped, the wearer has advantage on all STR checks and saving throws.

Hahne-Kedar GARDIAN gauntlets- Arm gauntlets that contain power cells that fuel a miniature version of a starship's standard GARDIAN point defense lasers. When you are targeted by a heavy weapon that relies on a projectile (i.e. Hydra rockets, a Cain missile, etc.) as opposed to a Directed Energy Weapon, you may use your reaction once per long rest to target any of the projectiles with your GARDIAN and shoot it out of the sky, reducing its damage to 0. Recharges after a long rest. 

LEGS

Spectre Initiate Greaves- Spectre trainee starting gear. Dual layer of fabric armor and kinetic padding beneath thick plates of ablative ceramic and lined with additional kinetic barrier emitters. 

Kassa Overcharged Greaves- Leg plating that diverts a suit of armor's excess subsystem power into motorized joints, allowing for bursts of intense speed. Once per short rest, you may double your movement speed for a duration of 1 minute. This is a Concentration effect, as if too much damage is done and the wearer loses concentration the suit will need to redistribute that power elsewhere. 

Serrice Stealth Greaves- Greaves that secrete a highly advanced lubricant in the joints. While you wear these greaves, your steps make no sound, regardless of the surface you are moving across. You also have advantage on Stealth checks that rely on moving silently.

Rosenkov Lockdown Greaves- A pair of leg armor pieces that connect the wearer's boots to the suit's power supply, turning the boots into a powerful electromagnet. As a bonus action, the wearer can activate the effect of the greaves to stick to the surface they are walking on, provided it's made of metal. This can aid them in walking up walls, upside down, etc. This lasts for 1 minute, and gives the user advantage to resist effects that lift or move them while under this armor's effects. 

Armax Strider Greaves- Greaves that use a set of mass effect field generators to alter the wearer's gravity, making certain maneuvers much more manageable. When wearing these, you gain advantage on Acrobatics checks, and DEX checks/saving throws. 

Ariake Enviro-Greaves- A set of leg armor that makes the user much more maneuverable in a mountainous or aquatic environment with normally unsuitable terrain. The wearer gains advantage on Athletics checks made to swim or climb. 

Hahne-Kedar Power Greaves- A set of greaves that have batteries designed to conserve biotic power. The wearer may restore all of their barrier ticks as a reaction once per short rest.

**Comment by queryluke** [comment]
I haven't gotten this on the site yet, but a few weeks ago I started digging into armor mods. Basically a way for PCs to roll a custom set of armor if they have the money for it. Here was my idea. But these are also great because I wanted to have pre-made equipment as well.

https://docs.google.com/spreadsheets/d/1YEFON_0j2l9Fw8MpEeECwPMc6tMljb7odY1McKPCHYA/edit?usp=sharing

**Comment by SleightxHope** [comment]
Wow, well done with how organized that is! Feel free to integrate anything I came up with, and I'll certainly reference your lists when giving my players options!
