### ISSUE TITLE
Spell Review: Overload

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#370]
## Current
* Level: X-type tech
* Casting Time: action
* Range: 20m
* Duration: instant
* Detonates: no
* Primes: lightning

__Spell Text__
You spend tech points to unleash an electrostatic discharge at a creature or object within range. Three bolts then leap from that target to as many as three other targets, each of which must be within 6m of the first target. A target can be a creature or an object and can be targeted by only one of the bolts. A target becomes primed lightning until the end of its next turn and must make a Dexterity saving throw. The target takes Xd4 lightning damage on a failed save, or half as much on a successful one where X is the number of tech points you spent.

__Advanced Options__
* Extended Leap: Overload can leap to targets within 10m.
* Heavy Overload: Increase the damage die type to d6

## Thoughts
- Increase range to 40m
Mechanic is 5th chain lightning. I don't have issue with anything but am open to suggestions.

**Comment by TheMarmotKing** [comment]
I know it's lightning damage, but I feel like a d4 makes this spell a little too weak compared to say the d10 of incinerate.

**Comment by queryluke** [comment]
@TheMarmotKing Right. I need to create some formula that lets me compare tech spells to biotic spells damage-wise. It needs to take into account the variable nature of tech spells and the total pool of tech points. Once I've figured out what that formula looks like, I'll be able to adjust damage accordingly.

But I agree. Since this is one of the "Engineer's Efficiency" choices and a bread&butter engineer spell it needs to be just as attractive as incinerate or cryo blast.

**Comment by queryluke** [comment]
## Proposal
* Load: 1
* Casting Time: action
* Range: 40m
* Duration: instant
* Detonates: no
* Primes: lightning

__Spell Text__
Spend 1 tech point to unleash an electrostatic discharge at a creature or object within range. Three bolts then leap from that target to as many as three other targets, each of which must be within 6m of the first target. A target can be a creature or an object and can be targeted by only one of the bolts. 

A target becomes primed lightning until the end of your next turn and must make a Dexterity saving throw. The target takes 2d6 lightning damage on a failed save, or half as much on a successful one where X is the number of tech points you spent.

You may spend additional tech points, up to your proficiency modifier, to increase the potency of this spell. The damage increase by 2d6 for each additional tech point you spend.

__Advanced Options__
* Extended Leap: +2 load, Overload can leap to as many as five other targets within 10m.
* Heavy Overload: +1 load, Increase the damage die type to d8

**Comment by TheMarmotKing** [comment]
So basically, get rid of a bunch of shields at once.  Nice.  I assume you've already done the math on damage and tech points, plus it's a save to that's good.  But overall I'm feeling like the big three, overload, incinerate and cryo blast really got good reworks
