### ISSUE TITLE
Spell Review: Salvo

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#371]
## Current
* Level: X-type tech
* Casting Time: action
* Range: 20m
* Duration: instant
* Detonates: yes
* Primes: no

__Spell Text__
You spend tech points to create glowing darts of plasma equal to the number of tech points spent. Each dart hits a creature of your choice that you can see within range. A dart deals 1d4+1 fire damage to its target. The darts all strike simultaneously and you can direct them to hit one creature or several.

__Advanced Options__
* Exploding Salvo: Each dart deals an additional 1d4 thunder damage.
* Blinding Salvo: The darts explode in a bright flash of light. Targets no longer take damage but must make a Constitution saving throw. On a failed save, a target is blinded until the end of your next turn.

## Thoughts
- Increase range to 50m
- Clarify number of darts equals number of tech points.
- Blinding salvo should be optional and no longer detonate either.

**Comment by TheMarmotKing** [comment]
Like the changes, not much to say this is ported magic missile

**Comment by queryluke** [comment]
## Proposal
* Load: 2
* Casting Time: action
* Range: __50m__
* Duration: instant
* Detonates: yes
* Primes: no

__Spell Text__
Spend 1 tech point to create three glowing darts of plasma. Each dart hits a creature of your choice that you can see within range. A dart deals 1d4+1 fire damage to its target. The darts all strike simultaneously and you can direct them to hit one creature or several.

You may spend additional tech points, up to your proficiency bonus, to increase the potency of this spell. The number of darts you create increases by 1 for each additional tech point you spend.

__Advanced Options__
* Exploding Salvo: +2 load, each dart deals an additional 1d4 thunder damage.
* Blinding Salvo: +2 load, When you cast salvo, you may create phosphorous darts instead. The darts no longer deal damage and cannot detonate primed targets. Instead, each dart explodes in a bright flash of light. Each creature hit by a dart must succeed on a Constitution saving throw or becomes blinded until the end of your next turn.


### Thoughts
2 tech point for an avg of 15 damage. There are no spell attacks which makes it even better. So I've bumped this up to 2 tech points. The load is only 1 so it's available at lower levels.

+2 load for exploding salvo because it's at least 3 extra damage, but an average of 8 (again, always hits). Plus, an tech caster can max this out for 7 tech points, equivalent to a 4th-level spell (7th-8th in 5e) and deal an average of 48 damage. that's on part with a 4th level aoe spell (hence 4 load)

+2 load blinding salvo because of the versatility

**Comment by bpmcpherson** [comment]
That seems reasonable to me.
