### ISSUE TITLE
Spell Review: Shocking Grasp

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#372]
## Current
* Level: X-type tech
* Casting Time: action
* Range: touch
* Duration: instant
* Detonates: no
* Primes: lightning

__Spell Text__
Spend tech points to send an electric shock from your omni-tool to a creature you try to touch. Make a melee attack against the target. You have advantage on the attack roll if the target is wearing armor. On a hit, the target becomes primed-lightning until the end of its next turn and takes Xd6 lightning damage where X is the number of tech points spent, and it can't take reactions until the start of its next turn.

__Advanced Options__
* Reach: increase the range to 4m
* Improved shock: Increase the damage die to d8

## Thoughts
This came straight from 5th. I don't think it works as an X-type spell because it doesn't deal enough damage compared to other single target X-type spells AND is requires a range of touch. It needs to have some other benefit like shield regen.

**Comment by TheMarmotKing** [comment]
I think this is a perfect opportunity for a stun.  Make it a 1 turn paralyze or stun with a little damage, but primary as a control spell.  Maybe points spent increase the save DC.

**Comment by queryluke** [comment]
## Proposal
* Load: 1
* Casting Time: action
* Range: touch
* Duration: instant
* Detonates: no
* Primes: lightning

__Spell Text__
Spend 1 tech point to send an electric shock from your omni-tool to a creature you try to touch. Make a melee spell attack against the target. You have advantage on the attack roll if the target is wearing armor. On a hit, the target becomes primed-lightning until the end of your turn and takes 1d6 lightning damage. Then the target must succeed on a Constitution saving throw or become stunned until the end of your next turn. A target with at least 1 shield point has advantage on this saving throw.

You may spend additional tech points, up to your proficiency bonus, to increase the potency of this spell. The damage increases by 2d6 for each additional tech point you spend.

__Advanced Options__
* Restoring shock: +1 load, if you are wearing armor, gain shield points equal to half the damage dealt. This cannot increase your shield points beyond their maximum capacity.
* Improved shock: +1 load, increase the range to 4m and the damage die to d8

## Thoughts
The addition of stun makes this a combination of a Monk's Stunning Strike and the Shocking Grasp.

**Comment by TheMarmotKing** [comment]
Love it.  Small damage, but great stuns.  Great for the engineer that needs to stun and run away or the vanguard that's being a melee tank little shit.  (My turian player loves to just punch people to death while wearing tech armor and barriers)
