### ISSUE TITLE
Spell Review: Unity

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#373]
## Current
* Level: X-type tech
* Casting Time: action
* Range: touch
* Duration: instant
* Detonates: no
* Primes: no

__Spell Text__
You spend X tech points and tap into the medical interface of a fallen comrade. You revive a friendly creature that has gone unconscious or died within the last minute. That creature returns to consciousness or life with hit points equal to Xd4 + your proficiency bonus.

__Advanced Options__
* Unrestricted: There is no limit to the amount of TP you may spend on this ability.
* Quick: You can use Unity as a reaction to the creature falling unconscious or dying.

## Thoughts
This is a pretty weak spell. When a creature is incapacitated because its hit points are below 0, any amount of healing will revive them. So there would be no reason to use this over first aid. 

I think this needs to change to weak AoE heal like mass healing word from 5th:
target 6 creatures withim 20m, gain hit points equal to Xd4 + spellcasting mod.

**Comment by TheMarmotKing** [comment]
Add some range and a small shield restore and you've got a great "get them back in the action" spell.  More tech points for more heal, and add an option to spend more points for multi res.  Another option for enhanced shield restore, maybe even a temp extra shield points

**Comment by queryluke** [comment]
## Proposal
* Load: 2
* Casting Time: action
* Range: 20m
* Duration: instant
* Detonates: no
* Primes: no

__Spell Text__
Spend 3 tech points to spawn a swarm of healing nano bots, up to six creatures of your choice that you can see within range regain hit points equal to 1d6 + your spellcasting ability modifier.

You may spend additional tech points, up to your proficiency bonus, to increase the potency of this spell. The healing increases by 1d6 for each additional tech point you spend.

__Advanced Options__
* Unrestricted: +1 load, There is no limit to the amount of tech points you may spend when you cast this ability.
* Shield Restore: +2 load, Creatures also gain 1d4 shield points for each tech point you spend.
