### ISSUE TITLE
Vehicles

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#377]
Figured this had gotten to the point of sharing. Still a work in progress and I'm actively working on stat blocks for vehicles. Feel free to comment here or on the sheet.

https://docs.google.com/document/d/1J6ylmiR1eWVWNlbmyNlaY5lLUpIguBLV_zpM3YoSwI4/edit?usp=sharing

**Comment by TheMarmotKing** [comment]
I'm continuously amazed at how comprehensive and well thought out all of this is.  This is legitimately professional level content you're putting out.  Not to mention the website design is fantastic.  Seriously If this whole project doesn't have heads from professional content creators turning I'd be shocked.  Just had to put this out there after seeing the vehicle section in all it's glory.  While I'm ranting, I've started a 4 man campaign with a couple of DND e5 veterans, and they are loving it.  3 have never played mass effect but are still getting really into all of it.  Not to mention everyone is super impressed by the website.  Keep up the amazing work you guys, this whole project is really an inspiration in the way of quality content creation.  I hope I can keep throwing my 2 cents in with school going!

**Comment by queryluke** [comment]
@TheMarmotKing Best way to start a Monday :) 

And your 2 cents (you've provided more than that) has been invaluable!

**Comment by bpmcpherson** [comment]
It looks like a solid start. Perhaps there should be a designation between civilian-accessible crafts and military? It could make it where a non-military person getting access to them is harder or illegal, meaning that black market channels are required to typically obtain one.

**Comment by SleightxHope** [comment]
I love it so far! On owning a ship, perhaps these could be rolled into a GM section? Like potential plot hooks. 
Maybe the military owns your ship and you receive your missions from them. Maybe you stole your ship, and you need to keep moving to avoid anyone taking a close look at your ship's ID. Maybe you own your ship, but had to take a loan from a crime lord to get it, and now you're working off your debt. There could also be taxes, docking fees, and other expenses to keep you in the hole.

Also, what do you think about luxury suites on board that might provide permanent bonuses to prevent disgruntled crew? Like a bar/lounge, theater, game room, etc. Maybe roll 2d6 when rolling for disgruntled crew and take the lower. 

Thoughts?

**Comment by TheMarmotKing** [comment]
In the campaign I have going, the party took a ship from some pirates dumb enough to attack the passenger ship they were on.  The one thing I'll note here for posterity is that I made them either intimidate the pirates for the ship access codes or hack their omnitools for them.  Now the engineer (who's a comp sci major irl) has different levels of access set up.  Just in case he ever wants to airlock the party you know?  But owning a ship and getting it's ID set up with CSec was a good rp experience in for them

**Comment by Swampson** [comment]
@bpmcpherson & @SleightxHope, with regards to civilians accessing military ships, one thing that I've seen in other games which I personally like is to list the ship's cost as "military" instead of a number of credits. This indicates the vehicle is not available for purchase normally.

Of course, it will be up to individual GMs to decide how to handle this, but I think its' probably a good baseline for establishing certain ships as unobtainable on the open market.

**Comment by queryluke** [comment]
@SleightxHope 

RE: Owning a ship
Yes, I'm going write up rules on ship acquisition. It's ultimately up to the players & GM on how they acquire the ship, but I'm going to provide examples.

Also, I'm going to write rules for upkeep, which will incorporate things like maintenance and fuel. I hand't thought about taxes/docking fees which is something to employ.

RE: Reducing disgruntled crew
Not sure when you read the doc, but at some point I added a rec room and ugraded kitchen, which give a -1 bonus to the disgruntled crew roll. Currently, that roll is 1d6 = number of disgruntled crew. But these specialized systems reduce the final roll.

**Comment by SleightxHope** [comment]
Apologies, must have missed the rec room/kitchen bits, I'll look again. Otherwise, everything on ships looks mega-solid. The only suggestion I might have is to streamline it as much as possible, giving Advantage instead of numerical bonuses when possible to cut the amount of math. 
Grateful for your work!

**Comment by queryluke** [comment]
closed with #382
