### ISSUE TITLE
New Skill: Knowledge- Xenology

### ISSUE THREAD

**Issue by SleightxHope** [queryluke/masseffect-5e#38]
Serving as almost a replacement for the Arcana and Religion knowledge skills, this skill would serve as a catch-all for a PC trying to recall facts about another species' culture, religion, fashion, biology, etc. 

For example, a successful Xenology check would inform a human PC about the Drell gods and goddesses, and a History check would reveal more concrete events, like the fact that 1983 CE was when the Drell evacuated their homeworld with the help of the Hanar. 

Or, a Xenology check would inform a Turian PC that the Quarians are highly susceptible to bacterial infection if their suits are ruptured, and a successful Medicine check would let him aid his Quarian teammate in patching their suit with omnigel.

**Comment by queryluke** [comment]
added in #44
