### ISSUE TITLE
Armor mods

### ISSUE THREAD

**Issue by TheMarmotKing** [queryluke/masseffect-5e#380]
So where exactly are the rules for applying mods to preexisting armor not custom armor? Is it possible to do so?  Can stock armor get mods? I'm not seeing anything on the site about it and I just wanted to check

**Comment by queryluke** [comment]
So, my intent was that pre-existing armor (armor sets) could not have custom mods installed, this includes stock armor.

My idea is that custom armor has a barrier of entry (the cost of the customizable piece). This is a light restriction to keep low-level characters from acquiring or purchasing mods a lot of mods.

If you're finding that too restrictive in your campaign, let me know.

**Comment by TheMarmotKing** [comment]
Alright, it's not very clearly stated in the armor rules. If anything a footnote to clarify.

In both campaigns I've started players early on want to try stuff like jump Jets and jetpacks.  I understand the balance aspect, but perhaps we could add variant rules in which head, legs, and arm gear start with 1 mod slot and chest with 2 (or just 1)so the DM can use mods as rare magic rewards rather than make players wait till they have money.  I know that's how I'll play it even if it's not in the rules, as I like giving them the opportunity to both spend money on worthwhile things and find attunment like items

**Comment by queryluke** [comment]
For v0.90, I've been writing a lot of clarification and explanation of the rules. 

[Custom Armor](https://github.com/queryluke/masseffect-5e/blob/v090/static/data/rules/06-03-custom-armor.md)

[Mods](https://github.com/queryluke/masseffect-5e/blob/v090/static/data/rules/06-05-mods.md)

Stock armor is really only intended for early level characters. In a lot of the playtests I've run, I've started players at level 3-5 and given them additional credits to purchase customized armor and mods. Or I've outlined restrictions like, "You all have a full set of armor type of your choice, your chest has 1 mod slot, and your legs or arms have 1 mod slot. You can pick mods worth 20,000 or less." 

So, yeah, if you're starting all your players with jump jets or customizable mods, go for it. Adjustments like that are entirely at the GMs discretion.

**Comment by queryluke** [comment]
closed with #382
