### ISSUE TITLE
Spell Review: Tactical Scan

### ISSUE THREAD

**Issue by TheMarmotKing** [queryluke/masseffect-5e#381]
This ability may need a Nerf.  My younger brother and I went on a test drive play, he as a Drell Infiltrator.  To be fair, I gave him a lot of money to start with and he of course bought a Black Widow.  
  
What we learned was that Tactical scan is incredibly good at allowing infiltrators to destroy single targets. The 20m range on the ability limits it a little, but not much.  The automatic advantage and improved crits plus sneak attack allowed him to Nat 20 and deal 50 damage to a character while he was a lvl 3.  Then 2 turns later he Nat 19 critted that enemies twin brother with his omniblade and killed him.  

It was hilarious, but I had to keep checking to see if he was reading it right.  The spell is one of the few I'd consider it essential to upgrade.

My suggestion ls that the 19 critted is removed or that the time for the ability is shortened or made concentration. It's redundant for vanguards and a little too strong for the rest of the classes.  

I want it to remain a strong ability, but 1 minute with no save and 2 extremely strong effects is Nerf worthy especially since it's lvl 1 accessable.

Btw my younger brother loved playing the mod and has been bugging me to continue since we started 👍

**Comment by queryluke** [comment]
This is what I have for v0.9.0:

>Spend your action scanning a creature you can see, studying its movement and revealing weaknesses. Make a Wisdom (Insight) check, contested by the target's Charisma (Deception) check. On a success, you have advantage on attack rolls against the target and natural 19 and 20's are considered critical hits. This benefit lasts 1 minute or until you successfully use this feature against a different target.

**Comment by TheMarmotKing** [comment]
Oh thank god

**Comment by queryluke** [comment]
closed with #382
