### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by TheMarmotKing** [queryluke/masseffect-5e#383]
So I've been waiting for this update for a while now and I could not be more excited to see it finally here!  Even If I was against the tech point changes,I think the new class updates are really well done and have a lot to offer.  

The vehicles look incredible and I can't wait for my players to try to head to head a dreadnaught in a mako.  

The site has so many new features I want to try out, it was worth the wait!

All that being said, would you say it's time for a feat review?  That section hasn't been edited in a while if I remember and I think there's room for some really cool improvment there.

Again, super hype for the new update, going to go pour over it now!

**Comment by queryluke** [comment]
Oh, and I'd like to revisit subraces
