### ISSUE TITLE
Bookmarks are broken

### ISSUE THREAD

**Issue by GameMasterPo** [queryluke/masseffect-5e#386]
This is been going on since last night after the update every time I click on the bookmarks I have the page says system failure or something like that just want to let y'all know that it's broken right now if you can fix it that's great cuz I have some bookmarks of enemies that I really need to access for my campaign

**Comment by queryluke** [comment]
Ah, sorry about that. Clearing the cache will have removed the creature you saved. But glad its working for you now.
