### ISSUE TITLE
Make older versions of site available

### ISSUE THREAD

**Issue by EvanED** [queryluke/masseffect-5e#387]
Would it be possible to make old versions of the PHB available? (Without checking out the repo, blah blah blah.)

This seems like it would be especially feasible nowadays that you have the ability to generate that PDF -- even just the old PDFs would be great. (It seems like it might be easier to make that available than the whole site?)

There will be an update to the rules and despite the changelog messages (which are good, I'm not criticizing that) it would be a lot easier to really see what changed if I could bring up old and new side-by-side.

**Comment by queryluke** [comment]
@EvanED Sure thing! The old pdf is still available here:
https://drive.google.com/drive/u/0/folders/1eDfgpG3JplKUjrIdySJKmyC4qxTi2MUT

I plan on keeping all versions of the PDFs in this folder.

I have thought about ways of hosting the older versions of the site, I can make a separate repo for each release tag. There are a few hurdles with pathing to work around and I'd want to make some other adjustments like a banner that explains outdated content. But yes, that's certainly a near-ish future goal.

**Comment by EvanED** [comment]
Perfect, thanks! That link, or a page you make themed with the rest of the ME site listing the contents, or something like that, I think might be useful to add to the assets page, but that's up to you. :-) Would get a lot of the benefit of the multiple versions thing much easier. (And I did see an older issue about supporting multiple versions, so I know that was on your radar already.)
