### ISSUE TITLE
Occulus Drones

### ISSUE THREAD

**Issue by rexthepig** [queryluke/masseffect-5e#388]
This might be me being an idiot, but the Reaper Capital Ship stat block says it can summon 1d10 Occulus Drones, but there are no stats anywhere for these.

**Comment by queryluke** [comment]
Nope, you're not an idiot. I haven't finished the Occulus stat block yet. I've got a short list of new monsters that didn't make it in that I'll release in the next week or so.

**Comment by rexthepig** [comment]
Good, I was just checking you hadn't forgot to publish the stats or something.

**Comment by queryluke** [comment]
added in #392
