### ISSUE TITLE
Consumable Program Suggestion

### ISSUE THREAD

**Issue by SleightxHope** [queryluke/masseffect-5e#393]
To start off, it's been a while since I've checked up on this project, and you're killin' it! Super excited at what you've put together. 

The wording on consumable programs, like Experimental_Barrier_Generator.exe, could maybe have a better in-universe explanation on why they're consumables (i.e., why they delete themselves.)

I propose a tag or category for these programs: "Unstable Code". An Omnitool program with unstable code might be used X amount of times before it degrades and is unusuable any further, needing to be re-installed by finding or purchasing a new program. This way, the program doesn't just delete itself arbitrarily. 

Again, love how everything is coming along!

**Comment by queryluke** [comment]
Did you see the current explanation? (Under Omni-tool programs on the [Equipment Rules](https://n7.world/phb/rules/equipment) page)

> Manufacturers and militaries quickly realized it was much easier, cheaper, faster, and (usually) safer to send bits of data rather than physical products, and let fabricators generate the devices on site using generic materials, like omni-gel. After the advent of omni-tools, a number of industries used this method to ship their products. However, to avoid unauthorized replication, the programs would scrub themselves once the job was complete.

**Comment by SleightxHope** [comment]
I actually missed that. >.> My apologies.

**Comment by queryluke** [comment]
No worries1 I really like the unstable code idea. I think it should be another type of program. When they get the program they'll roll a die and get to use it X times. Rolls like 1d4 + 1 or 1d8, etc.

**Comment by SleightxHope** [comment]
Good idea!
