### ISSUE TITLE
Additional Feats

### ISSUE THREAD

**Issue by SleightxHope** [queryluke/masseffect-5e#394]
More Mass Effect themed feats for review, let me know what you think:

**Nerves of Steel**- Traveling the galaxy has exposed you to violence and cruelty, and not much can make you flinch any more. You gain the following benefits and features:
Increase either your Intelligence, Wisdom, or Charisma score by 1, to a maximum of 20. You have Advantage on all saving throws made to resist becoming Stunned.

**Card Shark**- You've sunk considerable time into playing cards for credits in seedy dives and upscale casinos alike, and through countless wins and losses you've honed your gamesmanship into a thing of beauty.   You gain the following benefits and features:
Increase your Charisma score by 1, to a maximum of 20. 
You gain proficiency with two types of gaming sets of your choice.  
You have advantage on Charisma (Deception) checks to bluff opponents in games of chance, and Charisma (Persuasion) checks to convince others to join you for a game. 

**Grace Under Fire**- While others may lose their cool in the face of sustaining a wound, you've learned how to use that burst of pain and stress to move faster. You gain the following benefits and features:
Increase your Dexterity or Intelligence score by 1, to a maximum of 20.
Immediately after you receive damage from an enemy attack, you may use your reaction to move up to half your movement without provoking an attack of opportunity. 

**Come Get Me**- Conventional wisdom in combat is to avoid being targeted. You prefer an alternate school of thought, keeping enemies focused on you and off of your less stalwart allies. You gain the following benefits and features:
As an action, you can make a feint to draw enemy attention. This feint may be a war cry, a loud insult, or a different distraction, per your GM's discretion. All enemies within 16 meters must make a Wisdom saving throw (DC 8 + your proficiency bonus + your Charisma modifier). 
On a successful saving throw, a target is unaffected and is immune to this effect for the next 24 hours. On a failed saving throw, an enemy has disadvantage on attacking any creature besides you for the next minute, or until they make an attack against you. You may use this ability once per short or long rest.

More to come later!

**Comment by queryluke** [comment]
@SleightxHope I think these are great as is. The only one I slightly changed was Nerves of Steel, giving them advantage against being frightened and stunned.

They're included in v0.9.2
