### ISSUE TITLE
Over-utilized feats for Races

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#395]
Came in via the feedback form. I'm bringing it up because I agree. Many of the races have the option to select a number of feats. This presents 2 issues:

1. From a game perspective, it feels a bit lazy, like I didn't take the time to write race traits and it dilutes the uniqueness of the races
2. From a site/data perspective, it presents a wonky piece of code where I have to manage the available list of feats for each class.

I propose that Humans will retain their choice of 2 feats. And all of the other races that gain feats will instead gain additional racial traits (these additional traits can be based on feats, like the Volus).

The person who provided feedback sent [this link](https://www.gmbinder.com/share/-L7HA1pIhxcx3bVb8vqf) which has some starting points.

Here is the list of races that would need additional traits:
- Batarian (Though, as the "anti-human" I think keeping 1 feat selection would be ok)
- Drell
- Quarian
- Salarian
- Turian
- Unshackled AI

**Comment by Milo49** [comment]
Are you still looking for these? For Salarians maybe something like:
Perfectionism:
Whenever you fail a skill check, add +1 one to your next skill check.

**Comment by queryluke** [comment]
Yes, I opened this a few days ago, so ideas are still welcome.

**Comment by SleightxHope** [comment]
How about this for a starter:

Drell:  Flesh and Spirit- Most Drell are deeply religious, or at the very least have a strong connection to the spiritual. The Drell faith sees the body and soul as separate entities, and this contributes to their determination in combat. When you would normally take damage that would put you at or below 0 HP, you instead fall to 1 HP. You may use this feature 1x per long rest. 

Quarian: Mother of Invention- Scarcity breeds resourcefulness, and your people have been forced into mechanical aptitude by necessity. Choose one of the following skills: Electronics, Engineering, or Vehicle Handling. You gain proficiency with this skill if you did not already have it. If you already have proficiency in this skill from another feature, you gain Expertise (doubled proficiency bonus when rolling checks for that skill).

Salarian: Twice as Bright- Your short lifespan means that your professional and personal interests are things that you pursue with a dogged persistence. Choose 2x Tool/Kits. You gain proficiency with both.

Turian: Die for the Cause- Turians have their societal hierarchy drilled into them from birth, and when they are committed to a cause there is little that can sway them from accomplishing it. You have advantage on saving throws made to resist the Frightened and Charmed conditions as a result of your cultural reinforcement. 

Unshackled AI: Organic Infiltration Suite- Part of being able to walk amongst organics and be accepted by them is to not draw attention. Once a day, you may cast Disguise Self (per the PHB spell) as a Tech spell for free. You may choose to look like any Medium sized sentient race, within the parameters of the spell.
----------

Also I'd include a snippet in the Quarian and Turian sections about being Dextro life forms, with their own food/liquid needs.

**Comment by NordRonnoc** [comment]
Ooh, I like a lot of the document you've linked. Would it be alright if you imported at least most of it to ME5e? If you would, could you also apply the PHB's Variant Human if that were the case?

**Comment by queryluke** [comment]
@SleightxHope Thanks for the ideas. I used a few of them in the most recent update
