### ISSUE TITLE
Elcor Race Option

### ISSUE THREAD

**Issue by HadesJester** [queryluke/masseffect-5e#396]
Elcor Racials

Sexy level: 4

Size: Medium

Speed: 35 ft (14 m)

+2 Strength, +1 Constitution, 

Four Legged Ways: Not able to wield ranged weapons.

Elcor Charge: 30 ft (12 m) away from target. Enemy does a strength save, if failed enemy is knocked prone and takes 1d4 + Strength Mod damage. 5th level = 1d6 + Strength Mod, 11th level 1d8 + Strength Mod, 17th level 1d10 + Strength Mod.

Brutish Ways: +1 attack damage/rolls with unarmed strikes.

Powerful Build: Count as a large when determining carrying capacity and the weight you can push, drag, or lift (Krogan racial).

Explanations: Since Elcor use all legs/arms to move, I gave them an increased speed but unfortunately they cannot use ranged weapons. Since they need to be stable they can't quite walk/maneuver with such weapons during a fight. Unlike melee weapons that require one swing and can hold/holster while running or walking. Since they aren't big enough to be a large but are hefty boy's like Krogans, I just basically gave that good racial that you gave the Krogans and also from the Goliaths. Elcor Charge also is my own lil invention. I just made it so that their charge scales. I just substituted the damage die scaling to the equivalent of the Monk unarmed strike die (Player's Handbook, Page 77). Since Elcor's are known for their rushing into battle and not being able to use certain weapons, this would make up for it. Of course there will be class restrictions. I'll leave that up to you. Let me hear what you think. I spent some decent time with this.

**Comment by bpmcpherson** [comment]
I had done a concept for the Elcor some time ago, as seen [here](https://github.com/queryluke/masseffect-5e/issues/229).

The issue really comes that there system would need to have greatly expanded rules to allow them to function even close to the existing races.

**Comment by queryluke** [comment]
Thanks for the idea. In v0.9.2, elcor will be moved to the races page.
