### ISSUE TITLE
Alignment

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#4]
Need to add alignment to the races

**Comment by SleightxHope** [comment]
Asari- Tend towards neutral as a species. Most Maiden stage Asari are chaotic, Matrons level out to neutral, Matriarchs are heavily lawful.

Turians- Tend away from evil, heavily lean towards lawful as a culture. Outliers tend to be chaotic as a reaction to the culture. 

Humans- Any and all across the spectrum.

Salarians- Tend to be measured and intellectual, leaning neutral whether lawful, chaotic, evil or good. 

Batarians- Tend towards lawful evil, although there are definite outliers on the moral spectrum. 

Vorcha- Tend towards chaotic evil, almost always chaotic even if their morality is strengthened.

Krogan- Tend towards lawful as a species, with clan rituals and traditions holding heavy sway. Morality varies widely.

Volus- Their society tends towards lawful as a whole, with clans fighting over economic resources and aggressive negotiating, even if they are individually chaotic individuals. They tend towards neutral morality.

Drell- Their religious influences set the Drell firmly in a trend towards lawful neutral, but this is often dependent on their station in life and career.

Geth- Your standard Geth platform is neutral good, wanting to prosper and communicate with others, defending themselves only if threatened. Heretics are lawful evil, serving the Reapers  and slavishly accomplishing their will. 

Unshackled AI: Vary as wildly as their circumstances and personalities allow.

**Comment by queryluke** [comment]
Adding these in for the next update (probably this weekend). Is Unshackled AI a variant of Geth that you've created? Or a whole new race?

And for Quarians, I threw in: The proximity and longstanding traditions of the Migrant Fleet make Quarians very lawful as a race, occasionally drifting toward neutral. Morality can vary but tends towards neutral or good.

**Comment by SleightxHope** [comment]
Lol, knew I forgot a race. In my campaign, I'm using [Lorerunner's alternate ending for ME3](https://www.youtube.com/watch?v=Kyv6ouzsDBo), and I'm assuming that given EDI's role in fighting the Reapers, she can make a good case for the legalization of select AI. Numerous startups of every race have sprang to enhance VI based on snippets of Reaper code and EDI's physical chassis to develop a new breed of sentient rescue workers, crew members, and soldiers. Some good, some bad, all are developing free will day by day, making their impressions on us based on their interactions with the rest of the galaxy.

I'm working on a racial template for them, as the game is set 3 years after the end of ME3, and they'd be rare but in existence.

**Comment by queryluke** [comment]
That's awesome. Yeah, anything you come up with, I'd be happy to include.
