### ISSUE TITLE
random Height & Weight Table

### ISSUE THREAD

**Issue by rexthepig** [queryluke/masseffect-5e#403]
I saw there was no random height and weight table like in the phb, so I thought I might try and create one myself. I don't really have any experience in creating these, so I may have made a few small errors.

https://docs.google.com/spreadsheets/d/1-C3e8eU5X19S7UupGd3k6Dpa9yo1JwcnGx7LgWqx1Xc/edit#gid=0
### Clarifications
I gave the geth a set height of 6"5'. Whilst there are no doubt geth of different sizes, I thought most geth would probably be the same height, and someone using a random height and weight generator probably wants something that fits the norm.

The hanar have both a height and length table. This is because the height table refers to how tall the hanar "stand" on their tentacles, but I didn't think that would have much effect on their weight, so I created the length table, which refers to the length of their body and is used to determine the hanar's weight.

The unshackled AI assumes the player is playing as a human-like body similar to EDI's. If a player wants a body more similar to that of another race, then they could use the base height and height modifier of their desired race and the base weight and weight modifier of the unshackled AI, but I haven't really tested this out so it might not work properly.

Also, I'm not too sure about the elcor's weight, I didn't want to make them _too_ heavy, but I think I may have actually made them too light?

**Comment by NordRonnoc** [comment]
Looks good, though I looked at Drack's profile on the Mass Effect site, which states he stands at 196 cm (approx. 6'5" for us Americans) and weighs 340 kg (nearly 750 pounds) with prosthetics. You can check out the other Milky Way-based characters in Andromeda on their website for reference.

**Comment by rexthepig** [comment]
@NordRonnoc Ok, maybe I should lower the base height to 6'3" and raise the height modifier to 2d8, giving them a minimum height of 6'5" and a maximum of 7'7". I would need to lower the weight modifier from 2d20 to 2d12, or the maximum weight would be 970 pounds, making the maximum weight 714 pounds (not quite 750 lb. but Drack seems to be abnormally heavy anyway).
I guess the modifier could also be 3d10, making the maximum weight 810 lb., but I think that's a little too heavy.
