### ISSUE TITLE
Ghost Infiltrator Change

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#41]
GHOST INFILTRATOR:

2 Efficient Cloak

6 Uncanny Dodge

10 Supreme Sneak- you have advantage on a Stealth check if you move no more than half your
speed on the same turn.

14 Evasion

18 Ever Vigilant- You can take two turns during the first round of any combat. You take your first turn at your normal initiative and your second one at your initiative -10.

This turns the ghost into more of a sneak/evade/survive type of Infiltrator, a' la the Thief archetype.

**Comment by queryluke** [comment]
I took out efficient cloak because it ran as OP in a few playtests I did. If I do add it back, I would add it much later. Instead I threw in a Melee specialist talent for Ghost's (which I ended up renaming shadow). But there are still one or two features I'm not a fan of. I'm still not even sold on melee specialist as a talent.

**Comment by SleightxHope** [comment]
For the level 2 ability, how about a Silent Cloak? It still costs TP to activate, but it also dampens your sounds so enemies who use sonar or microphones to detect intruders can't hear or see the Ghost.

**Comment by queryluke** [comment]
Agreed, "Melee Specialist" seems more like a feat than a perk a class gets. I think this makes a lot of sense, and moves towards the Ghost/Shadow class to a Thief build.
