### ISSUE TITLE
Melee Specialist

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#43]
Should be a feat. 

Need to replace subclass features in Infiltrator (#41) & Vanguard

**Comment by SleightxHope** [comment]
I recommend reworking the Slayer's Melee specialist into the following:

Biotic Bullrush- When you successfully make a melee or ranged weapon attack while adjacent to your target, they must make a CON saving throw (8+your prof. modifier+your casting modifier) or be knocked back 4m by the backdraft of biotic power you wield.

**Comment by queryluke** [comment]
I really like the name and the knock back. Since this is replacing a talent that focuses the Vanguard into a melee build, I looked at augmenting Charge, as it is the primary means for a Vanguard to close the distance to it's target.

I ended up modifying Charge, removing the shield regen, and switching it to a ranged attack rather than saving throw.

Resulting in this buff:

Biotic Bullrush - Learn the Charge cantrip. If you have already learned the Charge cantrip, you may learn a new cantrip instead. The distance of your Charge cantrip is now 14m. When you hit a target with Charge, the target is knocked back 4m before it becomes prone. In addition, a portion of the kenetic force is transferred into you shield's mirco-capacitors. Gain shield points equal to half the damage done, rounded down.

If that gets too OP for level 6, it might be worth removing the sheild regen, as there are plenty of opportunities for that with tech and armor mods.

**Comment by SleightxHope** [comment]
I like that better. Personally, I think that the shield regen might be a bit much for lvl 6, maybe toss that in for the Slayer at a higher level.
