### ISSUE TITLE
Soldier: 2nd Fighting style when?

### ISSUE THREAD

**Issue by SleightxHope** [queryluke/masseffect-5e#46]
Looking over the Soldier, gets Fighting Style at lvl 1. But, does not get an advancement, whereas (if memory serves) Vanguard and Sentinel get an advancement eventually. I propose sticking the advancement in for the Soldier alongside a Combat Power @ lvl 9.

**Comment by queryluke** [comment]
Yeah, this was an oversight. lvl9 sounds good to me!
