### ISSUE TITLE
Knowledge: Lore- Combine Knowledge: History and Knowledge: Xenology

### ISSUE THREAD

**Issue by SleightxHope** [queryluke/masseffect-5e#47]
I propose that both knowledge skills (one about a species' history and one about their culture and biology) be rolled into Knowledge: Lore.

**Comment by queryluke** [comment]
Agreed, deciding which check to use can get fuzzy. I'm wondering if it might be simpler to drop Xenology and use Medicine for biology based checks and History for culture/history/politics. What do you thing?

**Comment by SleightxHope** [comment]
Hmmm... Yeah, I think we can drop Xenology entirely. As much as it's a cool idea, WotC really does think of everything, and I think editing the description for the Medicine and History skills would be better.
