### ISSUE TITLE
Export Online Character Sheet to Printable PDF

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#494]

**Comment by milgner** [comment]
I was looking for this feature and then saw that this issue exists and is marked as `wontfix`. I wonder what the reason behind it is? I realise that creating PDF from the browser is quite an involved process. But I guess it would not be as involved to take an existing PDF with form-fillable fields and then fill it in with character data using [pdf.js](https://github.com/mozilla/pdf.js)?

**Comment by queryluke** [comment]
The TL;DR version is that the site is in maintenance mode at this point. Content updates are determined by the discord moderators and I'm just working on bug fixes. I assist as needed if there are other developers who want to create site features/improvements. Technically everything is "wontfix" ...which is the wrong label, it should be more like "didn't get around to fixing"

**Comment by milgner** [comment]
Thanks for the explanation! I'm thinking about implementing it but am not sure whether to write it as a stand-alone tool that converts the JSON exports to PDF or integrate it into the Nuxt-based site. It seems like I'd be more flexible with a separate application but having it integrated into the site would probably be much more accessible.
So if you'd be willing to integrate it, I'll keep that in mind as an option after having done a proper evaluation for the complexity.

**Comment by queryluke** [comment]
If you can write the scripts to take the JSON export and turn it into a PDF, I don't mind finalizing that last 1% and integrating those scripts directly onto the site.
