### ISSUE TITLE
Backgrounds

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#5]
Are backgrounds important enough to covert?

**Comment by Swampson** [comment]
I think they could be at some point, but not necessarily for an alpha/first playtest. To me, the backgrounds seem like the kind of thing that are designed to help first-time players or people who are trying to roll up a character really quickly. I think they can pretty easily be replaced by good role-playing in a more experienced group.

So in summary, "yes, but not yet."

**Comment by SleightxHope** [comment]
Sample backgrounds:

---------
Military:

You joined your species' military as a youth, and were trained day in and day out in modern warfare. You might have spent some years in the service, left it to pursue mercenary work, or became part of a civilian militia during an interplanetary conflict. When you choose this background, work with your GM to determine which military organization you served with, your rank, and experiences. 

Skills: Athletics, Intimidation
Proficiencies: All armor, one type of gambling game (Skyllian 5, Quasar, etc.), land vehicles.
Equipment: A badge of rank, trophy from a fallen foe, set of cards, common outfit, and 1000 credits.

-------------------
Crewman:

You were crew on a starship for years. You've been harassed by pirates, survived meteor storms, and outrun slavers. Your first love is the sight of space in the viewport, but you needed a change of scenery from your old vessel. Discuss the nature of your previous ship with your GM, and your role on it.

Skills: Engineering, Piloting
Proficiencies: Repair kits, vehicles (space)
Equipment: A repair kit, souvenir from your last ship, common outfit and 1000 credits.

More to come

**Comment by SleightxHope** [comment]
More backgrounds:

Colonist:

You grew up on a colony that sat on the threshold of known space. You and your family know the value of adventure, to boldly go where no one has gone previously. Perhaps your family is still out on the verge, living peacefully, or perhaps they fell victim to pirates, slavers, or the Reapers. Discuss the nature of your home world with the GM. For some reason, you decided to leave your colonial life and set out among the stars once again. 

Skills: Perception, Survival
Proficiencies: One type of artisan's tools, vehicles (land)
 Equipment: A set of artisan's tools of your choice, a tattoo or patch on your jacket denoting your colony's sigil, common outfit and 1000 credits.

Feature: Eye for Survival

As part of an expeditionary crew to colonize a distant world, it's important to know what flora and fauna might be capable of killing you. Choose a type of terrain from among the following: Desert, forest, plains, volcano, underground, mountains, tundra, or urban. You have advantage on Survival, Nature, and Perception checks made in that environment.

-------------------------------------------------------------------------------------------------------------------
Politician

You understand the value of power, and the power of well placed words. You or your family have significant influence in your world's political structure. Work with your DM to come up with an appropriate title or family history and determine how much authority that carries. 

Skill Proficiencies: History, Persuasion
Tool Proficiencies: One type of gambling game (Skyllian 5, Quasar, etc.), 
Equipment: An expensive outfit, Presidium access codes, and 2500 credits. 

Feature: Grease the Wheels

As a result of your position, you can go places and learn things that other, less privileged members of society cannot. You may use your position to influence law enforcement to overlook small offenses, gain an audience with a society's upper class, and occasionally receive complimentary accommodations.

More to come.

**Comment by queryluke** [comment]
AHHH ALL OF THESE ARE FANTASTIC 🦄

**Comment by queryluke** [comment]
added in #44
