### ISSUE TITLE
Weapon stats

### ISSUE THREAD

**Issue by queryluke** [queryluke/masseffect-5e#55]
@SleightxHope [here is a first pass ](https://docs.google.com/spreadsheets/d/132iB2ONH0BzlHUlGA9DRHMRP0aUu0I_dpQlJzSgoOXY/edit?usp=sharing) at redoing weapon damage.

Using the information from the Wiki:
**Weight**: 1 per 10 pts, rounded up. 
**Heat**: Clip size / (rof*2)
**RoF**: 1 (semi-automatic), 2 (shotguns), 3(three-round burst), 4(automatic)
**Damage**: 1-20 (d4), 21-40 (d6), 41-60(d8), 61-80(d10), 81-100(d12)

I'll introduce a new weapon type: **Semi-Automatic**, which will say something like, when you take the attack action on your turn, you can use a bonus action to fire this weapon a second time. So each Semi-auto weapon is really 2dX if fired twice. 

I wanted to hear your thoughts as this change nerfs quite a few weapons. But they stats should be much more similar to the game now.

**Comment by SleightxHope** [comment]
I took a look at the spreadsheet. Looks good for now, when 3.0 rolls out I'll update my players' weapons. The weapons felt a bit random and unbalanced before, hopefully this helps a bit!
