### ISSUE TITLE
Reaper Forces

### ISSUE THREAD

**Issue by AusartheGelid** [queryluke/masseffect-5e#60]
For the Beastiary, I think the challenge ratings for reaper forces should remain low, as a result, the DM could give the overwhelming swarm fell of reaper troops. Something along the lines of my redone Bandit Captain posted below.

Marauder - 
Medium humanoid (synthetic-organic), chaotic evil
Armor Class - 
15
Hit Points - 
65(10d8+ 20)
Speed - 
30 ft. ft.
STR15 (+2) | DEX16 (+3) | CON14 (+2) | INT14 (+2) | WIS11 (0) | CHA14 (+2)
Proficiency Bonus - 
+2
Saving Throws - 
Str +4, Dex +5, Wis +2
Skills - 
Intimidation +4, Athletics +4
Senses - 
passive Perception 10
Languages - 
none
Challenge - 
2(450 XP)
Description - 
Marauders are harvested turians that command and protect other Reaper troops. The lean, armored creatures present a significant threat in and of themselves, but they are especially dangerous when leading a Reaper task force.
Actions - 
Fortify Reapers: As an action, the Marauder can give all Husk and Cannibals in 4 m aura +2 AC until its next turn
Phaeton: Assault Rifle Attack: +5 to hit, range 10 m., one target. Hit: RoF 5, Damage D4, Heat 2

**Comment by queryluke** [comment]
I agreed on the lower CR of reaper forces.In the play testing I've done, I was creating reaper forces with these CR:

Husks 1/8 - 1/4 (there are a few varieties)
Cannibals 1/2
Marauders 1
Scion 3
Brute 5
Banshee 8
Harvester 20*
Reaper 30*

*(I haven't actually done any play testing with a reaper or harvester).

I've got a mess of notes on possible skills for all of them, just need to find the time to organize and publish. Thanks for the Marauder stats!
