### ISSUE TITLE
Angaran Option?  Outcasts, Aya, Vaults. Etc 

### ISSUE THREAD

**Issue by kikibee1991** [queryluke/masseffect-5e#63]
By any chance would Angaran race  fit into this? Kadara port, Aya? Navigation?

**Comment by queryluke** [comment]
They certainly could! For right now I'm focusing on the original trilogy. But at some point I could see writing out an Andromeda expansion.

**Comment by queryluke** [comment]
This issue will be broken out into separate issues. E.g., for angara race see #205
