### ISSUE TITLE
Armor Mod Slots Clarification

### ISSUE THREAD

**Issue by Swampson** [queryluke/masseffect-5e#69]
When creating armor, the player has the option of paying additional credits in order to add more mod slots onto a piece of armor than that armor would include by default. In the RAW, it is not clear whether it is possible to customize existing armor in this manner.

Short version: can I pay 20,000 credits to add a mod slot to a piece of armor I loot after an encounter, or can this **only** be done when creating armor from scratch?

**Comment by queryluke** [comment]
You can upgrade existing armor (or armor you've found on the battlefield). I think I hinted at this in the example, but it's not clearly stated.
