### ISSUE TITLE
Thermal Clip Clarification

### ISSUE THREAD

**Issue by Swampson** [queryluke/masseffect-5e#70]
In the standard Thermal Clips rule, the Capacity is rated at 6. In the context of this rule, does this refer to the capacity of **specialized** thermal clips, i.e., my character can have two each of cryo, disruptor, and shredder thermal clips, and can also carry an infinite number of standard clips?
Similarly, in the Thermal Clips (Variant) rule, the capacity is listed at 10 - does this mean my character can carry 10 thermal clips total, with the implication they could be any combination of specialized and/or common thermal clips - e.g., if I have 5,000 credits I can carry 10 incendiary clips and have my character hum “I Don’t Want to Set the World on Fire” when they walk into battle?

**Comment by queryluke** [comment]
You are correct.

Standard version - 6 **specialized** thermal clips, infinite regular. The justification being that thermal clips are so prevalent that you can find them anywhere. However, I'm going to make the executive decision right now that this needs to be dropped down to 4.

Variant version - 10 thermal clips of specialized or regular.

**Comment by Swampson** [comment]
I will update wording accordingly.
