### ISSUE TITLE
Heavy Weapon Charges

### ISSUE THREAD

**Issue by Swampson** [queryluke/masseffect-5e#71]
In RAW, it is not clear whether the 20,000 credit cost to resupply HW charges refers to 20,000 credits **per charge**, or 20,000 credits for a complete resupply of charges. I would assume it’s the former, as various HW have different number of charges.

**Comment by queryluke** [comment]
It's the latter (resupply is for all charges). The charges of a weapon (in my mind) translate to uses per long rest (assuming you can afford the resupply during a long rest). The variance is based on the damage potential, for example:

|weapon|dmg|charges|total|
|---|---|---|---|
|spitfire|12d4|3|90|
|landon|4d8|10|180|
|hydra|4d12|1|26|

On the surface they look lopsided, but the spitfire is an aoe and allows a dex saving throw to reduce damage. The landon is limited to 4d8 per target. You can fire it 10 times, but each time you fire it requires you need to spend a round targeting (which make you very vulnerable). The hydra looks weak, but it's missile is pretty dirty. It first removes all shields and/or barriers, then reduces their AC, then deals it's 26 damage.

**Comment by Swampson** [comment]
OK, that makes sense. Is there a way to assign this issue to me and I'll update the rules language to make this explicit?
