### ISSUE TITLE
Tech Points Recharging

### ISSUE THREAD

**Issue by Swampson** [queryluke/masseffect-5e#72]
Would it make sense to allow for a certain number of TP to recharge on a short rest, since Combat abilities refresh on a short rest? Something like 1d4 or similar?

**Comment by queryluke** [comment]
Yeah, I like that. Which also means the armor mods can increase the die type of the regen.

**Comment by Swampson** [comment]
So we should change the wording to something like "All tech points are regained on a long rest. On a short rest, you regain 1d4 tech points (this can be increased through armor mods)".

Just want to confirm and I can make the change.

**Comment by queryluke** [comment]
Yep, that sounds good.
