### ISSUE TITLE
Armor Weight

### ISSUE THREAD

**Issue by Swampson** [queryluke/masseffect-5e#77]
The armor rules do not indicate how to determine the weight for a given piece of armor.

**Comment by queryluke** [comment]
Making another issue to make Carry Capacity (and rename to Encumbrance) a variant rule. Originally I wanted to limit the number of weapons a character can bring into battle using this rule, but I think that can simply be a discussion between the GM and players.

Either way, armor would need weight. So looking at 5e encumbrance, given a Strength of 12 (60lbs max), light armor would be ~1/6, medium ~1/2, heavy ~1.

I didn't want to use lbs, so capacity is based on your flat STR score, but this was only assuming weapon encumbrance. I think it should be doubled. So, given a str of 12 (24), I think a simple light 1, medium 2, heavy 3, should work.

**Comment by Swampson** [comment]
So is each piece of heavy armor weight 3? Meaning a helmet weighs the same as the torso armor?

The other way you could handle this is that armor only has a weight if it's being carried instead of worn, with the justification being that equipped armor (so long as a character is proficient in it) is effectively weightless; either because it's real light (light armor) or because there's servos and stuff that help you move in it (heavy armor) or a combination of both (med armor).
That would allow you to keep your same carry capacity formula (flat STR score) which is quite elegant and still serves to limit how many guns you can carry.

**Comment by queryluke** [comment]
Yeah, how about when I write out the encumbrance variant example, I explain that armor and weapon weights are completely optional, and use this armor weight matrix:

|piece|light|medium|heavy|
|---|---|---|---|
|head|1|2|3|
|chest|2|4|6|
|arms & legs|0|1|2|

All light = 3, all medium = 6, all heavy = 11

Given a str of 12, you can still carry a light weapon with heavy armor, cause you can up to 5 more before you start getting penalized.

**Comment by Swampson** [comment]
OK, sounds good! I will let you write this one out and then I'll proof it for you.

**Comment by Swampson** [comment]
If arms & legs are separate slots, wouldn't the actual weights be:

All light = 3, all medium = 8, all heavy = 13?

**Comment by queryluke** [comment]
Ah, shit, you're right.

Let's make it

|piece|light|medium|heavy|
|---|---|---|---|
|head|1|1|2|
|chest|2|3|4|
|arms & legs|0|1|2|

**Comment by Swampson** [comment]
So:
all light = 3, all medium = 6, all heavy = 10. That's the intent, right?

**Comment by queryluke** [comment]
correct
